"use strict";
// Production-source offline DOM checks. No browser, R, provider or network.
const fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const assert = require("node:assert/strict"), {webcrypto, createHash} = require("node:crypto");
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/review.js"), htmlPath = path.join(repo, "workbench/static/review.html");
const results = [], copy = value => JSON.parse(JSON.stringify(value)), sha = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must use textContent");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui() {
  const source = fs.readFileSync(sourcePath, "utf8"), html = fs.readFileSync(htmlPath, "utf8"), elements = new Map(), storage = new Map(), timers = new Map(); let timer = 0;
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate production HTML ID"); elements.set(match[2], new Element(match[1]));}
  const harness = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm() {return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}},
    setTimeout(callback, delay) {timers.set(++timer, {callback, delay}); return timer;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); assert(harness.fetchImpl, "Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args); harness.el = id => document.getElementById(id);
  harness.cycle = id => {const nodes = descendants(harness.el("strategy-operations")); return nodes.find(node => node.getAttribute("id") === id);};
  return harness;
}
const inputHash = "a".repeat(64), proposalHash = "b".repeat(64), reviewHash = "c".repeat(64), evidenceHash = "d".repeat(64);
function proposal() {return {schema: "scagentkit.strategy.v1", rationale: "Preserve measured biological signal pending analyst review", risks: [], inferences: [], qc: {method: "none"}, analysis: {normalization_method: "LogNormalize", scale_factor: 10000}, pcs: {method: "fixed", ndim: 12}, batch: {method: "none"}, clustering: {resolution: 0.5}, umap: {run: true}};}
function diagnostic(status = "available") {return {schema: "scagentkit.cycle.evidence.v1", status, reasons: status === "available" ? [] : ["Insufficient measured S genes"], species: "human", assay: "RNA", counts_layer: "counts", cells: 96, features: 2000,
  columns: {s_score: "sc_cycle_S.Score", g2m_score: "sc_cycle_G2M.Score", phase: "sc_cycle_Phase", difference: "sc_cycle_CC.Difference"}, cohort: {input_cells: 96, scored_cells: status === "available" ? 96 : 0, unknown_cells: status === "available" ? 0 : 96, removed_cells: 0},
  gene_set: {source: "Literal analyst list", version: "test.v1", species: "human", package: "test", hash: "e".repeat(64), mapping_explicit: true},
  coverage: {S: {requested: 10, present: 8, expressed: 7, present_fraction: 0.8, expressed_fraction: 0.7}, G2M: {requested: 12, present: 9, expressed: 8, present_fraction: 0.75, expressed_fraction: 2 / 3}},
  normalization: {method: "LogNormalize", scale_factor: 10000, source: "genuine raw counts", layer: "data", scope: "isolated diagnostic copy"}, reference: "fixed_full_input", refit_after_qc: false,
  phase_counts: {G1: 40, S: 26, G2M: 30, Undecided: 0, Unknown: status === "available" ? 0 : 96}, score_distributions: {s_score: {median: 0.12}, g2m_score: {median: 0.08}, difference: {median: 0.04}}, scoring: {search: false, set_ident: false}, control: {applicable: status === "available"}, options: {seed: 42}};}
function answer(enabled = true, method = "none", status = "available") {
  const details = {canonical_proposal: proposal(), background: {facts: {species: "human"}}, quality: {cell_count: 96}, applicability: {executable: true, blockers: []}, capabilities: {cycle: "unsupported", doublet: "unsupported"}, source: {kind: "manual"}};
  if (enabled) {details.canonical_proposal.cycle = {method, reason: "Explicit analyst choice"}; details.cycle_diagnostics = diagnostic(status); details.capabilities.cycle = ["none", "full", "difference"]; details.applicability.cycle = {status: status === "available" ? "applicable" : "blocked", retained_cells: 90, design_rank: 3, design_columns: 3, regressor_variance: {"sc_cycle_S.Score": 0.05, "sc_cycle_G2M.Score": 0.04}, reference: "fixed_full_input", refit_after_qc: false};}
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "offline-token", run: {schema: "scagentkit.run.v1", project_id: "offline-cycle", input_hash: inputHash, revision: 7, status: "awaiting_review", stage: "strategy_propose", context: {species: "human"},
    review_node: {kind: "strategy", project_id: "offline-cycle", input_hash: inputHash, expected_revision: 7, proposal_hash: proposalHash, review_hash: reviewHash, evidence_hash: evidenceHash, can_decide: true, can_revise: true, can_undo: false},
    strategy_review: {schema: "scagentkit.strategy.review.v1", hash: reviewHash, input_hash: inputHash, evidence_hash: evidenceHash, details}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.state.continuation = value.continuation || null; h.call("render"); return h;}
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("legacy six noncycle operations are unchanged", () => {const h = setup(answer(false)); assert.equal(h.el("strategy-operations").children.length, 6); assert.equal(h.cycle("cycle-card"), undefined); assert.match(h.el("strategy-unsupported").textContent, /Cell-cycle regression and doublet/); assert.equal(h.requests.length, 0);});
  await check("cycle-enabled strategy has seven readonly observations and one central approval", () => {const h = setup(); assert.equal(h.el("strategy-operations").children.length, 7); assert.equal(h.cycle("cycle-card").tagName, "SECTION"); assert.equal(descendants(h.cycle("cycle-card")).some(node => ["BUTTON", "INPUT", "TEXTAREA", "SELECT"].includes(node.tagName)), false); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.el("annotation-approve").disabled, true); assert.equal(h.requests.length, 0);});
  await check("none defaults to keeping signal without deleting cells", () => {const value = answer(); delete value.run.strategy_review.details.canonical_proposal.cycle; const h = setup(value); assert.match(h.cycle("cycle-method").textContent, /none.*keep.*default/); assert.match(h.cycle("cycle-regressors").textContent, /none/); assert.match(h.cycle("cycle-card").textContent, /does not delete cells/);});
  await check("full displays exact saved score regressors and biological risk", () => {const h = setup(answer(true, "full")); assert.match(h.cycle("cycle-regressors").textContent, /sc_cycle_S.Score, sc_cycle_G2M.Score/); assert.doesNotMatch(h.cycle("cycle-regressors").textContent, /CC.Difference/); assert.match(h.cycle("cycle-risk").textContent, /Full regression.*remove biological signal/); assert.match(h.cycle("cycle-risk").textContent, /labels are not biological truth/);});
  await check("actual production column vector and applicability without regressors display reviewed scaling inputs", () => {for (const [method, expected] of [["none", "none"], ["full", "sc_cycle_S.Score, sc_cycle_G2M.Score"], ["difference", "sc_cycle_CC.Difference"]]) {const value = answer(true, method), details = value.run.strategy_review.details; details.cycle_diagnostics.columns = ["sc_cycle_S.Score", "sc_cycle_G2M.Score", "sc_cycle_Phase", "sc_cycle_CC.Difference"]; details.applicability.cycle = {status: "applicable", retained_cells: 2540, regressor_variance: [0.00191, 0.00170], design_rank: 3, design_columns: 3, scoring_status: "available", reference: "fixed_full_input", refit_after_qc: false}; assert.equal(Object.hasOwn(details.applicability.cycle, "regressors"), false); const h = setup(value); assert.equal(h.cycle("cycle-regressors").textContent, "Reviewed scaling inputs: " + expected + (method === "none" ? ". Keep the saved signal." : "")); assert.match(h.cycle("cycle-cohort").textContent, /Projected retained cells: 2,540/);}});
  await check("column vectors require the bound schema and exact four role order", () => {for (const mutate of [details => details.cycle_diagnostics.columns.pop(), details => details.cycle_diagnostics.columns.push("extra"), details => details.cycle_diagnostics.schema = "unsupported"]) {const value = answer(true, "full"), details = value.run.strategy_review.details; details.cycle_diagnostics.columns = ["sc_cycle_S.Score", "sc_cycle_G2M.Score", "sc_cycle_Phase", "sc_cycle_CC.Difference"]; mutate(details); const h = setup(value); assert.match(h.cycle("cycle-regressors").textContent, /Unknown; saved score columns are unavailable/);}});
  await check("ordinary choices remain none and full with difference collapsed as advanced", () => {const h = setup(); assert.match(h.cycle("cycle-ordinary").textContent, /none.*default.*full.*standard/); assert.doesNotMatch(h.cycle("cycle-ordinary").textContent, /difference/); assert.equal(h.cycle("cycle-advanced").tagName, "DETAILS"); assert.equal(h.cycle("cycle-advanced").open, false); assert.match(h.cycle("cycle-goal").textContent, /If proliferation or cell cycle is the research goal.*consider.*none/);});
  await check("explicit advanced difference displays only its exact saved score regressor", () => {const h = setup(answer(true, "difference")); assert.match(h.cycle("cycle-method").textContent, /difference.*advanced/); assert.match(h.cycle("cycle-regressors").textContent, /sc_cycle_CC.Difference/); assert.doesNotMatch(h.cycle("cycle-regressors").textContent, /S.Score|G2M.Score/); assert.match(h.cycle("cycle-difference-risk").textContent, /preserves the cycling\/noncycling contrast.*reducing differences between phases/); assert.equal(h.cycle("cycle-advanced").open, false);});
  await check("available evidence displays fixed pre-QC cohort and actual coverage", () => {const h = setup(); assert.equal(h.cycle("cycle-status").dataset.status, "available"); assert.match(h.cycle("cycle-cohort").textContent, /before QC; no refit.*96.*96.*0.*90/); assert.match(h.cycle("cycle-coverage").textContent, /8 \/ 10.*7 \/ 10.*0.8.*0.7.*9 \/ 12/s); assert.equal(h.cycle("cycle-details").open, false);});
  await check("insufficient evidence is Unknown with reasons and no inferred phase", () => {const h = setup(answer(true, "none", "insufficient")); assert.match(h.cycle("cycle-status").textContent, /Unknown.*insufficient/); assert.match(h.cycle("cycle-record").textContent, /Insufficient measured S genes.*Unknown/s);});
  await check("missing evidence and missing columns are disclosed", () => {const value = answer(true, "full"); delete value.run.strategy_review.details.cycle_diagnostics; const h = setup(value); assert.match(h.cycle("cycle-status").textContent, /Unknown.*unavailable/); assert.match(h.cycle("cycle-regressors").textContent, /Unknown/); assert.match(h.cycle("cycle-coverage").textContent, /Unavailable/);});
  await check("exact gene source hash species mapping normalization and summaries remain visible", () => {const h = setup(); const record = h.cycle("cycle-record").textContent; assert.match(record, /Literal analyst list.*test.v1.*human/s); assert(record.includes("e".repeat(64))); assert.match(record, /mapping_explicit.*true.*LogNormalize.*genuine raw counts.*isolated diagnostic copy/s); assert.match(record, /sc_cycle_Phase.*phase_counts.*score_distributions.*design_rank/s); assert.match(h.cycle("cycle-provenance").textContent, /Human and mouse symbols are not inferred by changing case/);});
  await check("gene strings render literally without HTML evaluation or case conversion", () => {const value = answer(); value.run.strategy_review.details.cycle_diagnostics.gene_set.mapping = [{input: "Mki67", output: "<img src=x onerror=never()>"}]; const h = setup(value); assert.match(h.cycle("cycle-record").textContent, /Mki67.*<img/s); assert.equal(descendants(h.cycle("cycle-card")).some(node => ["SCRIPT", "IMG"].includes(node.tagName)), false);});
  await check("cycle edits use whole JSON and disable approval until central save", async () => {const h = setup(answer(true, "full")), p = proposal(); p.cycle = {method: "difference", reason: "Preserve cycling contrast"}; h.state.strategyDraftText = JSON.stringify(p); h.call("buttons"); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);});
  await check("whole revision transports no cycle action or execution", async () => {const h = setup(answer(true, "full")); const p = copy(h.state.view.run.strategy_review.details.canonical_proposal); p.cycle = {method: "difference", reason: "Preserve cycling contrast"}; h.state.strategyDraftText = JSON.stringify(p); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Complete strategy review";
    h.fetchImpl = async (_, options) => {const request = JSON.parse(options.body), result = answer(true, "difference"); result.run.revision = 8; result.run.review_node.expected_revision = 8; result.run.strategy_review.details.canonical_proposal = request.proposal; return {ok: true, json: async () => result};};
    await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); const request = JSON.parse(h.requests[0].options.body); assert.equal(h.requests[0].url, "/api/run-review/decision"); assert.equal(request.kind, "strategy"); assert.equal(request.action, "revise"); assert.deepEqual(request.proposal, p); assert.equal(request.expected_revision, 7); assert.equal(h.el("strategy-approve").disabled, false); assert.match(h.cycle("cycle-regressors").textContent, /CC.Difference/);});
  await check("one central approval records a decision without local computation", async () => {const h = setup(answer(true, "difference")); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Reviewed full plan"; h.fetchImpl = async () => {const result = answer(true, "difference"); result.run.status = "ready"; result.run.stage = "strategy_apply"; result.run.review_node = null; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 1); assert.equal(JSON.parse(h.requests[0].options.body).action, "approve"); assert.equal(h.requests.some(request => request.url.includes("continue")), false);});
  await check("stale revision preserves the complete draft and blocks decisions", async () => {const h = setup(), p = proposal(); p.cycle = {method: "full", reason: "Explicit new choice"}; h.state.strategyDraftText = JSON.stringify(p); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Complete review"; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale strategy approval"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.stale, true); assert.equal(h.state.strategyDraftText, JSON.stringify(p)); assert.equal(h.el("strategy-approve").disabled, true);});
  const report = {schema: "scagentkit.cycle.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(test => test.passed).length, failed: results.filter(test => !test.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n"); process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
