"use strict";
// Production-source offline DOM checks. No browser, R, provider or network.
const fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const assert = require("node:assert/strict"), {webcrypto, createHash} = require("node:crypto");
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/review.js"), htmlPath = path.join(repo, "workbench/static/review.html");
const results = [], copy = value => JSON.parse(JSON.stringify(value)), sha = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must use textContent");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui() {
  const source = fs.readFileSync(sourcePath, "utf8"), html = fs.readFileSync(htmlPath, "utf8"), elements = new Map(), storage = new Map(), timers = new Map(); let timer = 0;
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate production HTML ID"); elements.set(match[2], new Element(match[1]));}
  const harness = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm() {return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}},
    setTimeout(callback, delay) {timers.set(++timer, {callback, delay}); return timer;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); assert(harness.fetchImpl, "Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args); harness.el = id => document.getElementById(id);
  harness.doublet = id => {const nodes = descendants(harness.el("strategy-operations")); return nodes.find(node => node.getAttribute("id") === id);};
  return harness;
}
const inputHash = "a".repeat(64), proposalHash = "b".repeat(64), reviewHash = "c".repeat(64), strategyEvidenceHash = "d".repeat(64), doubletEvidenceHash = "e".repeat(64), selectionHash = "f".repeat(64);
function proposal(method = "keep") {return {schema: "scagentkit.strategy.v1", rationale: "Review saved predictions without automatic deletion", risks: [], inferences: [], qc: {method: "none"}, analysis: {normalization_method: "LogNormalize", scale_factor: 10000}, pcs: {method: "fixed", ndim: 12}, batch: {method: "none"}, clustering: {resolution: 0.5}, umap: {run: true}, doublet: {method, reason: "Explicit analyst choice"}};}
function diagnostic(status = "available") {return {schema: "scagentkit.doublet.evidence.v1", status, reasons: status === "available" ? [] : ["Rate assumption unresolved"], species: "human", assay: "RNA", counts_layer: "counts", cells: 4, features: 2000,
  reference: "fixed_full_input", refit_after_qc: false, full_called_cohort: false, technology: "declared_droplet_other", columns: {score: "sc_doublet_score", class: "sc_doublet_class"}, capture: {method: "column", column: "capture_id", source: "Declared two physical loading units; donor is distinct"}, rate: {method: "manual", source: "Analyst documented loading plan", value: 0.08, sd: 0.02}, input_source: "Explicit synthetic called-cell raw-count fixture", parameters: {seed: 17}, scoring: {function_name: "scDblFinder::scDblFinder", versions: {scDblFinder: "1.26.7", SingleCellExperiment: "1.34.0"}}, capture_stats: {loading_A: {input_cells: 2, expressed_features: 1900, expected_rate: 0.08, expected_doublets: 0.16, predicted_doublets: 1, predicted_fraction: 0.5, unknown_cells: 0, status}, loading_B: {input_cells: 2, expressed_features: 1850, expected_rate: 0.08, expected_doublets: 0.16, predicted_doublets: 0, predicted_fraction: 0, unknown_cells: 0, status}}, cohort: {predicted_doublets: 1, input_cells: 4, scored_cells: status === "available" ? 4 : 0, unknown_cells: status === "available" ? 0 : 4}};}
function answer(enabled = true, method = "keep", status = "available") {
  const canonical = proposal(method), details = {canonical_proposal: canonical, background: {facts: {species: "human"}}, quality: {cell_count: 4}, applicability: {executable: true, blockers: []}, capabilities: {doublet: "unsupported"}, source: {kind: "manual"}};
  if (enabled) {details.doublet_diagnostics = diagnostic(status); details.doublet_evidence_hash = doubletEvidenceHash; details.capabilities.doublet = ["keep", "remove_predicted"]; details.applicability.doublet = {method, evidence_hash: doubletEvidenceHash, selection_hash: selectionHash, qc_keep_cell_ids: ["cell-1", "cell-2", "cell-3"], selected_cell_ids: method === "remove_predicted" ? ["cell-1", "cell-3"] : ["cell-1", "cell-2", "cell-3"], removed_cell_ids: method === "remove_predicted" ? ["cell-2"] : [], scoring_status: status, processed_reuse: false, input_cells: 4, qc_retained: 3, removed_cells: method === "remove_predicted" ? 1 : 0, retained_cells: method === "remove_predicted" ? 2 : 3,
    per_capture: {loading_A: {input_cells: 2, predicted_input: 1, qc_retained: 2, predicted_after_qc: 1, predicted_qc_excluded: 0, removed: method === "remove_predicted" ? 1 : 0, retained: method === "remove_predicted" ? 1 : 2, removed_fraction_after_qc: method === "remove_predicted" ? 0.5 : 0, retained_fraction_after_qc: method === "remove_predicted" ? 0.5 : 1, removed_fraction_input: method === "remove_predicted" ? 0.5 : 0, retained_fraction_input: method === "remove_predicted" ? 0.5 : 1}, loading_B: {input_cells: 2, predicted_input: 0, qc_retained: 1, predicted_after_qc: 0, predicted_qc_excluded: 0, removed: 0, retained: 1, removed_fraction_after_qc: 0, retained_fraction_after_qc: 1, removed_fraction_input: 0, retained_fraction_input: 0.5}},
    cycle: {status: "insufficient", evidence_hash: "0".repeat(64), phase_by_scope: {full_input: {G1: 0, S: 0, G2M: 0, Undecided: 0, Unknown: 4}, post_qc: {G1: 0, S: 0, G2M: 0, Undecided: 0, Unknown: 3}, proposed_removed: {G1: 0, S: 0, G2M: 0, Undecided: 0, Unknown: method === "remove_predicted" ? 1 : 0}}, score_by_scope: {post_qc: {s_score: {median: null}}}}};}
  else delete canonical.doublet;
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "offline-token", run: {schema: "scagentkit.run.v1", project_id: "offline-doublet", input_hash: inputHash, revision: 7, status: "awaiting_review", stage: "strategy_propose", context: {species: "human"},
    review_node: {kind: "strategy", project_id: "offline-doublet", input_hash: inputHash, expected_revision: 7, proposal_hash: proposalHash, review_hash: reviewHash, evidence_hash: strategyEvidenceHash, can_decide: true, can_revise: true, can_undo: false},
    strategy_review: {schema: "scagentkit.strategy.review.v1", hash: reviewHash, input_hash: inputHash, evidence_hash: strategyEvidenceHash, details}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.state.continuation = value.continuation || null; h.call("render"); return h;}
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("disabled doublet keeps exact original six-card interface", () => {const h = setup(answer(false)); assert.equal(h.el("strategy-operations").children.length, 6); assert.equal(h.doublet("doublet-card"), undefined); assert.equal(h.el("strategy-unsupported").textContent, "Cell-cycle regression and doublet scoring/removal are unsupported in this strategy version. Subclustering is a separate scoped-child action from a completed parent. Cell-cycle regression does not mean deleting cycling cells; a doublet score alone does not authorize removal."); assert.equal(h.requests.length, 0);});
  await check("score-first default adds one readonly card and one existing central approval", () => {const h = setup(); assert.equal(h.el("strategy-operations").children.length, 7); assert.equal(descendants(h.doublet("doublet-card")).some(node => ["BUTTON", "INPUT", "SELECT", "TEXTAREA"].includes(node.tagName)), false); assert.match(h.doublet("doublet-method").textContent, /keep.*scores only.*default/); assert.match(h.doublet("doublet-choices").textContent, /keep.*default.*remove_predicted/); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.el("annotation-approve").disabled, true); assert.equal(h.requests.length, 0);});
  await check("cycle and doublet diagnostics share one central strategy without changing cycle controls", () => {const value = answer(), details = value.run.strategy_review.details; details.canonical_proposal.cycle = {method: "none", reason: "Keep proliferation signal"}; details.cycle_diagnostics = {schema: "scagentkit.cycle.evidence.v1", status: "insufficient", reasons: ["Missing phase genes"], columns: ["sc_cycle_S.Score", "sc_cycle_G2M.Score", "sc_cycle_Phase", "sc_cycle_CC.Difference"], reference: "fixed_full_input", refit_after_qc: false}; details.capabilities.cycle = ["none", "full", "difference"]; const h = setup(value); assert.equal(h.el("strategy-operations").children.length, 8); assert.equal(h.doublet("cycle-method").dataset.method, "none"); assert.equal(h.doublet("doublet-method").dataset.method, "keep"); assert.equal(h.doublet("cycle-advanced").open, false); assert.equal(h.el("strategy-approve").disabled, false); assert.doesNotMatch(h.el("strategy-unsupported").textContent, /Doublet scoring\/removal.*unsupported/);});
  await check("missing optional choice keeps cells and never invents removal", () => {const value = answer(); delete value.run.strategy_review.details.canonical_proposal.doublet; const h = setup(value); assert.match(h.doublet("doublet-method").textContent, /keep/); assert.match(h.doublet("doublet-cell-ids").textContent, /None/); assert.equal(h.call("doubletReviewError"), null);});
  await check("prediction limits and capture provenance remain explicit", () => {const h = setup(); assert.match(h.doublet("doublet-risk").textContent, /not a calibrated probability.*algorithm prediction.*not biological truth.*homotypic.*does not authorize deletion/); assert.match(h.doublet("doublet-capture-note").textContent, /physical loading unit.*Donor, condition and batch do not establish a capture/); const record = h.doublet("doublet-record").textContent; for (const text of ["capture_id", "physical loading units", "Analyst documented loading plan", "fixed_full_input", "scDblFinder", "1.26.7", doubletEvidenceHash, selectionHash]) assert(record.includes(text)); assert.equal(h.doublet("doublet-details").open, false); assert.match(h.doublet("doublet-provenance").textContent, /human.*Explicit synthetic called-cell raw-count fixture.*scDblFinder::scDblFinder.*1.26.7/);});
  await check("actual capture summaries and QC/cycle overlaps display saved values without inference", () => {const h = setup(answer(true, "remove_predicted")); assert.match(h.doublet("doublet-capture").textContent, /capture_id.*Declared two physical loading units/); assert.match(h.doublet("doublet-cohort").textContent, /full project input before QC; no refit after QC or deletion.*does not establish a complete capture.*Input: 4.*scored: 4.*predicted doublets: 1.*Unknown: 0.*retained: 2.*choice: 1/); assert.match(h.doublet("doublet-capture-stats").textContent, /loading_A.*1,900.*0.08.*0.16.*1.*0.5.*loading_B/s); assert.match(h.doublet("doublet-capture-impact").textContent, /Predicted excluded by QC.*Removed \/ QC.*Retained \/ input/s); assert.match(h.doublet("doublet-cycle-relation").textContent, /Unknown.*full_input.*4.*post_qc.*3.*proposed_removed.*1/s); assert.equal(h.doublet("doublet-cycle-relation").open, false);});
  await check("complete capture and technology are declared explicitly rather than inferred from project size", () => {for (const flag of [true, false, undefined]) {const value = answer(), evidence = value.run.strategy_review.details.doublet_diagnostics; if (flag === undefined) delete evidence.full_called_cohort; else evidence.full_called_cohort = flag; const h = setup(value); assert(h.doublet("doublet-rate").textContent.includes("Declared full_called_cohort: " + (flag === undefined ? "Unavailable" : String(flag).toUpperCase()))); assert.match(h.doublet("doublet-rate").textContent, /declared_droplet_other.*manual.*not inferred from project size/); assert.match(h.doublet("doublet-cohort").textContent, /full project input.*does not establish a complete capture/);}});
  await check("missing saved values display unavailable instead of zero or inferred capture", () => {const value = answer(), details = value.run.strategy_review.details; delete details.doublet_diagnostics.capture_stats.loading_A.expected_rate; delete details.doublet_diagnostics.capture.source; delete details.applicability.doublet.per_capture.loading_A.retained_fraction_input; details.applicability.doublet.cycle = null; const h = setup(value); assert.match(h.doublet("doublet-capture-stats").textContent, /Unavailable/); assert.match(h.doublet("doublet-capture-impact").textContent, /Unavailable/); assert.match(h.doublet("doublet-capture").textContent, /Source: Unavailable/); assert.match(h.doublet("doublet-cycle-relation").textContent, /no bound cycle diagnostics.*No cycle phase or score is inferred/);});
  await check("approved removal preview displays literal complete exact IDs", () => {const h = setup(answer(true, "remove_predicted")); assert.equal(h.doublet("doublet-scope-status").dataset.status, "verified"); assert.equal(h.doublet("doublet-cell-ids").textContent, "cell-2"); assert.match(h.doublet("doublet-cell-count").textContent, /Exact removal count: 1.*complete.*no ID is truncated/); assert.equal(h.doublet("doublet-cell-scope").open, false); assert.equal(h.doublet("doublet-cell-ids").getAttribute("tabindex"), "0"); assert.equal(h.el("strategy-approve").disabled, false);});
  await check("full long deletion list is preserved without case changes or truncation", () => {const value = answer(true, "remove_predicted"), impact = value.run.strategy_review.details.applicability.doublet, ids = Array.from({length: 2001}, (_, i) => `Literal_MixedCase_Cell_${i}`); impact.qc_keep_cell_ids = ["keep", ...ids]; impact.selected_cell_ids = ["keep"]; impact.removed_cell_ids = ids; impact.qc_retained = ids.length + 1; impact.removed_cells = ids.length; impact.retained_cells = 1; impact.per_capture = {loading_A: {input_cells: ids.length + 1, qc_retained: ids.length + 1, predicted_input: ids.length, predicted_after_qc: ids.length, predicted_qc_excluded: 0, removed: ids.length, retained: 1}}; const h = setup(value); assert.equal(h.doublet("doublet-cell-ids").textContent, ids.join("\n")); assert(h.doublet("doublet-cell-ids").textContent.endsWith(ids.at(-1)));});
  await check("literal cell IDs and provenance are escaped as text without HTML evaluation", () => {const value = answer(true, "remove_predicted"), impact = value.run.strategy_review.details.applicability.doublet; impact.qc_keep_cell_ids[1] = "<img src=x onerror=never()>"; impact.removed_cell_ids[0] = impact.qc_keep_cell_ids[1]; const h = setup(value); assert.match(h.doublet("doublet-cell-ids").textContent, /<img/); assert.equal(descendants(h.doublet("doublet-card")).some(node => ["SCRIPT", "IMG"].includes(node.tagName)), false);});
  await check("unresolved score-first diagnostics retain visible status/reason without silent skip", () => {const h = setup(answer(true, "keep", "unsupported")); assert.equal(h.doublet("doublet-status").dataset.status, "unsupported"); assert.match(h.doublet("doublet-record").textContent, /Rate assumption unresolved/); assert.match(h.doublet("doublet-reasons").textContent, /Rate assumption unresolved/); assert.match(h.doublet("doublet-cell-ids").textContent, /None/);});
  for (const [name, mutate] of [
    ["missing diagnostic schema", details => delete details.doublet_diagnostics.schema],
    ["unavailable scoring", details => details.doublet_diagnostics.status = "unsupported"],
    ["missing evidence binding", details => delete details.doublet_evidence_hash],
    ["mismatched evidence hash", details => details.applicability.doublet.evidence_hash = "0".repeat(64)],
    ["missing selection hash", details => delete details.applicability.doublet.selection_hash],
    ["invalid selection hash", details => details.applicability.doublet.selection_hash = "not-a-hash"],
    ["missing exact scope", details => delete details.applicability.doublet.removed_cell_ids],
    ["duplicate removed IDs", details => details.applicability.doublet.removed_cell_ids.push("cell-2")],
    ["missing literal ID", details => details.applicability.doublet.removed_cell_ids[0] = ""],
    ["nonliteral ID", details => details.applicability.doublet.removed_cell_ids[0] = 2],
    ["selected and removed overlap", details => details.applicability.doublet.selected_cell_ids.push("cell-2")],
    ["uncovered QC cell", details => details.applicability.doublet.selected_cell_ids.pop()],
    ["cell outside QC", details => details.applicability.doublet.removed_cell_ids[0] = "other-input"],
    ["mismatched saved method", details => details.applicability.doublet.method = "keep"],
    ["missing impact count", details => delete details.applicability.doublet.retained_cells],
    ["impact count mismatches exact scope", details => details.applicability.doublet.removed_cells = 0],
    ["missing per-capture impact", details => delete details.applicability.doublet.per_capture],
    ["per-capture deletion exceeds predictions", details => details.applicability.doublet.per_capture.loading_A.predicted_after_qc = 0],
    ["per-capture counts do not sum to exact scope", details => details.applicability.doublet.per_capture.loading_B.retained = 0]
  ]) await check("malformed removal blocks central approval: " + name, async () => {const value = answer(true, "remove_predicted"); mutate(value.run.strategy_review.details); const h = setup(value); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-reject").disabled, false); assert.equal(h.doublet("doublet-scope-status").dataset.status, "unverified"); assert.equal(h.doublet("doublet-cell-ids").textContent, "Unavailable"); assert.match(h.el("strategy-draft-status").textContent, /unverified/); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);});
  await check("keep never accepts a hidden deletion or mismatched method", async () => {for (const mutate of [impact => impact.removed_cell_ids = ["cell-2"], impact => impact.removed_cells = 1, impact => impact.method = "remove_predicted"]) {const value = answer(); mutate(value.run.strategy_review.details.applicability.doublet); const h = setup(value); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.doublet("doublet-cell-ids").textContent, "Unavailable"); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);}});
  await check("new local selection/preprocess stages permit explicit failure retry only", () => {const h = setup(); for (const stage of ["strategy_selection", "strategy_preprocess"]) {assert.equal(h.call("supportedSavedLocalRetry", {stage, status: "failed"}, null), true); assert.equal(h.call("supportedSavedLocalRetry", {stage, status: "ready"}, null), false); assert.equal(h.call("supportedSavedLocalRetry", {stage, status: "ready"}, {status: "running"}), false);}});
  await check("malformed removal scope blocks explicit Continue as well as approval", () => {const value = answer(true, "remove_predicted"); value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = null; delete value.run.strategy_review.details.applicability.doublet.selection_hash; value.continuation = {schema: "scagentkit.run-continue.workbench.v1", enabled: true, job: null, availability: {can_continue: true, can_retry: false, requires_explicit_retry: false, reason: "approved local work", project_id: value.run.project_id, input_hash: value.run.input_hash, expected_revision: value.run.revision}}; const h = setup(value); assert.equal(h.el("run-continue").disabled, true); assert.equal(h.call("canContinue", false), false);});
  await check("single R-auto-unboxed literal cell vectors preserve exact membership", () => {const value = answer(true, "remove_predicted"), impact = value.run.strategy_review.details.applicability.doublet; impact.qc_keep_cell_ids = "one"; impact.selected_cell_ids = []; impact.removed_cell_ids = "one"; impact.qc_retained = 1; impact.removed_cells = 1; impact.retained_cells = 0; impact.per_capture = {loading_A: {input_cells: 1, qc_retained: 1, predicted_input: 1, predicted_after_qc: 1, predicted_qc_excluded: 0, removed: 1, retained: 0}}; const h = setup(value); assert.equal(h.call("doubletReviewError"), null); assert.equal(h.doublet("doublet-cell-ids").textContent, "one");});
  await check("complete JSON editing disables approval until central save", async () => {const h = setup(), p = copy(h.state.view.run.strategy_review.details.canonical_proposal); p.doublet = {method: "remove_predicted", reason: "Inspect exact impact before deletion"}; h.state.strategyDraftText = JSON.stringify(p); h.call("buttons"); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);});
  await check("revision uses existing complete strategy endpoint with no deletion execution", async () => {const h = setup(), p = copy(h.state.view.run.strategy_review.details.canonical_proposal); p.doublet = {method: "remove_predicted", reason: "Reviewed algorithm prediction scope"}; h.state.strategyDraftText = JSON.stringify(p); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Complete plan review";
    h.fetchImpl = async (_, options) => {const request = JSON.parse(options.body), result = answer(true, "remove_predicted"); result.run.revision = 8; result.run.review_node.expected_revision = 8; result.run.strategy_review.details.canonical_proposal = request.proposal; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); const request = JSON.parse(h.requests[0].options.body); assert.equal(h.requests[0].url, "/api/run-review/decision"); assert.equal(request.kind, "strategy"); assert.equal(request.action, "revise"); assert.deepEqual(request.proposal, p); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.doublet("doublet-cell-ids").textContent, "cell-2");});
  await check("one central approval records choice without Continue or scientific computation", async () => {const h = setup(answer(true, "remove_predicted")); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Reviewed full impact"; h.fetchImpl = async () => {const result = answer(true, "remove_predicted"); result.run.status = "ready"; result.run.stage = "strategy_apply"; result.run.review_node = null; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 1); assert.equal(JSON.parse(h.requests[0].options.body).action, "approve"); assert.equal(h.requests.some(request => request.url.includes("continue")), false);});
  await check("stale whole-strategy revision retains exact draft and stops further decisions", async () => {const h = setup(), p = proposal("remove_predicted"); h.state.strategyDraftText = JSON.stringify(p); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Complete review"; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale strategy approval"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.stale, true); assert.equal(h.state.strategyDraftText, JSON.stringify(p)); assert.equal(h.el("strategy-approve").disabled, true);});
  const report = {schema: "scagentkit.doublet.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(test => test.passed).length, failed: results.filter(test => !test.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n"); process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
