"use strict";
// Production-source offline DOM checks. No browser, R, provider or network.
const fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const assert = require("node:assert/strict"), {webcrypto, createHash} = require("node:crypto");
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/review.js"), htmlPath = path.join(repo, "workbench/static/review.html");
const results = [], copy = value => JSON.parse(JSON.stringify(value)), sha = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must use textContent");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui() {
  const source = fs.readFileSync(sourcePath, "utf8"), html = fs.readFileSync(htmlPath, "utf8"), elements = new Map(), storage = new Map(), timers = new Map(); let timer = 0;
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate production HTML ID"); elements.set(match[2], new Element(match[1]));}
  const harness = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm() {return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}},
    setTimeout(callback, delay) {timers.set(++timer, {callback, delay}); return timer;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); assert(harness.fetchImpl, "Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args); harness.el = id => document.getElementById(id);
  harness.mad = id => {const nodes = descendants(harness.el("strategy-operations")); return nodes.find(node => node.getAttribute("id") === id);};
  return harness;
}
const inputHash = "a".repeat(64), proposalHash = "b".repeat(64), reviewHash = "c".repeat(64), strategyEvidenceHash = "d".repeat(64), panelHash = "e".repeat(64), evidenceHash = "f".repeat(64);
const presets = ["keep_all", "conservative_and3", "low_counts3", "low_features3", "high_mt3", "any_quality3"];
function proposal(preset = "keep_all") {return {schema: "scagentkit.strategy.v1", rationale: "Review the finite saved QC panel", risks: [], inferences: [], qc: {schema: "scagentkit.qc.mad.v1", rationale: "Explicit analyst choice", risks: [], preset_id: preset, panel_hash: panelHash}, analysis: {normalization_method: "LogNormalize", scale_factor: 10000}, pcs: {method: "fixed", ndim: 12}, batch: {method: "none"}, clustering: {resolution: 0.5}, umap: {run: true}};}
function panel() {
  const metric = {available: true, exact: {median: 2.567891234567, mad_raw: 0.01, scaled_mad: 0.014826, lower_transformed: 2.523413234567, lower_raw: 332.0000198765}, display: {median: 2.568, lower_raw: 332}, warnings: [], unavailable_reasons: []};
  return {schema: "scagentkit.qc.mad.evidence.v1", panel_hash: panelHash, grouping: {method: "column", column: "qc_pool", declared_role: "sample", source: "Explicit per-sample QC grouping; distinct from capture"}, stage_counts: {original_cells: 5, pre_score_cells: 4, statistics_cells: 4, quality_choice: "pending"}, method: {k: 3, mad_constant: 1.4826, min_group_cells: 30, counts_features_transform: "log10(x+1)", mt_transform: "identity"},
    warnings: ["Small-N warning", "Possible multimodal or majority-low-quality group; no optimal threshold claim"], groups: [{group_id: "group1", value: "sample A", before: 3, pre_score: 3, metrics: {nCount: copy(metric), nFeature: copy(metric), percent_mt: {available: false, exact: null, display: null, warnings: ["MAD zero"], unavailable_reasons: ["MAD0 / near-zero"]}}, diagnostic_metrics: {percent_ribo: {median: 0}, percent_hb: {median: null}, high_rna_flagged: 1}, warnings: ["Small-N warning"]}, {group_id: "group2", value: "sample B", before: 2, pre_score: 1, metrics: {nCount: copy(metric)}, diagnostic_metrics: {percent_ribo: {median: 12}}, warnings: []}],
    presets: presets.map((preset_id, index) => ({preset_id, label: index ? preset_id : "Keep all", rule: preset_id === "conservative_and3" ? "low count AND low feature AND high mt" : preset_id === "any_quality3" ? "low count OR low feature OR high mt" : preset_id, available: preset_id !== "high_mt3", unavailable_reasons: preset_id === "high_mt3" ? ["MAD0 in mitochondrial measurements"] : [], before: 5, pre_score: 4, retained: preset_id === "high_mt3" ? null : index ? 3 : 4, removed: preset_id === "high_mt3" ? null : index ? 1 : 0, fraction_retained: preset_id === "high_mt3" ? null : index ? .75 : 1, groups: [{group_id: "group1", value: "sample A", pre_score: 3, retained: 3, removed: 0, fraction_retained: 1}, {group_id: "group2", value: "sample B", pre_score: 1, retained: preset_id === "high_mt3" ? null : index ? 0 : 1, removed: preset_id === "high_mt3" ? null : index ? 1 : 0, fraction_retained: preset_id === "high_mt3" ? null : index ? 0 : 1}]}))};
}
function answer(enabled = true, preset = "keep_all") {
  const canonical = proposal(preset), details = {canonical_proposal: canonical, background: {facts: {species: "human"}}, quality: {cell_count: 5}, applicability: {executable: true, blockers: []}, capabilities: {}, source: {kind: "manual"}};
  if (enabled) {details.mad_panel = panel(); details.qc_mad = {panel_hash: panelHash, evidence_hash: evidenceHash, choice: copy(canonical.qc), impact: {retained: preset === "keep_all" ? 4 : 3}}; details.qc_impact = {keep_cells: preset === "keep_all" ? ["a", "b", "c", "d"] : ["a", "b", "c"], remove_cells: preset === "keep_all" ? ["prefilter"] : ["prefilter", "d"], keep_cell_hash: "1".repeat(64), remove_cell_hash: "2".repeat(64)};}
  else canonical.qc = {method: "none"};
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "offline-token", run: {schema: "scagentkit.run.v1", project_id: "offline-mad", input_hash: inputHash, revision: 7, status: "awaiting_review", stage: "strategy_propose", context: {species: "human"}, review_node: {kind: "strategy", project_id: "offline-mad", input_hash: inputHash, expected_revision: 7, proposal_hash: proposalHash, review_hash: reviewHash, evidence_hash: strategyEvidenceHash, can_decide: true, can_revise: true, can_undo: false}, strategy_review: {schema: "scagentkit.strategy.review.v1", hash: reviewHash, input_hash: inputHash, evidence_hash: strategyEvidenceHash, details}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.state.continuation = value.continuation || null; h.call("render"); return h;}
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("legacy range UI retains six original operation cards", () => {const h = setup(answer(false)); assert.equal(h.el("strategy-operations").children.length, 6); assert.equal(h.mad("mad-card"), undefined); assert.equal(h.call("madReviewError"), null); assert.equal(h.requests.length, 0);});
  await check("optional MAD panel adds one concentrated review with default keep_all", () => {const h = setup(); assert.equal(h.el("strategy-operations").children.length, 7); assert.equal(h.mad("mad-choice").dataset.preset, "keep_all"); assert.match(h.mad("mad-choice").textContent, /default/); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(descendants(h.mad("mad-card")).filter(node => node.tagName === "SELECT").length, 1); assert.equal(descendants(h.mad("mad-card")).filter(node => node.tagName === "BUTTON").length, 0);});
  await check("QC group role differs from capture with no donor inference", () => {const h = setup(); assert.match(h.mad("mad-grouping").textContent, /qc_pool.*sample.*Capture\/loading unit: Unknown.*distinct declarations.*no relationship is inferred/);});
  await check("MAD formula and original-scale mitochondrial tail are explicit", () => {const h = setup(); assert.match(h.mad("mad-method").textContent, /log10\(x\+1\).*3.*1.4826.*upper tail.*original scale.*exact thresholds.*rounded display.*never control execution/);});
  await check("high RNA ribosomal and haemoglobin values only diagnose", () => {const h = setup(); assert.match(h.mad("mad-risk").textContent, /High RNA is flagged only.*Ribosomal and haemoglobin.*diagnostic only.*none authorizes automatic deletion/);});
  await check("MAD0 small groups nonfinite and unknown are disclosed", () => {const h = setup(); assert.match(h.mad("mad-risk").textContent, /MAD zero\/near zero.*small groups.*missing\/nonfinite.*Unknown.*distinct.*zero/); assert.match(h.mad("mad-warnings").textContent, /Small-N.*multimodal.*majority-low-quality/);});
  await check("source prefilter prescore quality and postdoublet counts have distinct labels", () => {const h = setup(); assert.match(h.mad("mad-stage-counts").textContent, /Original: 5; minimal prefilter: 4; pre-score: 4; post-QC: 4; post-doublet: Unavailable.*statistics cells: 4/);});
  await check("saved explicit stage lineage overrides panel when supplied", () => {const value = answer(); value.run.strategy_review.details.qc_stage_counts = {original_cells: 6, prefilter_cells: 5, pre_score_cells: 4}; const h = setup(value); assert.match(h.mad("mad-stage-counts").textContent, /Original: 6; minimal prefilter: 5; pre-score: 4/);});
  await check("missing rate source is Unknown rather than inferred from retained size", () => {const h = setup(); assert.match(h.mad("mad-rate-source").textContent, /method: Unknown; source: Unknown; score reference: Unknown.*separate.*retained count/);});
  await check("declared capture and original rate lineage render without reassignment", () => {const value = answer(); value.run.strategy_review.details.doublet_diagnostics = {schema: "scagentkit.doublet.evidence.v1", capture: {method: "column", column: "loading_id"}, rate: {method: "manual", source: "Original loading plan"}, reference: "fixed_full_input"}; const h = setup(value); assert.match(h.mad("mad-grouping").textContent, /qc_pool.*loading_id/); assert.match(h.mad("mad-rate-source").textContent, /manual.*Original loading plan.*fixed_full_input/);});
  await check("explicit prefilter threshold source and legacy policy separation remain visible", () => {const value = answer(); value.run.strategy_review.details.prefilter = {options: {method: "min_counts", min_counts: 200, source: "Explicit called-cell scoring prerequisite"}}; value.run.strategy_review.details.doublet_diagnostics = {schema: "scagentkit.doublet.evidence.v1", reference: "fixed_full_input", refit_after_qc: false}; const h = setup(value); assert.match(h.mad("mad-prefilter").textContent, /raw total counts >= 200.*inclusive.*preapproved.*Explicit called-cell.*Later quality filtering.*capture scores.*does not silently alter legacy range rules/); assert.match(h.mad("doublet-cohort").textContent, /explicit pre-score cohort.*minimal prefilter.*before quality filtering.*Original full-called capture size.*rate reference/);});
  await check("all six finite alternatives distinguish AND from OR", () => {const h = setup(); for (const name of presets) assert(h.mad("mad-candidates").textContent.includes(name)); assert.match(h.mad("mad-candidates").textContent, /low count AND low feature AND high mt/); assert.match(h.mad("mad-candidates").textContent, /low count OR low feature OR high mt/); assert.equal(h.mad("mad-preset-select").children.length, 6);});
  await check("unavailable candidates stay visible with reasons and disabled option", () => {const h = setup(); assert.equal(h.mad("mad-preset-select").children.find(option => option.getAttribute("value") === "high_mt3").disabled, true); assert.match(h.mad("mad-candidates").textContent, /MAD0 in mitochondrial measurements/);});
  await check("every group exact thresholds and rounded displays remain separated", () => {const h = setup(); assert.equal(h.mad("mad-groups").open, false); assert.match(h.mad("mad-groups").textContent, /sample A.*Exact thresholds used by R.*332.0000198765.*Rounded display only.*332.*sample B/s);});
  await check("observed all-deleted group zero and unavailable group remain distinct", () => {const h = setup(); const groups = descendants(h.mad("mad-groups")).filter(node => node.getAttribute("data-qc-group") === "group2"); assert.equal(groups.length, 1); assert.match(groups[0].textContent, /conservative_and31010.*high_mt31UnavailableUnavailableUnavailable/s);});
  await check("literal group and source strings are escaped text", () => {const value = answer(); value.run.strategy_review.details.mad_panel.groups[0].value = "<img src=x onerror=never()>"; const h = setup(value); assert.match(h.mad("mad-groups").textContent, /<img src=x/); assert.equal(descendants(h.mad("mad-card")).some(node => ["SCRIPT", "IMG"].includes(node.tagName)), false);});
  await check("source selection fingerprints stay inspectable locally", () => {const h = setup(); assert.equal(h.mad("mad-details").open, false); for (const value of [panelHash, evidenceHash, "qc_pool", "log10(x+1)"]) assert(h.mad("mad-record").textContent.includes(value)); assert.equal(h.mad("mad-binding").dataset.status, "verified");});
  await check("complete exact quality scope exposes prefilter and approved quality removals", () => {const h = setup(answer(true, "conservative_and3")); assert.equal(h.mad("mad-cell-scope").open, false); assert.equal(h.mad("mad-keep-ids").textContent, "a\nb\nc"); assert.equal(h.mad("mad-remove-ids").textContent, "prefilter\nd"); assert.match(h.mad("mad-cell-count").textContent, /Retained: 3.*removed from original input: 2.*prefilter.*without truncation/); assert.equal(h.mad("mad-keep-ids").getAttribute("tabindex"), "0");});
  await check("no biological-optimum claim or automatic preset change", () => {const h = setup(); assert.match(h.mad("mad-review-note").textContent, /No preset is universally best.*not biological truth/); assert.equal(h.state.view.run.strategy_review.details.canonical_proposal.qc.preset_id, "keep_all"); assert.equal(h.requests.length, 0);});
  for (const [name, mutate] of [
    ["missing panel", details => delete details.mad_panel], ["wrong panel schema", details => details.mad_panel.schema = "arbitrary"],
    ["missing evidence hash", details => delete details.qc_mad.evidence_hash], ["mismatched panel hash", details => details.qc_mad.panel_hash = "0".repeat(64)],
    ["changed panel fingerprint", details => details.mad_panel.panel_hash = "0".repeat(64)], ["invalid proposal panel hash", details => details.canonical_proposal.qc.panel_hash = "bad"],
    ["unsupported preset", details => details.canonical_proposal.qc.preset_id = "arbitrary_threshold"], ["unavailable preset", details => details.canonical_proposal.qc.preset_id = "high_mt3"],
    ["duplicate candidates", details => details.mad_panel.presets.push(copy(details.mad_panel.presets[0]))], ["hallucinated candidate", details => details.mad_panel.presets[0].preset_id = "custom_R"],
    ["missing saved choice", details => delete details.qc_mad.choice], ["saved impact refers to other preset", details => details.qc_mad.choice.preset_id = "conservative_and3"],
    ["missing exact quality scope", details => delete details.qc_impact.keep_cells], ["duplicate exact cells", details => details.qc_impact.remove_cells.push("prefilter")],
    ["overlapping exact scopes", details => details.qc_impact.remove_cells = ["a"]], ["wrong candidate count", details => details.mad_panel.presets[0].retained = 3],
    ["missing exact scope fingerprint", details => delete details.qc_impact.keep_cell_hash], ["global all cells removed", details => details.mad_panel.presets[0].all_cells_removed = true]
  ]) await check("invalid MAD binding blocks approval: " + name, async () => {const value = answer(); mutate(value.run.strategy_review.details); const h = setup(value); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.mad("mad-binding").dataset.status, "unverified"); assert.match(h.el("strategy-draft-status").textContent, /unverified/); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);});
  await check("selection edits only complete draft with no request or cell mutation", () => {const h = setup(), original = copy(h.state.view.run); h.call("chooseMadPreset", "conservative_and3"); const draft = JSON.parse(h.el("strategy-json").value); assert.equal(draft.qc.preset_id, "conservative_and3"); assert.equal(draft.qc.panel_hash, panelHash); assert.deepEqual(Object.keys(draft.qc).sort(), ["schema", "rationale", "risks", "preset_id", "panel_hash"].sort()); assert.deepEqual(copy(h.state.view.run), original); assert.equal(h.requests.length, 0); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.el("strategy-save").disabled, false);});
  await check("unsupported and unavailable selections leave draft unchanged", () => {const h = setup(), original = h.state.strategyDraftText; for (const preset of ["high_mt3", "invented"]) h.call("chooseMadPreset", preset); assert.equal(h.state.strategyDraftText, original); assert.equal(h.requests.length, 0);});
  await check("one central save sends complete typed plan and rebuilds bound impact", async () => {const h = setup(); h.call("chooseMadPreset", "conservative_and3"); const draft = JSON.parse(h.state.strategyDraftText); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Concentrated whole-panel review"; h.fetchImpl = async (_, options) => {const request = JSON.parse(options.body), result = answer(true, "conservative_and3"); result.run.revision = 8; result.run.review_node.expected_revision = 8; result.run.strategy_review.details.canonical_proposal = request.proposal; result.run.strategy_review.details.qc_mad.choice = copy(request.proposal.qc); return {ok: true, json: async () => result};}; await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); const request = JSON.parse(h.requests[0].options.body); assert.equal(h.requests[0].url, "/api/run-review/decision"); assert.equal(request.action, "revise"); assert.equal(request.kind, "strategy"); assert.deepEqual(request.proposal, draft); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.mad("mad-choice").dataset.preset, "conservative_and3");});
  await check("one whole-plan approval does not execute scientific continuation", async () => {const h = setup(answer(true, "conservative_and3")); h.el("strategy-reviewer").value = "Analyst"; h.el("strategy-reason").value = "Accept exact candidate impact"; h.fetchImpl = async () => {const result = answer(true, "conservative_and3"); result.run.status = "ready"; result.run.stage = "strategy_apply"; result.run.review_node = null; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 1); assert.equal(JSON.parse(h.requests[0].options.body).action, "approve"); assert.equal(h.requests.some(item => item.url.includes("continue")), false);});
  await check("stale revision preserves unsaved draft and blocks new decisions", async () => {const h = setup(); h.call("chooseMadPreset", "conservative_and3"); const draft = h.state.strategyDraftText; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale MAD proposal"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.stale, true); assert.equal(h.state.strategyDraftText, draft); assert.equal(h.el("strategy-approve").disabled, true);});
  await check("unverified MAD scope also blocks Continue at ready boundary", () => {const value = answer(); value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = null; delete value.run.strategy_review.details.qc_mad.evidence_hash; value.continuation = {schema: "scagentkit.run-continue.workbench.v1", enabled: true, job: null, availability: {can_continue: true, can_retry: false, requires_explicit_retry: false, reason: "approved local work", project_id: value.run.project_id, input_hash: value.run.input_hash, expected_revision: value.run.revision}}; const h = setup(value); assert.equal(h.el("run-continue").disabled, true); assert.equal(h.call("canContinue", false), false);});
  await check("minimal prefilter retry is explicit and cannot replay an active task", () => {const h = setup(); assert.equal(h.call("supportedSavedLocalRetry", {stage: "prefilter", status: "failed"}, null), true); assert.equal(h.call("supportedSavedLocalRetry", {stage: "prefilter", status: "ready"}, null), false); assert.equal(h.call("supportedSavedLocalRetry", {stage: "prefilter", status: "failed"}, {status: "running"}), false);});
  await check("complete run makes preset selection readonly", () => {const value = answer(); value.run.status = "complete"; value.run.stage = "complete"; value.run.review_node = null; const h = setup(value); assert.equal(h.mad("mad-preset-select").disabled, true); const before = h.state.strategyDraftText; h.call("chooseMadPreset", "conservative_and3"); assert.equal(h.state.strategyDraftText, before);});
  const report = {schema: "scagentkit.mad.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(test => test.passed).length, failed: results.filter(test => !test.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n"); process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
