"use strict";
// Actual production-source offline DOM tests; no browser, R, provider or network.
const fs = require("node:fs"), path = require("node:path"), vm = require("node:vm");
const assert = require("node:assert/strict"), {webcrypto, createHash} = require("node:crypto");
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/review.js"), htmlPath = path.join(repo, "workbench/static/review.html");
const results = [];
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must not access innerHTML");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
function copy(value) {return JSON.parse(JSON.stringify(value));}
function descendants(element) {return element.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);}
function sha(file) {return createHash("sha256").update(fs.readFileSync(file)).digest("hex");}
function ui() {
  const source = fs.readFileSync(sourcePath, "utf8"), html = fs.readFileSync(htmlPath, "utf8"), elements = new Map();
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate HTML ID"); elements.set(match[2], new Element(match[1]));}
  const timers = new Map(), storage = new Map(); let sequence = 0;
  const harness = {elements, timers, requests: [], fetchImpl: null, confirmations: []};
  const document = {body: {dataset: {}}, getElementById(id) {assert.ok(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm(value) {harness.confirmations.push(value); return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}},
    setTimeout(callback, delay) {const id = ++sequence; timers.set(id, {callback, delay}); return id;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); if (!harness.fetchImpl) throw new Error("Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  // Only the final initial HTTP load is omitted. Production functions are intact.
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args);
  harness.el = id => document.getElementById(id); return harness;
}
const inputHash = "a".repeat(64), proposalHash = "b".repeat(64), reviewHash = "c".repeat(64), evidenceHash = "d".repeat(64);
function proposal() {
  return {schema: "scagentkit.strategy.v1", rationale: "Use measured public quality and an explicit analyst plan.", risks: ["Clustering does not validate cell identity"], inferences: [{claim: "The contrast may be biological", uncertainty: "unverified design"}],
    qc: {method: "thresholds", rules: [{metric: "nFeature_RNA", min: 200}]}, analysis: {normalization_method: "LogNormalize", scale_factor: 10000, nfeatures: 2000, npcs: 30, seed: 42},
    pcs: {method: "fixed", ndim: 20}, batch: {method: "none", reason: "No verified batch contrast"}, clustering: {resolution: 0.5, diagnostic_resolutions: [0.3, 0.5]}, umap: {run: true, n_neighbors: 30}};
}
function answer() {
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "offline-session-token", run: {schema: "scagentkit.run.v1", project_id: "offline-strategy", input_hash: inputHash, revision: 7, status: "awaiting_review", stage: "strategy_propose", context: {species: "human", tissue: "Blood"},
    review_node: {kind: "strategy", project_id: "offline-strategy", input_hash: inputHash, expected_revision: 7, proposal_hash: proposalHash, review_hash: reviewHash, evidence_hash: evidenceHash, can_decide: true, can_revise: true, can_undo: false},
    strategy_review: {schema: "scagentkit.strategy.review.v1", hash: reviewHash, input_hash: inputHash, evidence_hash: evidenceHash, details: {canonical_proposal: proposal(), background: {facts: {species: "human", tissue: "Blood", group_column: "condition", group_values: ["Ca", "Ctrl"]}, missing: ["batch assignment", "donor identity"]}, quality: {cell_count: 96, actual_source: "saved measured QC summary"}, qc_impact: {expected_retained_cells: 90, input_cell_count: 96}, applicability: {executable: true, blockers: [], details: [{operation: "batch", method: "none", applicable: true}]}, capabilities: {pc_selection: ["fixed", "computed_variance"], batch: ["none", "manual"], cycle: "unsupported", doublet: "unsupported", subcluster: "unsupported"}, execution_plan: ["qc_apply", "strategy_basis", "strategy_neighbors", "strategy_cluster", "markers", "annotation_review"], dependency_hashes: {input: inputHash}, source: {kind: "mock_provider", new_request: false}, limitations: ["Synthetic transport fixture, not scientific validation"]}}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.state.continuation = value.continuation || null; h.call("render"); return h;}
function validReady(value) {value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = null; return value;}
function continuation(run, job = null, canRetry = false) {return {schema: "scagentkit.run-continue.workbench.v1", enabled: true, job, availability: {project_id: run.project_id, input_hash: run.input_hash, expected_revision: run.revision, can_continue: !canRetry && run.status === "ready", can_retry: canRetry, requires_explicit_retry: canRetry, reason: canRetry ? "explicit_retry_required" : "ready"}};}
async function check(name, fn) {try {await fn(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("verified central strategy snapshot renders without calculation", () => {const h = setup(); assert.equal(h.el("run-strategy").hidden, false); assert.equal(h.el("run-qc").hidden, true); assert.equal(h.el("run-annotation").hidden, true); assert.equal(h.requests.length, 0); assert.match(h.el("run-progress").textContent, /Analysis strategy review/);});
  await check("user facts missing background and model inferences remain separate", () => {const h = setup(); const cards = h.el("strategy-background").children; assert.equal(cards.length, 3); assert.match(cards[0].textContent, /User-provided facts.*condition.*Ca.*Ctrl/s); assert.doesNotMatch(cards[0].textContent, /unverified design/); assert.match(cards[1].textContent, /Missing background.*batch assignment/s); assert.match(cards[2].textContent, /Model \/ proposal inferences.*unverified design/s);});
  await check("all six saved operation sections are readonly observations", () => {const h = setup(); const cards = h.el("strategy-operations").children; assert.equal(cards.length, 6); assert.match(cards.map(value => value.textContent).join(" "), /QC and cell retention.*LogNormalize.*PC selection.*ndim.*Batch handling.*Clustering and resolution.*UMAP/s); assert.match(h.el("strategy-unsupported").textContent, /regression does not mean deleting cycling cells/); assert.match(h.el("strategy-unsupported").textContent, /doublet score alone does not authorize removal/);});
  await check("quality QC impact and execution evidence use saved values", () => {const h = setup(); assert.match(h.el("strategy-quality").textContent, /96.*saved measured QC/s); assert.match(h.el("strategy-qc-impact").textContent, /90.*96/s); assert.match(h.el("strategy-capabilities").textContent, /computed_variance.*unsupported.*strategy_neighbors/s);});
  await check("detailed record and evidence start collapsed", () => {const h = setup(); assert.equal(descendants(h.el("run-strategy")).filter(value => value.tagName === "DETAILS").some(value => value.open), false); assert.match(h.el("strategy-record").textContent, /scagentkit.strategy.review.v1/);});
  await check("rendered user strings are text rather than executable HTML", () => {const value = answer(); value.run.strategy_review.details.canonical_proposal.rationale = "<img src=x onerror=alert(1)>"; value.run.strategy_review.details.background.facts.note = "<script>never()</script>"; const h = setup(value); assert.match(h.el("strategy-rationale").textContent, /<img/); assert.match(h.el("strategy-background").textContent, /<script>/); assert.equal(descendants(h.el("run-strategy")).some(value => value.tagName === "SCRIPT" || value.tagName === "IMG"), false);});
  await check("saved whole strategy has one enabled approval and reject", () => {const h = setup(); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.el("strategy-reject").disabled, false); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("run-undo-button").disabled, true); assert.equal(h.el("annotation-approve").disabled, true);});
  await check("local blocker disables approval through authoritative node permission", () => {const value = answer(); value.run.review_node.can_decide = false; value.run.strategy_review.details.applicability = {executable: false, blockers: [{code: "group_batch_confounded", message: "Biological condition is completely confounded with batch"}], details: {batch: "manual"}}; const h = setup(value); assert.match(h.el("strategy-applicability").textContent, /blocked/); assert.match(h.el("strategy-blockers").textContent, /group_batch_confounded/); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.el("strategy-json").disabled, false);});
  await check("manual batch approval records a pending plan and discloses the enforced stop", () => {const value = answer(); value.run.strategy_review.details.canonical_proposal.batch = {method: "manual", reason: "Integration needs verified design and an independently prepared object"}; value.run.strategy_review.details.applicability = {executable: false, blockers: [{code: "manual_batch_required"}], details: {batch: "manual"}}; const h = setup(value); assert.equal(h.el("strategy-approve").disabled, false); assert.match(h.el("strategy-execution-note").textContent, /remains pending.*stops for configuration before QC and analysis.*No integration is executed/s);});
  await check("processed explicit reuse renders null operations without inventing execution", () => {const value = answer(), p = value.run.strategy_review.details.canonical_proposal; for (const key of ["qc", "analysis", "pcs", "clustering", "umap"]) p[key] = null; value.run.strategy_review.details.qc_impact = null; value.run.strategy_review.details.execution_plan = ["reuse_saved_processed_analysis", "markers", "annotation_review"]; const h = setup(value); assert.match(h.el("strategy-operations").textContent, /Reuse is explicit/); assert.match(h.el("strategy-capabilities").textContent, /reuse_saved_processed_analysis/);});
  await check("optional evidence shape absence renders disclosed missing information", () => {const value = answer(); for (const key of ["background", "quality", "qc_impact", "capabilities", "execution_plan", "limitations", "applicability"]) delete value.run.strategy_review.details[key]; const h = setup(value); assert.match(h.el("strategy-applicability").textContent, /not been recorded/); assert.match(h.el("strategy-background").textContent, /No structured user facts/);});
  for (const [label, mutate] of [["review hash", v => v.run.strategy_review.hash = "e".repeat(64)], ["input hash", v => v.run.strategy_review.input_hash = "e".repeat(64)], ["record schema", v => v.run.strategy_review.schema = "scagentkit.annotation.review.v1"], ["node revision", v => v.run.review_node.expected_revision += 1], ["evidence mismatch", v => v.run.strategy_review.evidence_hash = "e".repeat(64)], ["missing evidence", v => delete v.run.strategy_review.evidence_hash], ["typed schema", v => v.run.strategy_review.details.canonical_proposal.schema = "arbitrary-r"], ["missing record", v => delete v.run.strategy_review]]) {
    await check(`strategy ${label} mismatch is rejected before display`, () => {const h = ui(), value = answer(); mutate(value); assert.throws(() => h.call("verify", value));});
  }
  await check("changed project or input cannot replace active saved view", () => {const h = setup(); const value = answer(); value.run.project_id = "other-project"; assert.throws(() => h.call("verify", value), /project or input changed/);});
  await check("JSON whitespace does not invalidate an otherwise unchanged draft", () => {const h = setup(); h.state.strategyDraftText = JSON.stringify(proposal()); h.call("buttons"); assert.equal(h.call("strategyDirty"), false); assert.equal(h.el("strategy-approve").disabled, false);});
  await check("invalid JSON disables saving and approval without evaluating text", async () => {const h = setup(); h.state.strategyDraftText = "({schema:'scagentkit.strategy.v1',code:never()})"; h.call("buttons"); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 0); assert.match(h.el("run-message").textContent, /valid JSON/);});
  await check("nonobject JSON and unsupported schema cannot be saved", () => {const h = setup(); for (const value of ["null", "[]", '"literal R"', JSON.stringify({schema: "not-supported"})]) {h.state.strategyDraftText = value; assert.ok(h.call("strategyDraftError")); h.call("buttons"); assert.equal(h.el("strategy-save").disabled, true);}});
  await check("complete revision disables approval until rebuilt review is inspected", async () => {const h = setup(), value = proposal(); value.clustering.resolution = 0.7; h.state.strategyDraftText = JSON.stringify(value); h.call("buttons"); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0); assert.match(h.el("run-message").textContent, /Save the complete strategy/);});
  await check("whole revision IPC contains typed JSON and exact snapshot only", async () => {const h = setup(), value = proposal(); value.clustering.resolution = 0.7; value.rationale = "source('never') $(never) <script>literal</script>"; h.state.strategyDraftText = JSON.stringify(value); h.el("strategy-reviewer").value = " Analyst "; h.el("strategy-reason").value = " One reason "; h.fetchImpl = async (_, options) => {const payload = JSON.parse(options.body), result = answer(); result.run.revision = 8; result.run.review_node.expected_revision = 8; result.run.strategy_review.details.canonical_proposal = payload.proposal; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); const payload = JSON.parse(h.requests[0].options.body); assert.deepEqual(Object.keys(payload).sort(), ["action", "kind", "project_id", "input_hash", "proposal_hash", "review_hash", "expected_revision", "reviewer", "reason", "proposal"].sort()); assert.equal(payload.kind, "strategy"); assert.equal(payload.action, "revise"); assert.deepEqual(payload.proposal, value); assert.equal(payload.reviewer, "Analyst"); assert.equal(payload.expected_revision, 7); assert.equal(h.state.view.run.revision, 8); assert.equal(h.call("strategyDirty"), false); assert.equal(h.el("strategy-approve").disabled, false);});
  await check("approval saves one decision and never starts continuation or provider", async () => {const h = setup(); h.el("strategy-reviewer").value = "analyst"; h.el("strategy-reason").value = "reviewed all operations"; h.fetchImpl = async () => ({ok: true, json: async () => validReady(answer())}); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 1); assert.equal(h.requests[0].url, "/api/run-review/decision"); assert.equal(JSON.parse(h.requests[0].options.body).action, "approve"); assert.equal("proposal" in JSON.parse(h.requests[0].options.body), false); assert.match(h.el("run-message").textContent, /Execute approved local work separately/); assert.equal(h.state.view.run.status, "ready");});
  await check("whole reject preserves record and does not run calculation", async () => {const h = setup(); h.el("strategy-reviewer").value = "analyst"; h.el("strategy-reason").value = "design requires clarification"; h.fetchImpl = async () => {const result = answer(); result.run.status = "rejected"; result.run.review_node.can_decide = false; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "reject"); assert.equal(h.requests.length, 1); assert.equal(h.state.view.run.status, "rejected"); assert.match(h.el("run-message").textContent, /earlier decisions remain recorded/);});
  await check("strategy preview undo and model actions have no UI dispatch", async () => {const h = setup(); for (const action of ["preview", "undo", "chat", "execute"]) await h.call("decideStrategy", action); assert.equal(h.requests.length, 0);});
  await check("failed or stale revision preserves unsaved text and blocks further decisions", async () => {const h = setup(), value = proposal(); value.clustering.resolution = 0.7; h.state.strategyDraftText = JSON.stringify(value); h.el("strategy-reviewer").value = "analyst"; h.el("strategy-reason").value = "revision"; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale strategy approval"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.stale, true); assert.equal(h.state.strategyDraftText, JSON.stringify(value)); assert.equal(h.el("strategy-save").disabled, true); await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1);});
  await check("active local computation prevents strategy edits or decisions", async () => {const value = answer(), h = setup(value); h.state.continuation = {enabled: true, job: {status: "running"}}; h.call("buttons"); assert.equal(h.el("strategy-json").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0);});
  await check("unsaved complete strategy prevents separate local Continue", () => {const value = validReady(answer()); value.continuation = continuation(value.run); const h = setup(value); assert.equal(h.call("canContinue", false), true); const p = proposal(); p.clustering.resolution = 0.7; h.state.strategyDraftText = JSON.stringify(p); h.call("buttons"); assert.equal(h.call("canContinue", false), false); assert.equal(h.el("run-continue").disabled, true);});
  await check("every new local stage supports only explicit saved failure retry", () => {const h = ui(); for (const stage of ["strategy_evidence", "strategy_apply", "strategy_basis", "strategy_neighbors", "strategy_cluster"]) {assert.equal(h.call("supportedSavedLocalRetry", {status: "failed", stage}, null), true); assert.equal(h.call("supportedSavedLocalRetry", {status: "running", stage}, null), true); assert.equal(h.call("supportedSavedLocalRetry", {status: "awaiting_review", stage}, null), false);} assert.equal(h.call("supportedSavedLocalRetry", {status: "failed", stage: "strategy_propose"}, null), false);});
  await check("strategy retry stages retain provider-free task wording", () => {const value = validReady(answer()); value.run.status = "failed"; value.run.stage = "strategy_neighbors"; value.continuation = continuation(value.run, null, true); const h = setup(value); assert.equal(h.el("run-continue-retry").disabled, false); assert.match(h.el("run-continuation-note").textContent, /makes no model request/);});
  await check("legacy QC review still uses the QC iframe and schema", () => {const value = answer(); delete value.run.strategy_review; value.run.stage = "qc_propose"; value.run.review_node.kind = "qc"; delete value.run.review_node.evidence_hash; value.run.qc_preview = {schema: "scagentkit.qc.review.v1", hash: reviewHash, input_hash: inputHash}; const h = setup(value); assert.equal(h.el("run-qc").hidden, false); assert.equal(h.el("run-strategy").hidden, true); assert.equal(h.el("run-qc-frame").getAttribute("src"), "/review-qc");});
  const report = {schema: "scagentkit.strategy.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0,
    sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(result => result.passed).length, failed: results.filter(result => !result.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n");
  process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
