#!/usr/bin/env node
// Production-source DOM contracts with explicitly synthetic saved records.
// No browser, R, project, provider or network is used by this focused test.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import assert from "node:assert/strict";
import {webcrypto, createHash} from "node:crypto";
import {fileURLToPath} from "node:url";
const file = fileURLToPath(import.meta.url), root = path.resolve(path.dirname(file), "..");
const source = fs.readFileSync(path.join(root, "static/review.js"), "utf8"), html = fs.readFileSync(path.join(root, "static/review.html"), "utf8"), css = fs.readFileSync(path.join(root, "static/review.css"), "utf8");
const copy = value => JSON.parse(JSON.stringify(value)), results = [], H = letter => letter.repeat(64);
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  set innerHTML(_) {throw new Error("Evidence cannot be HTML source");}
  append(...items) {this.children.push(...items);}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui() {
  const elements = new Map(), storage = new Map();
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert(!elements.has(match[2])); elements.set(match[2], new Element(match[1]));}
  const h = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), "Missing production HTML ID " + id); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const context = vm.createContext({document, window: {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm() {return false;}}, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}}, setTimeout() {return 1;}, clearTimeout() {},
    async fetch(url, options) {h.requests.push({url, options}); assert(h.fetchImpl, "Offline test forbids real network"); return h.fetchImpl(url, options);}});
  assert.match(source, /\nload\(\);\s*$/); vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context);
  h.state = vm.runInContext("state", context); h.call = (name, ...args) => vm.runInContext(name, context)(...args); h.el = id => document.getElementById(id);
  h.control = id => [...elements.values()].flatMap(node => [node, ...descendants(node)]).find(node => node.getAttribute("id") === id);
  h.event = (element, event) => {for (const callback of element.listeners[event] || []) callback();};
  return h;
}
const range = (metric = "nFeature", min = 200, max = null, group = null) => ({op: "range", metric, min, max, group});
function qc(combined = false) {return combined ? {schema: "scagentkit.qc.rules.v1", rationale: "Synthetic contract fixture; no biological claim", risks: [], remove_if: "any", rules: [range(), range("percent_mt", null, 15)]} : {schema: "scagentkit.qc.v1", rationale: "Synthetic fixed-range contract fixture", risks: [], filters: [range()]};}
function proposal(combined = false) {return {schema: "scagentkit.strategy.v1", rationale: "Synthetic whole-plan contract fixture", risks: [], inferences: [], qc: qc(combined), analysis: {normalization_method: "LogNormalize", scale_factor: 10000, nfeatures: 2000, npcs: 30, seed: 17}, pcs: {method: "fixed", ndim: 10}, batch: {method: "none", reason: "No technical correction authorized"}, clustering: {resolution: .5, diagnostic_resolutions: null}, umap: {run: true, n_neighbors: 15}};}
function panel() {return {schema: "scagentkit.qc.mad.evidence.v1", panel_hash: H("e"), stage_counts: {original_cells: 100, pre_score_cells: 90}, groups: [], presets: ["keep_all", "conservative_and3", "low_counts3", "low_features3", "high_mt3", "any_quality3"].map((preset_id, index) => ({preset_id, label: preset_id, available: index !== 5, all_cells_removed: false, before: 100, retained: 90, removed: 10, pre_score: 90, unavailable_reasons: index === 5 ? ["Synthetic unavailable candidate"] : []}))};}
function preview(q, retained = 40) {
  const rules = q.rules || q.filters || [{op: "mad_preset", preset_id: q.preset_id, panel_hash: q.panel_hash}], ids = rules.map((_, index) => "rule" + (index + 1));
  return {schema: "scagentkit.qc.preview.v1", evidence_hash: H("d"), canonical_parameters: {proposal: copy(q)}, retention: {before: 100, retained, removed: 100 - retained, groups: [{selector: {sample: "S1", capture: "C1"}, before: 50, retained: retained / 2, removed: 50 - retained / 2, fraction_retained: retained / 100}, {selector: {sample: "S2", capture: "C2"}, before: 50, retained: retained / 2, removed: 50 - retained / 2, fraction_retained: retained / 100}]},
    keep_cells: Array.from({length: retained}, (_, i) => "synthetic-cell-" + i), remove_cells: Array.from({length: 100 - retained}, (_, i) => "synthetic-cell-" + (i + retained)), keep_cell_hash: H("a"), remove_cell_hash: H("b"),
    rule_logic: {schema: "scagentkit.qc.rule-logic.v1", remove_if: q.remove_if || "any", rule_ids: ids, prefilter_applied: true, prefilter_removed: 10, quality_removed: 90 - retained, final_retained: retained},
    filter_impacts: rules.map((filter, index) => ({id: ids[index], filter, scoped: 90, independently_removed: index ? 30 : 40, exclusively_removed: q.remove_if === "all" ? 0 : index ? 10 : 20, unavailable: index ? 5 : 0})),
    overlap: {filter_ids: ids, counts: ids.map((_, i) => ids.map((_, j) => i === j ? i ? 30 : 40 : 20))},
    patterns: [{filter_ids: ids, unavailable_filter_ids: [], prefilter_excluded: false, count: 20, retained: q.remove_if === "all" ? 0 : 0, removed: 20}, {filter_ids: [], unavailable_filter_ids: [], prefilter_excluded: true, count: 10, retained: 0, removed: 10}]};
}
function answer(combined = false) {
  const p = proposal(combined), details = {canonical_proposal: p, background: {facts: {species: "human", columns: {sample: "sample_id", capture: "loading_unit", condition: "Ca_Ctrl"}, design: {technical_batch: false}}, missing: []}, quality: {cell_count: 100}, qc_impact: preview(p.qc), qc_stage_counts: {original_cells: 100, pre_score_cells: 90, post_qc_cells: 40, final_selected_cells: 40}, applicability: {executable: true, blockers: [], details: {}}, capabilities: {qc_rules: {schema: "scagentkit.qc.rules.v1", remove_if: ["any", "all"], max_rules: 32, max_mad_predicates: 1, operations: ["range", "mad_preset"]}, batch: ["none", "manual"], pcs: ["fixed", "computed_variance", "computed_top50"]}, limitations: [], source: {kind: "manual"}};
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "synthetic-token", run: {schema: "scagentkit.run.v1", project_id: "synthetic-parameters", input_hash: H("a"), revision: 7, status: "awaiting_review", stage: "strategy_propose", context: details.background.facts, review_node: {kind: "strategy", project_id: "synthetic-parameters", input_hash: H("a"), expected_revision: 7, proposal_hash: H("b"), review_hash: H("c"), evidence_hash: H("d"), can_decide: true, can_revise: true, can_undo: false}, strategy_review: {schema: "scagentkit.strategy.review.v1", hash: H("c"), input_hash: H("a"), evidence_hash: H("d"), details}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.call("render"); return h;}
const draft = h => JSON.parse(h.state.strategyDraftText), details = value => value.run.strategy_review.details;
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.stack});}}

await check("canonical scalar and array risks stay visible plain text outside collapsed raw audit", () => {for (const risks of ["Actual scalar risk", ["Risk one", "<img src=x onerror=alert(1)>"]]) {const value = answer(true); details(value).canonical_proposal.risks = risks; const h = setup(value), section = h.el("strategy-rationale").children.find(node => /Risks declared/.test(node.textContent)); assert(descendants(section).some(node => node.tagName === "UL")); assert.equal(descendants(section).filter(node => node.tagName === "LI").length, Array.isArray(risks) ? 2 : 1); assert(!descendants(section).some(node => node.tagName === "DETAILS")); assert.equal(h.requests.length, 0);}});
await check("supported scalar proposal inferences render as text without coercing objects", () => {const value = answer(); details(value).canonical_proposal.inferences = "Declared inference stays an inference"; const h = setup(value), section = h.el("strategy-background").children.find(node => /Model \/ proposal inferences/.test(node.textContent)); assert(descendants(section).some(node => node.tagName === "LI" && node.textContent === "Declared inference stays an inference")); const invalid = h.call("strategyTextSection", "Risks", {fake: "not a text vector"}); assert(!descendants(invalid).some(node => node.tagName === "LI")); assert.equal(h.requests.length, 0);});
await check("legacy structured proposal inferences retain their explicit raw record and separate role", () => {const value = answer(); details(value).canonical_proposal.inferences = [{value: "unverified design", source: "model_inference"}]; const before = copy(value), h = setup(value), section = h.el("strategy-background").children.find(node => /Model \/ proposal inferences/.test(node.textContent)); assert.match(section.textContent, /unverified design/); assert(descendants(section).some(node => node.tagName === "DETAILS")); assert(!descendants(section).some(node => node.tagName === "LI")); assert.deepEqual(copy(h.state.view), before); assert.equal(h.requests.length, 0);});
await check("typed QC summary counts actual fixed and MAD failure rules and any/all logic", () => {const value = answer(true); details(value).canonical_proposal.qc.rules.push({op: "mad_preset", preset_id: "keep_all", panel_hash: H("e")}); details(value).canonical_proposal.qc.remove_if = "all"; const h = setup(value); assert.match(h.el("strategy-plan-summary").textContent, /3 typed failure rules \(2 fixed ranges; 1 saved MAD presets\).*remove_if all.*AND/); assert.doesNotMatch(h.el("strategy-plan-summary").textContent, /0 supported range rules/); assert.match(h.call("suggestionSummary", qc(true), "qc").join(" "), /2 typed failure rules.*remove_if any.*OR/); assert.equal(h.requests.length, 0);});
await check("draft errors and unapplied state appear by controls without opening the raw JSON audit", () => {const h = setup(answer(true)), p = copy(h.state.view); h.control("qc-range-min-0").value = "bad bound"; h.call("chooseQCDraft"); assert.match(h.control("strategy-controls-status").textContent, /finite nonnegative/); assert.equal(h.control("strategy-controls-status").dataset.invalid, "true"); assert.equal(h.el("strategy-save").disabled, true); h.control("qc-range-min-0").value = "250"; h.call("chooseQCDraft"); assert.match(h.control("strategy-controls-status").textContent, /Unsaved.*Saved preview is unchanged.*Save/s); assert.equal(h.control("strategy-controls-status").dataset.invalid, "false"); assert.equal(h.el("strategy-edit-details").open, false); assert.deepEqual(copy(h.state.view), p); assert.equal(h.requests.length, 0);});
await check("raw PC controls do not depend on Harmony capabilities or diagnostics", () => {const h = setup(); assert.equal(h.control("pc-method").value, "fixed"); assert.equal(h.control("pc-ndim").value, "10"); assert.equal(h.control("harmony-method"), undefined); assert.equal(h.requests.length, 0);});
await check("canonical R auto-unboxed single risk remains valid without permitting nontext risks", () => {const value = answer(true); details(value).canonical_proposal.qc.risks = "Synthetic single saved risk"; details(value).qc_impact = preview(details(value).canonical_proposal.qc); const h = setup(value); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.call("madReviewError"), null); for (const risks of [7, {}, ["valid", 7], ""]) {const p = draft(h); p.qc.risks = risks; assert(h.call("typedStrategyError", p));} assert.equal(h.requests.length, 0);});
await check("canonical R auto-unboxed single resolution is shown and validated as one candidate", () => {const value = answer(); details(value).canonical_proposal.clustering.diagnostic_resolutions = .7; const h = setup(value); assert.equal(h.control("clustering-diagnostic-resolutions").value, "0.7"); assert.equal(h.call("strategyDraftError"), null); h.call("chooseClusteringDraft"); assert.deepEqual(draft(h).clustering.diagnostic_resolutions, [.7]); for (const diagnostic_resolutions of ["0.7", {}, ["0.7"], [], 0, 3]) {const p = draft(h); p.clustering.diagnostic_resolutions = diagnostic_resolutions; assert(h.call("typedStrategyError", p));} assert.equal(h.requests.length, 0);});
await check("legacy saved summary is labelled projected rather than a verified full preview", () => {const value = answer(); details(value).qc_impact = {expected_retained_cells: 90, input_cell_count: 96}; const h = setup(value); assert.match(h.el("strategy-qc-impact").textContent, /Saved legacy projected retention: 90 of 96/); assert.match(h.el("strategy-qc-impact").textContent, /full exact QC preview.*not recorded/); assert.equal(h.requests.length, 0);});
await check("processed reuse invents no QC, PC or resolution inputs", () => {const value = answer(); for (const key of ["qc", "analysis", "pcs", "clustering", "umap"]) details(value).canonical_proposal[key] = null; const h = setup(value); for (const id of ["qc-rule-combine", "pc-method", "clustering-resolution"]) assert.equal(h.control(id), undefined); assert.match(h.el("strategy-operations").textContent, /reused|Reuse is explicit/);});
await check("legacy fixed-range invalid browser text blocks Save and approval while keeping saved impact", async () => {const h = setup(), saved = copy(h.state.view), impact = h.el("strategy-qc-impact").textContent; h.control("qc-range-min-0").value = "invalid-bound"; h.call("chooseQCDraft"); assert.equal(draft(h).qc.schema, "scagentkit.qc.v1"); assert.equal(draft(h).qc.filters[0].min, "invalid-bound"); assert.match(h.control("strategy-controls-status").textContent, /finite nonnegative/); assert.equal(h.control("strategy-controls-status").dataset.invalid, "true"); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "revise"); await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 0); assert.deepEqual(copy(h.state.view), saved); assert.equal(h.el("strategy-qc-impact").textContent, impact); h.control("qc-range-min-0").value = "250"; h.call("chooseQCDraft"); assert.equal(draft(h).qc.schema, "scagentkit.qc.v1"); assert.equal(draft(h).qc.filters[0].min, 250); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
for (const [name, mutate] of [
  ["string numeric bound", q => q.filters[0].min = "250"], ["NaN text", q => q.filters[0].min = "NaN"],
  ["infinity text", q => q.filters[0].max = "Infinity"], ["negative", q => q.filters[0].min = -1],
  ["fractional feature count", q => q.filters[0].min = 1.5], ["inverted range", q => q.filters[0].max = 100],
  ["percent above 100", q => q.filters[0] = range("percent_mt", 0, 100.1)], ["no bounds", q => q.filters[0] = range("nFeature", null, null)],
  ["unsupported metric", q => q.filters[0].metric = "gene_expression"], ["unsupported operation", q => q.filters[0].op = "execute"],
  ["MAD in legacy schema", q => q.filters[0] = {op: "mad_preset", preset_id: "keep_all", panel_hash: H("e")}],
  ["condition mistaken for capture", q => q.filters[0].group = {condition: "Ca"}], ["empty literal scope", q => q.filters[0].group = {sample: ""}],
  ["unknown range field", q => q.filters[0].target_cells = 90], ["empty filters", q => q.filters = []]
]) await check("legacy range draft is blocked before Save: " + name, async () => {const h = setup(), p = draft(h); mutate(p.qc); h.state.strategyDraftText = JSON.stringify(p); h.call("buttons"); assert(h.call("strategyDraftError")); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 0);});
await check("legacy ranges preserve inclusive integer and fractional-percent choices without combined capabilities", () => {const value = answer(), q = details(value).canonical_proposal.qc; delete details(value).capabilities.qc_rules; q.filters = [range("nCount", 0, 5000, {sample: "S1", capture: "C1"}), range("nFeature", 200, null), range("percent_mt", 0, 5.88)]; const h = setup(value), before = draft(h); h.control("qc-range-max-2").value = "6.25"; h.call("chooseQCDraft"); before.qc.filters[2].max = 6.25; assert.deepEqual(draft(h), before); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.requests.length, 0);});
await check("legacy range validation retains its R contract without a combined-rule cap", () => {const h = setup(), p = draft(h); p.qc.filters = Array.from({length: 33}, () => range("nFeature", 200, null)); p.qc.risks = "Single auto-unboxed saved risk"; assert.equal(h.call("typedStrategyError", p), null); assert.equal(p.qc.schema, "scagentkit.qc.v1"); assert.equal(p.qc.filters.length, 33); assert.equal(h.requests.length, 0);});
await check("legacy fixed-range edit preserves schema and every other operation", () => {const h = setup(), before = draft(h); h.control("qc-range-min-0").value = "250"; h.call("chooseQCDraft"); before.qc.filters[0].min = 250; assert.deepEqual(draft(h), before); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
await check("explicit all selection creates typed rules and leaves saved impact unchanged", () => {const h = setup(), impact = h.el("strategy-qc-impact").textContent; h.control("qc-rule-combine").value = "all"; h.call("chooseQCDraft"); assert.equal(draft(h).qc.schema, "scagentkit.qc.rules.v1"); assert.equal(draft(h).qc.remove_if, "all"); assert.deepEqual(draft(h).qc.rules, proposal().qc.filters); assert.equal(h.el("strategy-qc-impact").textContent, impact); assert.equal(h.requests.length, 0);});
await check("empty new fixed rule cannot be saved or become implicit keep-all", () => {const h = setup(answer(true)); h.call("changeQCRules", "range"); const q = draft(h).qc; assert.equal(q.rules.at(-1).metric, ""); assert.equal(q.rules.at(-1).min, null); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.requests.length, 0);});
await check("new range accepts exact supplied group and updates complete draft only", () => {const h = setup(answer(true)); h.call("changeQCRules", "range"); h.control("qc-range-metric-2").value = "nCount"; h.control("qc-range-min-2").value = "100"; h.control("qc-range-group-2").value = JSON.stringify({sample: "S1", capture: "C1"}); h.call("chooseQCDraft"); assert.deepEqual(draft(h).qc.rules[2], range("nCount", 100, null, {sample: "S1", capture: "C1"})); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.requests.length, 0);});
await check("removing the final rule keeps an invalid explicit empty draft", () => {const h = setup(); h.call("changeQCRules", "remove", 0); assert.deepEqual(draft(h).qc.rules, []); assert.equal(h.el("strategy-save").disabled, true);});
await check("a saved dynamic rule is limited to one bound available preset", () => {const value = answer(true); details(value).mad_panel = panel(); const h = setup(value); h.call("changeQCRules", "mad"); assert.equal(draft(h).qc.rules.at(-1).preset_id, ""); assert.equal(h.el("strategy-save").disabled, true); h.control("qc-mad-preset").value = "low_counts3"; h.call("chooseQCDraft"); assert.equal(draft(h).qc.rules.at(-1).panel_hash, H("e")); assert.equal(h.control("qc-add-mad").disabled, true); assert.equal(h.requests.length, 0);});
await check("legacy MAD retains one picker and exact original validation", () => {const value = answer(), d = details(value); d.mad_panel = panel(); d.canonical_proposal.qc = {schema: "scagentkit.qc.mad.v1", rationale: "Synthetic saved candidate", risks: [], preset_id: "keep_all", panel_hash: H("e")}; d.qc_impact = preview(d.canonical_proposal.qc, 90); d.qc_mad = {panel_hash: H("e"), evidence_hash: H("f"), choice: copy(d.canonical_proposal.qc), impact: {}}; const h = setup(value); assert.equal(h.control("qc-mad-preset"), undefined); assert(h.control("mad-preset-select")); assert.equal(h.call("madReviewError"), null); h.call("chooseMadPreset", "low_counts3"); assert.equal(draft(h).qc.schema, "scagentkit.qc.mad.v1"); assert.equal(draft(h).qc.preset_id, "low_counts3"); assert.equal(h.requests.length, 0);});
await check("saved new QC review validates original exact partition and rule binding", () => {const h = setup(answer(true)); assert.equal(h.call("madReviewError"), null); assert.equal(h.el("strategy-approve").disabled, false); h.state.view.run.strategy_review.details.qc_impact.keep_cells.push("duplicate-foreign"); assert(h.call("madReviewError")); h.call("buttons"); assert.equal(h.el("strategy-approve").disabled, true);});
await check("combined MAD validates the panel without equating preset-alone retention with combined retention", () => {const value = answer(true), d = details(value); d.mad_panel = panel(); d.canonical_proposal.qc.rules.push({op: "mad_preset", preset_id: "keep_all", panel_hash: H("e")}); d.qc_impact = preview(d.canonical_proposal.qc, 40); d.qc_mad = {panel_hash: H("e"), evidence_hash: H("f"), choice: copy(d.canonical_proposal.qc)}; const h = setup(value); assert.equal(h.call("madReviewError"), null); assert.equal(h.control("mad-preset-select"), undefined); assert(h.control("qc-mad-preset"));});
await check("AND allows an available all-failing MAD component while final retained scope remains authoritative", () => {const value = answer(true), d = details(value); d.mad_panel = panel(); d.mad_panel.presets[4].all_cells_removed = true; d.mad_panel.presets[4].retained = 0; d.canonical_proposal.qc.remove_if = "all"; d.canonical_proposal.qc.rules.push({op: "mad_preset", preset_id: "high_mt3", panel_hash: H("e")}); d.qc_impact = preview(d.canonical_proposal.qc, 70); d.qc_mad = {panel_hash: H("e"), evidence_hash: H("f"), choice: copy(d.canonical_proposal.qc)}; const h = setup(value); const option = h.control("qc-mad-preset").children.find(node => node.getAttribute("value") === "high_mt3"); assert.equal(option.disabled, false); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.call("madReviewError"), null); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.requests.length, 0); d.qc_impact = preview(d.canonical_proposal.qc, 0); h.state.view.run.strategy_review.details.qc_impact = copy(d.qc_impact); h.call("buttons"); assert.equal(h.el("strategy-approve").disabled, true);});
await check("legacy runtime capabilities prevent combined schema conversion", () => {const value = answer(); delete details(value).capabilities.qc_rules; const h = setup(value), before = h.state.strategyDraftText; assert.equal(h.control("qc-add-range").disabled, true); h.call("changeQCRules", "range"); assert.equal(h.state.strategyDraftText, before); h.control("qc-rule-combine").value = "all"; h.call("chooseQCDraft"); assert.equal(h.state.strategyDraftText, before); assert.equal(h.requests.length, 0);});
await check("readable impact uses original denominator and separates overlap, prefilter and doublets", () => {const h = setup(answer(true)), text = h.el("strategy-qc-impact").textContent; assert.match(text, /Original input: 100; pre-score: 90/); assert.match(text, /40\.00%/); assert.match(text, /20\.00%/); assert.match(text, /must not be added/); assert.match(text, /cannot be restored/); assert.match(text, /not removed twice/); assert.match(text, /Pairwise failure overlap/); assert.match(text, /sample.*S1/s); assert.equal(h.requests.length, 0);});
await check("all logic displays true final exclusive removals without recomputing counts", () => {const value = answer(true); details(value).canonical_proposal.qc.remove_if = "all"; details(value).qc_impact = preview(details(value).canonical_proposal.qc, 70); const h = setup(value); assert.match(h.el("strategy-qc-impact").textContent, /after QC: 70/); assert.equal(h.call("madReviewError"), null); assert.equal(h.requests.length, 0);});
for (const [name, mutate] of [
  ["empty rules", q => q.rules = []], ["33 rules", q => q.rules = Array.from({length: 33}, () => range())], ["unsupported failure logic", q => q.remove_if = "automatic"],
  ["unknown operation", q => q.rules[0].op = "system"], ["code field", q => q.rules[0].code = "never()"], ["unsupported metric", q => q.rules[0].metric = "hallucinated"],
  ["negative bound", q => q.rules[0].min = -1], ["fractional count bound", q => q.rules[0].min = 1.5], ["inverted range", q => q.rules[0].max = 100],
  ["unbounded rule", q => q.rules[0].min = null], ["percent above 100", q => q.rules[1].max = 101], ["condition grouping", q => q.rules[0].group = {condition: "Ca"}],
  ["unavailable MAD candidate", q => q.rules.push({op: "mad_preset", preset_id: "any_quality3", panel_hash: H("e")})],
  ["stale MAD panel", q => q.rules.push({op: "mad_preset", preset_id: "keep_all", panel_hash: H("a")})],
  ["two MAD rules", q => q.rules.push(...Array.from({length: 2}, () => ({op: "mad_preset", preset_id: "keep_all", panel_hash: H("e")})))],
  ["new MAD parameter", q => q.rules.push({op: "mad_preset", preset_id: "keep_all", panel_hash: H("e"), nmads: 3})]
]) await check("unsupported QC draft blocks Save without requests: " + name, async () => {const value = answer(true); details(value).mad_panel = panel(); const h = setup(value), p = draft(h); mutate(p.qc); h.state.strategyDraftText = JSON.stringify(p); h.call("buttons"); assert(h.call("strategyDraftError")); assert.equal(h.el("strategy-save").disabled, true); await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 0);});
await check("invalid text remains invalid text rather than becoming zero or null", () => {const h = setup(answer(true)); h.control("qc-range-min-0").value = "NaN"; h.call("chooseQCDraft"); assert.equal(draft(h).qc.rules[0].min, "NaN"); assert.equal(h.el("strategy-save").disabled, true);});
await check("all-computed variance permits arbitrary explicit fractions and no .80 default", () => {const h = setup(); h.control("pc-method").value = "computed_variance"; h.call("choosePCDraft"); assert.equal(draft(h).pcs.threshold, null); assert.match(h.control("pc-threshold").getAttribute("placeholder"), /0\.80 reference/); assert.equal(h.el("strategy-save").disabled, true); h.control("pc-threshold").value = ".93"; h.call("choosePCDraft"); assert.deepEqual(draft(h).pcs, {method: "computed_variance", threshold: .93}); assert.equal(h.call("strategyDraftError"), null); assert.equal(h.requests.length, 0);});
await check("fixed PC count respects the declared computed basis bound", () => {const h = setup(); h.control("pc-ndim").value = "31"; h.call("choosePCDraft"); assert(h.call("strategyDraftError")); h.control("pc-ndim").value = "20"; h.call("choosePCDraft"); assert.equal(h.call("strategyDraftError"), null);});
await check("legacy first-50 policies retain exactly .80/.85", () => {const h = setup(), p = draft(h); p.pcs = {method: "computed_top50", threshold: .9}; assert(h.call("typedStrategyError", p)); p.pcs.threshold = .85; assert.equal(h.call("typedStrategyError", p), null); assert.match(h.control("pc-policy-note").textContent, /all actually computed.*first min\(50/s);});
function actualDiagnostics() {return {basis_artifact_sha256: H("e"), pc_candidates: {schema: "scagentkit.pc.candidates.v1", total_computed_pcs: 60, reference_pcs: 50, shortfall_count: 0, candidates: {p80: {threshold: .8, ndim: 40, supported: true}, p85: {threshold: .85, ndim: 43, supported: true}}}, all_pc_variance: {status: "saved", source: "strategy_basis_saved_pca_evidence", basis_artifact_sha256: H("e"), available_pcs: 60, fraction_per_pc: Array.from({length: 60}, () => 1 / 60), cumulative_fraction: Array.from({length: 60}, (_, index) => (index + 1) / 60), denominator: "Synthetic sum of all 60 actual computed PC variances"}, cluster_candidates: {status: "saved", source: "analysis_saved_louvain_diagnostics", basis_artifact_sha256: H("e"), analysis_artifact_sha256: H("f"), chosen_resolution: .5, candidates: [{resolution: .3, chosen: false, n_clusters: 3, min_cluster_size: 10, max_cluster_size: 50, ari_vs_chosen: .7, ari_vs_previous: null}, {resolution: .5, chosen: true, n_clusters: 4, min_cluster_size: 8, max_cluster_size: 40, ari_vs_chosen: 1, ari_vs_previous: .7}]}};}
await check("actual saved all-PC and cluster diagnostics are rendered separately from initial policy", () => {const value = answer(); value.run.computed_diagnostics = actualDiagnostics(); const h = setup(value); assert.equal(h.control("pc-status").dataset.status, "computed"); assert.match(h.control("pc-all-computed").textContent, /Actually computed PCs: 60/); assert.match(h.control("pc-candidates").textContent, /reference PCs: 50/); assert.match(h.control("clustering-actual-comparison").textContent, /Actual saved comparison/); assert.match(h.control("clustering-actual-comparison").textContent, /ARI \/ chosen/); assert.equal(h.requests.length, 0);});
await check("missing or mismatched saved diagnostic binding never fabricates observed evidence", () => {const value = answer(); value.run.computed_diagnostics = actualDiagnostics(); value.run.computed_diagnostics.all_pc_variance.basis_artifact_sha256 = H("a"); value.run.computed_diagnostics.cluster_candidates.basis_artifact_sha256 = H("a"); const h = setup(value); assert.match(h.control("pc-all-computed").textContent, /not recorded/); assert.match(h.control("clustering-actual-comparison").textContent, /Not run/);});
await check("pending diagnostics show no invented PCs, cluster counts or curves", () => {const h = setup(); assert.equal(h.control("pc-status").dataset.status, "deferred"); assert.match(h.control("clustering-actual-comparison").textContent, /Not run/); assert.match(h.control("pc-all-computed").textContent, /not recorded/);});
await check("direct resolution and candidate editor patch exactly the clustering object", () => {const h = setup(), before = draft(h); h.control("clustering-resolution").value = ".7"; h.control("clustering-diagnostic-resolutions").value = ".2, .4, .8"; h.call("chooseClusteringDraft"); before.clustering = {resolution: .7, diagnostic_resolutions: [.2, .4, .8]}; assert.deepEqual(draft(h), before); assert.equal(h.requests.length, 0);});
for (const text of [".2,.2", "0,.5", "2.1", ".1,.2,.3,.4,.5,.6", ".1,,.4", "NaN"]) await check("invalid diagnostic list blocks Save: " + text, () => {const h = setup(); h.control("clustering-diagnostic-resolutions").value = text; h.call("chooseClusteringDraft"); assert(h.call("strategyDraftError")); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.requests.length, 0);});
await check("manual JSON edits synchronize form values without resetting draft or requests", () => {const h = setup(), p = draft(h); p.pcs = {method: "computed_variance", threshold: .87}; p.clustering = {resolution: .9, diagnostic_resolutions: [.6, .9]}; p.qc.filters[0].min = 300; h.el("strategy-json").value = JSON.stringify(p); h.event(h.el("strategy-json"), "input"); assert.deepEqual(draft(h), p); assert.equal(h.control("pc-threshold").value, "0.87"); assert.equal(h.control("clustering-resolution").value, "0.9"); assert.equal(h.control("qc-range-min-0").value, "300"); assert.equal(h.requests.length, 0);});
await check("unsaved JSON values never overwrite the canonical saved policy or evidence", () => {const h = setup(answer(true)), before = copy(h.state.view), p = draft(h); p.pcs = {method: "computed_variance", threshold: .87}; h.el("strategy-json").value = JSON.stringify(p); h.event(h.el("strategy-json"), "input"); const savedPC = h.control("pc-card").children.find(node => node.tagName === "DETAILS" && /Saved typed PC policy/.test(node.textContent)); assert.match(savedPC.textContent, /"method": "fixed"/); assert.doesNotMatch(savedPC.textContent, /0\.87/); assert.deepEqual(copy(h.state.view), before); assert.equal(h.requests.length, 0);});
await check("one Save submits complete edited plan and rebuilds without model or Continue", async () => {const h = setup(answer(true)); h.control("clustering-resolution").value = ".7"; h.call("chooseClusteringDraft"); const p = draft(h); h.fetchImpl = async (_, options) => {const body = JSON.parse(options.body), value = answer(true); value.run.revision = 8; value.run.review_node.expected_revision = 8; details(value).canonical_proposal = body.proposal; details(value).qc_impact = preview(body.proposal.qc); return {ok: true, json: async () => value};}; await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); assert.equal(JSON.parse(h.requests[0].options.body).action, "revise"); assert.deepEqual(JSON.parse(h.requests[0].options.body).proposal, p); assert.equal(h.el("strategy-approve").disabled, false); assert(!h.requests.some(request => /continue|suggestion/.test(request.url)));});
await check("stale Save keeps exact draft and locks controls", async () => {const h = setup(answer(true)); h.control("clustering-resolution").value = ".7"; h.call("chooseClusteringDraft"); const text = h.state.strategyDraftText; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale synthetic review"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.strategyDraftText, text); assert.equal(h.state.stale, true); assert(h.state.strategyControls.every(control => control.disabled));});
await check("completed inspection disables every control and draft mutation function", () => {const value = answer(true); value.run.status = "complete"; value.run.stage = "complete"; value.run.review_node = null; const h = setup(value), before = h.state.strategyDraftText; assert(h.state.strategyControls.every(control => control.disabled)); for (const action of ["chooseQCDraft", "choosePCDraft", "chooseClusteringDraft"]) h.call(action); h.call("changeQCRules", "range"); assert.equal(h.state.strategyDraftText, before); assert.equal(h.requests.length, 0);});
await check("doublet choice remains separate and updates only its own explicit reason/method", () => {const value = answer(true), d = details(value); d.canonical_proposal.doublet = {method: "keep", reason: "Synthetic diagnostic-only choice"}; d.capabilities.doublet = ["keep", "remove_predicted"]; d.doublet_diagnostics = {schema: "scagentkit.doublet.evidence.v1", status: "available", capture_stats: {}}; const h = setup(value), before = draft(h); h.control("doublet-draft-method").value = "remove_predicted"; h.control("doublet-draft-reason").value = "Explicit synthetic correction reason"; h.event(h.control("doublet-draft-method"), "change"); before.doublet = {method: "remove_predicted", reason: "Explicit synthetic correction reason"}; assert.deepEqual(draft(h), before); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
await check("raw audit stays collapsed with local system fonts, visible focus and reduced motion", () => {const h = setup(answer(true)); assert(descendants(h.el("strategy-operations")).filter(node => node.tagName === "DETAILS").every(node => !node.open)); assert.match(css, /system-ui/); assert.match(css, /#f7f7f2/); assert.match(css, /#9b4a32/); assert.match(css, /:focus-visible/); assert.match(css, /prefers-reduced-motion/); assert.doesNotMatch(css, /@import|url\(/);});
await check("six parameter disclosures preserve exact controls and canonical saved summaries", () => {const h = setup(answer(true)), groups = h.el("strategy-operations").children; assert.equal(groups.length, 6); assert(groups.every(group => group.tagName === "DETAILS" && !group.open && group.children[0].tagName === "SUMMARY")); assert.match(groups[0].children[0].textContent, /QC and cell retention.*Saved.*2 fixed ranges/s); assert.match(groups[2].children[0].textContent, /Fixed 10 PCs/); assert.match(h.el("strategy-key-parameters").textContent, /QC failure rules.*PC policy.*Fixed 10 PCs.*Batch choice.*Clustering/s); assert.equal(h.control("qc-range-min-0").value, "200"); assert.equal(h.requests.length, 0);});
await check("open parameter group persists when an explicit draft rebuild adds a rule", () => {const value = answer(true); details(value).mad_panel = panel(); const h = setup(value); h.el("strategy-operations").children[0].open = true; h.call("changeQCRules", "mad"); assert.equal(h.el("strategy-operations").children[0].open, true); assert.equal(draft(h).qc.rules.length, 3); assert.equal(h.control("qc-range-min-0").value, "200"); assert.equal(h.requests.length, 0);});
await check("key summary and nearby impact remain canonical when the draft changes", () => {const h = setup(answer(true)), savedSummary = h.el("strategy-key-parameters").textContent, savedImpact = h.el("strategy-qc-impact").textContent; h.control("pc-method").value = "computed_variance"; h.control("pc-threshold").value = ".87"; h.call("choosePCDraft"); assert.equal(h.el("strategy-key-parameters").textContent, savedSummary); assert.equal(h.el("strategy-qc-impact").textContent, savedImpact); assert.match(h.el("strategy-impact-draft-status").textContent, /Unsaved.*saved impact values have not changed.*Save/s); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
await check("invalid draft is visible beside impact even with every parameter group closed", () => {const h = setup(answer(true)); h.control("qc-range-min-0").value = "invalid"; h.call("chooseQCDraft"); assert(h.el("strategy-operations").children.every(group => !group.open)); assert.match(h.el("strategy-impact-draft-status").textContent, /finite nonnegative/); assert.equal(h.el("strategy-impact-draft-status").dataset.invalid, "true"); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.requests.length, 0);});
await check("disabled model worker is collapsed but can be explicitly expanded without any request", () => {const h = setup(); assert.equal(h.el("suggestion-disclosure").open, false); assert.match(h.el("suggestion-disclosure-status").textContent, /Unavailable/); h.el("suggestion-disclosure").open = true; h.call("renderSuggestion"); assert.equal(h.el("suggestion-disclosure").open, true); assert.equal(h.requests.length, 0);});
await check("model errors and exact outgoing previews expand the optional disclosure", () => {const h = setup(); h.state.suggestionError = "Saved transfer could not be verified"; h.call("renderSuggestion"); assert.equal(h.el("suggestion-disclosure").open, true); assert.match(h.el("suggestion-message").textContent, /could not be verified/); h.el("suggestion-disclosure").open = false; h.state.suggestionError = ""; h.state.suggestion = {enabled: false, suggestion: {kind: "strategy", preview: {provider: "fixture", model: "fixture-preview", external: true, notice: "Exact aggregate transfer needs explicit consent", generation: {}, user_prompt: "fixture aggregate"}}}; h.call("renderSuggestion"); assert.equal(h.el("suggestion-disclosure").open, true); assert.match(h.el("suggestion-notice").textContent, /explicit consent/); assert.equal(h.requests.length, 0);});
await check("saved local blockers remain explicit rather than hidden in raw audit", () => {const value = answer(true); details(value).applicability = {executable: false, blockers: "Missing declared technical design"}; const h = setup(value); assert.equal(h.el("strategy-blockers").hidden, false); assert(descendants(h.el("strategy-blockers")).some(row => row.tagName === "LI" && /Missing declared/.test(row.textContent))); assert.match(h.el("strategy-applicability").textContent, /blocked/); assert.equal(h.requests.length, 0);});
await check("readonly historical groups retain summaries while every scientific edit stays disabled", () => {const value = answer(true); value.run.status = "complete"; value.run.stage = "complete"; value.run.review_node = null; const h = setup(value); assert.match(h.el("strategy-key-parameters").textContent, /Fixed 10 PCs/); assert(h.state.strategyControls.every(control => control.disabled)); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
await check("legacy MAD disclosure describes the actual canonical QC preset", () => {const h = setup(); assert.equal(h.call("savedOperationSummary", "qc-mad", {qc: {schema: "scagentkit.qc.mad.v1", preset_id: "keep_all"}}), "Saved preset · keep_all"); assert.equal(h.requests.length, 0);});
const sha = text => createHash("sha256").update(text).digest("hex");
const report = {schema: "scagentkit.strategy-parameters.dom-tests.v1", actualProductionSource: true, syntheticContractRecords: true, actualBrowser: false, actualR: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(source), cssSha256: sha(css), driverSha256: sha(fs.readFileSync(file)), tests: results.length, passed: results.filter(row => row.passed).length, failed: results.filter(row => !row.passed).length, results};
if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n");
console.log(JSON.stringify({tests: report.tests, passed: report.passed, failed: report.failed, failures: results.filter(row => !row.passed)})); if (report.failed) process.exitCode = 1;
