// Production-source offline DOM checks. No browser, R, provider or network.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import assert from "node:assert/strict";
import {webcrypto, createHash} from "node:crypto";
import {fileURLToPath} from "node:url";
const __filename = fileURLToPath(import.meta.url), __dirname = path.dirname(__filename);
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/review.js"), htmlPath = path.join(repo, "workbench/static/review.html");
const results = [], copy = value => JSON.parse(JSON.stringify(value)), sha = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must use textContent");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui() {
  const source = fs.readFileSync(sourcePath, "utf8"), html = fs.readFileSync(htmlPath, "utf8"), elements = new Map(), storage = new Map(), timers = new Map(); let timer = 0;
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate production HTML ID"); elements.set(match[2], new Element(match[1]));}
  const harness = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search: ""}, addEventListener() {}, confirm() {return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}},
    setTimeout(callback, delay) {timers.set(++timer, {callback, delay}); return timer;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); assert(harness.fetchImpl, "Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args); harness.el = id => document.getElementById(id);
  harness.control = id => {const nodes = descendants(harness.el("strategy-operations")); return nodes.find(node => node.getAttribute("id") === id);};
  return harness;
}
const inputHash = "a".repeat(64), proposalHash = "b".repeat(64), reviewHash = "c".repeat(64), evidenceHash = "d".repeat(64);
function batch(method = "none") {return method === "harmony" ? {method, group_by_vars: ["technical_run"], theta: 2, lambda: 1, sigma: .1, max_iter: 10, nclust: 30, reason: "Explicit technical batch in a declared crossed design"} : {method, reason: method === "none" ? "Keep the computed representation by default" : "Analyst design work remains pending"};}
function proposal(method = "none", pcs = {method: "computed_top50", threshold: .8}) {return {schema: "scagentkit.strategy.v1", rationale: "Typed deterministic analysis plan", risks: ["Correction can remove biological signal"], inferences: [], qc: {method: "none"}, analysis: {normalization_method: "LogNormalize", scale_factor: 10000, nfeatures: 2000, npcs: 50, seed: 999}, pcs, batch: batch(method), clustering: {resolution: .4}, umap: {run: true}};}
function pcRecord(computed = false) {
  const record = {schema: "scagentkit.strategy.pc-review.v1", status: computed ? "computed" : "pending_computation", policy: {method: "computed_top50", threshold: .8}, interpretation: "Finite empirical candidates, not biological truth"};
  if (computed) Object.assign(record, {artifact: {path: "checkpoints/strategy_basis-frozen.rds", sha256: "e".repeat(64)}, basis_dependency_hash: "f".repeat(64), actual: {top50_candidates: {schema: "scagentkit.pc.candidates.v1", total_computed_pcs: 40, reference_pcs: 40, target_reference_pcs: 50, shortfall: true, shortfall_count: 10, denominator: "Sum of first 40 computed PC variances, not total expressed-gene variance", candidates: {p80: {threshold: .8, ndim: 17, supported: true, reason: "First exact crossing"}, p85: {threshold: .85, ndim: 23, supported: true, reason: "First exact crossing"}}}}});
  return record;
}
function answer(method = "none", computed = false) {
  const details = {canonical_proposal: proposal(method), background: {facts: {species: "human", columns: {batch: "technical_run", sample: "sample_id", donor: "donor_id", condition: "Ca_Ctrl", capture: "loading_unit"}, design: {technical_batch: true, notes: "Explicit technical processing provenance"}}, missing: []}, quality: {cell_count: 440}, applicability: {executable: true, blockers: [], details: {}}, capabilities: {batch: ["none", "manual", "harmony"], pcs: ["fixed", "computed_variance", "computed_top50"]}, pc_diagnostics: pcRecord(computed), limitations: [], source: {kind: "manual"}};
  if (method === "harmony") details.harmony = {choice: batch(method), audit: {selected_factors: [{column: "technical_run", role: "batch", levels: 2}], biological_roles: [{role: "condition", column: "Ca_Ctrl"}], technical_batch_declared: true, joint_rank: {full_rank: true}, warnings: ["Crossed design does not establish scientific benefit"]}, executable: true, blockers: [], dependency_hash: "0".repeat(64)};
  return {schema: "scagentkit.run-review.workbench.v1", csrf_token: "offline-token", run: {schema: "scagentkit.run.v1", project_id: "offline-harmony", input_hash: inputHash, revision: 7, status: "awaiting_review", stage: "strategy_propose", context: details.background.facts, review_node: {kind: "strategy", project_id: "offline-harmony", input_hash: inputHash, expected_revision: 7, proposal_hash: proposalHash, review_hash: reviewHash, evidence_hash: evidenceHash, can_decide: true, can_revise: true, can_undo: false}, strategy_review: {schema: "scagentkit.strategy.review.v1", hash: reviewHash, input_hash: inputHash, evidence_hash: evidenceHash, details}}};
}
function setup(value = answer()) {const h = ui(); h.state.view = h.call("verify", copy(value)); h.state.continuation = value.continuation || null; h.call("render"); return h;}
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("one central plan preserves six operation sections", () => {const h = setup(); assert.equal(h.el("strategy-operations").children.length, 6); assert.equal(h.control("harmony-method").value, "none"); assert.equal(h.el("strategy-approve").disabled, false); assert.equal(h.requests.length, 0);});
  await check("initial PC policy never fabricates computed count or dimensions", () => {const h = setup(); assert.equal(h.control("pc-status").dataset.status, "deferred"); assert.match(h.control("pc-status").textContent, /not been computed.*Actual computed PC count.*unknown.*typed policy only/); assert.match(h.control("pc-candidates").textContent, /deferred.*no preview value is fabricated/); assert.doesNotMatch(h.control("pc-candidates").textContent, /17|23/);});
  await check("computed diagnostics display actual first crossings and shortfall", () => {const h = setup(answer("none", true)); assert.equal(h.control("pc-status").dataset.status, "computed"); assert.match(h.control("pc-candidates").textContent, /p800.817true.*p850.8523true.*Computed PCs: 40; reference PCs: 40; shortfall: 10/s); assert.equal(h.control("pc-details").open, false); assert.match(h.control("pc-details").textContent, /strategy_basis-frozen.*eeee.*ffff/s);});
  await check("unbound cached diagnostics disclose deferred values", () => {const value = answer("none", true); delete value.run.strategy_review.details.pc_diagnostics.artifact.sha256; const h = setup(value); assert.equal(h.control("pc-status").dataset.status, "deferred"); assert.doesNotMatch(h.control("pc-candidates").textContent, /17|23/);});
  await check("PC variance denominator empirical policy and one-PC limit are explicit", () => {const h = setup(); assert.match(h.control("pc-policy-note").textContent, /empirical policies.*not universal optima.*min\(50, computed PCs\).*not total expressed-gene variance.*shortfalls.*one-PC.*not clipped/);});
  await check("batch roles provenance and biological-group exclusion stay explicit", () => {const h = setup(); assert.match(h.control("harmony-provenance").textContent, /technical_batch: TRUE.*Explicit technical processing provenance.*technical_run, sample_id, donor_id.*Group, condition, treatment and physical capture are excluded.*aliases/);});
  await check("Harmony risk avoids claimed preservation and visual tuning", () => {const h = setup(); assert.match(h.control("harmony-risk").textContent, /remove biological signal.*Crossed design.*does not prove.*confounding.*blocked.*excluded as a correction covariate.*not a claim.*effect is preserved.*UMAP/);});
  await check("saved none never auto-selects a correction column", () => {const h = setup(); assert.equal(h.control("harmony-parameters").hidden, true); assert.equal(h.control("harmony-group_by_vars").value, ""); assert.deepEqual(copy(h.state.view.run.strategy_review.details.canonical_proposal.batch), batch());});
  await check("saved Harmony typed fields and design audit remain inspectable", () => {const h = setup(answer("harmony", true)); assert.equal(h.control("harmony-method").value, "harmony"); assert.equal(h.control("harmony-parameters").hidden, false); assert.equal(JSON.parse(h.control("harmony-group_by_vars").value)[0], "technical_run"); assert.match(h.control("harmony-design").textContent, /selected_factors.*technical_run.*biological_roles.*Ca_Ctrl.*joint_rank.*full_rank/s);});
  await check("changing method creates unsupported-incomplete draft until explicit fields are supplied", () => {const h = setup(); h.control("harmony-method").value = "harmony"; h.call("chooseBatchDraft"); assert.equal(JSON.parse(h.el("strategy-json").value).batch.method, "harmony"); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
  await check("typed Harmony fields edit full draft only without source or cell mutation", () => {const h = setup(), before = copy(h.state.view.run); h.control("harmony-method").value = "harmony"; for (const [key, value] of Object.entries(batch("harmony"))) if (!["method", "reason"].includes(key)) h.control("harmony-" + key).value = JSON.stringify(value); h.control("harmony-reason").value = "Explicit technical batch in a declared crossed design"; h.call("chooseBatchDraft"); assert.deepEqual(JSON.parse(h.el("strategy-json").value).batch, batch("harmony")); assert.equal(h.el("strategy-save").disabled, false); assert.equal(h.el("strategy-approve").disabled, true); assert.deepEqual(copy(h.state.view.run), before); assert.equal(h.requests.length, 0);});
  await check("switching to none removes all integration parameter fields from draft", () => {const h = setup(answer("harmony")); h.control("harmony-method").value = "none"; h.control("harmony-reason").value = "Keep the computed representation"; h.call("chooseBatchDraft"); assert.deepEqual(Object.keys(JSON.parse(h.state.strategyDraftText).batch).sort(), ["method", "reason"]);});
  await check("manual remains a recorded pending plan with enforced boundary", () => {const value = answer("manual"); value.run.strategy_review.details.applicability.executable = false; const h = setup(value); assert.equal(h.el("strategy-approve").disabled, false); assert.match(h.el("strategy-execution-note").textContent, /pending.*stops for configuration.*No integration is executed/);});
  await check("80-to-85 selector modifies policy threshold only", () => {const h = setup(), before = proposal(); h.control("pc-top50-threshold").value = ".85"; h.call("choosePCDraft"); const draft = JSON.parse(h.state.strategyDraftText); assert.deepEqual(draft.pcs, {method: "computed_top50", threshold: .85}); before.pcs.threshold = .85; assert.deepEqual(draft, before); assert.equal(h.el("strategy-approve").disabled, true); assert.equal(h.requests.length, 0);});
  await check("legacy fixed and computed_variance policies remain supported", () => {const h = setup(); for (const pcs of [{method: "fixed", ndim: 20}, {method: "computed_variance", threshold: .9}, null]) {const draft = proposal("none", pcs); assert.equal(h.call("typedStrategyError", draft), null);}});
  await check("processed reuse does not fabricate PCA controls", () => {const value = answer(); value.run.strategy_review.details.canonical_proposal.pcs = null; value.run.strategy_review.details.pc_diagnostics.status = "processed_reuse"; const h = setup(value); assert.equal(h.control("pc-method"), undefined); assert.match(h.el("strategy-operations").textContent, /Reuse is explicit.*no PCA dimensions are invented/);});
  for (const [name, mutate] of [
    ["provider operation", draft => draft.provider = {api_key: "never"}], ["top-level R code", draft => draft.code = "source('never')"], ["nested R code", draft => draft.qc.code = "system('never')"],
    ["batch code", draft => draft.batch.code = "never()"], ["unsupported batch method", draft => draft.batch.method = "automatic_best"], ["empty reason", draft => draft.batch.reason = " "],
    ["missing Harmony field", draft => delete draft.batch.sigma], ["unknown correction column", draft => draft.batch.group_by_vars = ["undeclared"]], ["condition correction", draft => draft.batch.group_by_vars = ["Ca_Ctrl"]],
    ["capture correction", draft => draft.batch.group_by_vars = ["loading_unit"]], ["duplicate correction columns", draft => draft.batch.group_by_vars = ["technical_run", "technical_run"]], ["four correction columns", draft => draft.batch.group_by_vars = ["a", "b", "c", "d"]],
    ["string theta", draft => draft.batch.theta = "2"], ["negative theta", draft => draft.batch.theta = -1], ["zero lambda", draft => draft.batch.lambda = 0], ["wrong factor-array length", draft => draft.batch.theta = [1, 2]],
    ["sigma zero", draft => draft.batch.sigma = 0], ["sigma above one", draft => draft.batch.sigma = 1.1], ["too many iterations", draft => draft.batch.max_iter = 51], ["fractional iterations", draft => draft.batch.max_iter = 2.5],
    ["one Harmony cluster", draft => draft.batch.nclust = 1], ["too many Harmony clusters", draft => draft.batch.nclust = 101], ["unsupported top50 threshold", draft => draft.pcs.threshold = .9],
    ["invented top50 dimensions", draft => draft.pcs.ndim = 20], ["PC provider field", draft => draft.pcs.provider = "never"]
  ]) await check("unsafe or unsupported typed plan refuses Save: " + name, async () => {const h = setup(), draft = proposal("harmony"); mutate(draft); h.state.strategyDraftText = JSON.stringify(draft); h.call("buttons"); assert.equal(h.el("strategy-save").disabled, true); assert.equal(h.el("strategy-approve").disabled, true); assert(h.call("strategyDraftError")); await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 0);});
  await check("missing explicit technical declaration blocks Harmony column use", () => {const value = answer(); value.run.strategy_review.details.background.facts.design.technical_batch = false; const h = setup(value); assert(h.call("typedStrategyError", proposal("harmony"))); assert.deepEqual(copy(h.call("declaredHarmonyColumns")), []);});
  await check("physical capture alias and ambiguous donor/sample mappings are ineligible", () => {for (const mutate of [columns => columns.batch = columns.capture, columns => columns.sample = columns.donor]) {const value = answer(); mutate(value.run.strategy_review.details.background.facts.columns); const h = setup(value), eligible = copy(h.call("declaredHarmonyColumns")); assert.equal(eligible.includes(value.run.strategy_review.details.background.facts.columns.sample === "donor_id" ? "donor_id" : "loading_unit"), false);}});
  await check("numeric scalar or exact-factor numeric arrays remain valid", () => {const h = setup(), draft = proposal("harmony"); draft.batch.group_by_vars = ["technical_run", "sample_id"]; draft.batch.theta = [0, 3]; draft.batch.lambda = [1, 2]; assert.equal(h.call("typedStrategyError", draft), null); draft.batch.theta = [2]; assert.equal(h.call("typedStrategyError", draft), null);});
  await check("literal explanation text never becomes executable code", () => {const h = setup(), draft = proposal(); draft.rationale = "source('never') $(never) <script>literal</script>"; draft.batch.reason = "system('never') is an explanation string"; assert.equal(h.call("typedStrategyError", draft), null);});
  await check("new batch retry requires explicit saved failure and no active task", () => {const h = setup(); assert.equal(h.call("supportedSavedLocalRetry", {stage: "strategy_batch", status: "failed"}, null), true); assert.equal(h.call("supportedSavedLocalRetry", {stage: "strategy_batch", status: "ready"}, null), false); assert.equal(h.call("supportedSavedLocalRetry", {stage: "strategy_batch", status: "failed"}, {status: "running"}), false);});
  await check("one Save sends complete typed Harmony plan without execution", async () => {const h = setup(), draft = proposal("harmony"); h.state.strategyDraftText = JSON.stringify(draft); h.fetchImpl = async (_, options) => {const request = JSON.parse(options.body), result = answer("harmony"); result.run.revision = 8; result.run.review_node.expected_revision = 8; result.run.strategy_review.details.canonical_proposal = request.proposal; return {ok: true, json: async () => result};}; await h.call("decideStrategy", "revise"); assert.equal(h.requests.length, 1); const request = JSON.parse(h.requests[0].options.body); assert.equal(request.action, "revise"); assert.deepEqual(request.proposal, draft); assert.equal(h.el("strategy-approve").disabled, false);});
  await check("one central approval saves decision separately from Continue", async () => {const h = setup(answer("harmony")); h.fetchImpl = async () => {const value = answer("harmony"); value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = null; return {ok: true, json: async () => value};}; await h.call("decideStrategy", "approve"); assert.equal(h.requests.length, 1); assert.equal(JSON.parse(h.requests[0].options.body).action, "approve"); assert.equal(h.requests.some(request => request.url.includes("continue")), false);});
  await check("stale save keeps exact draft and disables further decisions", async () => {const h = setup(), draft = JSON.stringify(proposal("harmony")); h.state.strategyDraftText = draft; h.fetchImpl = async () => ({ok: false, json: async () => ({error: "Stale strategy review"})}); await h.call("decideStrategy", "revise"); assert.equal(h.state.strategyDraftText, draft); assert.equal(h.state.stale, true); assert.equal(h.el("strategy-approve").disabled, true);});
  await check("completed review locks every typed batch and PC control", () => {const value = answer("harmony", true); value.run.status = "complete"; value.run.stage = "complete"; value.run.review_node = null; const h = setup(value); assert(h.state.strategyControls.length >= 10); assert(h.state.strategyControls.every(input => input.disabled)); const before = h.state.strategyDraftText; h.call("chooseBatchDraft"); h.call("choosePCDraft"); assert.equal(h.state.strategyDraftText, before);});
  const report = {schema: "scagentkit.harmony.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(test => test.passed).length, failed: results.filter(test => !test.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n"); process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
