#!/usr/bin/env node
// Actual display helper and app rendering with inert DOM; external requests
// are forbidden. Native-browser behavior is checked separately.
import assert from "node:assert/strict";
import fs from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import vm from "node:vm";
import {fileURLToPath} from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = fs.readFileSync(path.join(root, "static/gene-links.js"), "utf8");
class Element {
  constructor(tag) {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.text = ""; this.listeners = {}; this.classList = {toggle() {}};}
  set textContent(value) {this.text = String(value ?? ""); this.children = [];}
  get textContent() {return this.text + this.children.map(child => child.textContent ?? String(child)).join("");}
  set innerHTML(_) {throw new Error("Gene evidence cannot become HTML source");}
  setAttribute(name, value) {this.attributes[name] = String(value);}
  getAttribute(name) {return this.attributes[name] ?? null;}
  append(...values) {this.children.push(...values);}
  replaceChildren(...values) {this.text = ""; this.children = values;}
  addEventListener(name, fn) {this.listeners[name] = fn;}
}
const elements = new Map(), document = {querySelectorAll() {return [];}, createElement: tag => new Element(tag), createTextNode: text => ({textContent: text}), getElementById(id) {if (!elements.has(id)) elements.set(id, new Element("div")); return elements.get(id);}};
const context = vm.createContext({document, window: {addEventListener() {}}, URLSearchParams, fetch() {throw new Error("Rendering must not fetch external gene information");}});
vm.runInContext(source, context); const api = context.ScGeneCards;
const links = value => [value, ...(value.children || []).flatMap(links)].filter(node => node.tagName === "A");
let passed = 0;
function test(name, action) {action(); passed++; console.log("PASS " + name);}
test("human literal symbol uses the official fixed HTTPS card path", () => {assert.equal(api.destination("TP53", "human"), "https://www.genecards.org/card/TP53"); assert.equal(api.destination("Cd3d", "human"), "https://www.genecards.org/card/Cd3d");});
test("explicit R-supported human aliases remain declarations", () => {for (const value of ["Homo sapiens", "homo_sapiens", "homo-sapiens", "H. sapiens", "h.sapiens", "hsapiens", "9606"]) assert.equal(api.species(value).kind, "human");});
test("mouse without a mapping asset is never uppercased into a human ortholog", () => {for (const species of ["mouse", "Mus musculus", "10090"]) {assert.equal(api.destination("Cd3d", species), null); const node = api.render("Cd3d", species); assert.equal(links(node).length, 0); assert.match(node.textContent, /^Cd3dmouse/); assert.match(api.note(species), /local official mouse mapping is unavailable/); assert.equal(api.lookup("Cd3d", species).status, "mapping_unavailable");}});
test("missing and non-string species have no direct link", () => {for (const species of [null, undefined, "", " ", {}, 9606]) {assert.equal(api.destination("CD3D", species), null); assert.match(api.render("CD3D", species).textContent, /species undeclared/);}});
test("unsupported declarations have no direct link", () => {for (const species of ["rat", "Homo sapiens;mouse", "human<svg onload=never>"]) {assert.equal(api.destination("TP53", species), null); assert.match(api.render("TP53", species).textContent, /other declared species/);}});
test("URL metacharacters encode inside one literal gene path", () => {const gene = "A/B?x=1&y=2#anchor% \"'()!*"; const href = api.destination(gene, "human"), url = new URL(href); assert.equal(url.origin, "https://www.genecards.org"); assert.equal(url.search, ""); assert.equal(url.hash, ""); assert.equal(decodeURIComponent(url.pathname.slice("/card/".length)), gene); assert.match(href, /%2F.*%3F.*%26.*%23.*%25/);});
test("Unicode symbols preserve exact text and encode", () => {const gene = "基因-α"; assert.equal(decodeURIComponent(api.destination(gene, "human").split("/card/")[1]), gene); assert.equal(api.render(gene, "human").children[0].textContent, gene);});
test("abnormal HTML is inert text and fixed-host encoded content", () => {const gene = '<img src=x onerror="never()">'; const node = api.render(gene, "human"), anchor = links(node)[0]; assert.equal(anchor.textContent, gene); assert.match(anchor.getAttribute("href"), /^https:\/\/www\.genecards\.org\/card\/%3Cimg/); assert.equal(node.children.some(value => value.tagName === "IMG"), false);});
test("scheme-looking symbols cannot change the destination host", () => {for (const gene of ["javascript:alert(1)", "https://evil.example/?q=x", "//evil.example"]) assert.equal(new URL(api.destination(gene, "human")).origin, "https://www.genecards.org");});
test("empty, control, path-dot and malformed symbols stay plain", () => {for (const gene of [null, 1, {}, "", " ", "A\nB", "A\u0000B", ".", "..", "\ud800", "A".repeat(201)]) assert.equal(api.destination(gene, "human"), null);});
test("safe new-tab attributes and explicit species are present", () => {const node = api.render("TP53", "human"), anchor = links(node)[0]; assert.equal(anchor.getAttribute("target"), "_blank"); assert.equal(anchor.getAttribute("rel"), "noopener noreferrer"); assert.equal(anchor.getAttribute("referrerpolicy"), "no-referrer"); assert.match(anchor.getAttribute("aria-label"), /human.*entry not verified/); assert.match(node.textContent, /human · GeneCards/);});
test("no hidden mapping or remote call is accepted", () => {assert.equal(api.destination("Cd3d", "mouse", {human: "CD3D"}), null); assert.doesNotMatch(source, /\b(?:fetch|XMLHttpRequest|sendBeacon|window\.open)\s*\(/); api.list(["CD3D", "CD79A"], "human");});
test("gene lists produce independent literal anchors without upload", () => {const list = api.list(["CD3D", "CD79A"], "human"); assert.deepEqual(links(list).map(link => link.getAttribute("data-gene-symbol")), ["CD3D", "CD79A"]); assert.equal(api.list([], "human").textContent, "none");});
test("human notice makes click-only symbol transmission explicit", () => {assert.match(api.note("human"), /only when a gene is clicked.*clicked symbol is sent.*No gene list/s);});
test("both production pages defer helper before application code", () => {for (const name of ["index", "review"]) {const html = fs.readFileSync(path.join(root, "static/" + name + ".html"), "utf8"); assert(html.indexOf('/gene-links.js" defer') < html.indexOf('/' + (name === "index" ? "app" : "review") + '.js" defer')); assert.doesNotMatch(html, /(?:preconnect|dns-prefetch|prefetch).*genecards/i);}});
const app = fs.readFileSync(path.join(root, "static/app.js"), "utf8");
assert.match(app, /\nload\(\);\s*$/);
vm.runInContext(app.replace(/\nload\(\);\s*$/, "\n"), context);
function markerRender(evidence) {vm.runInContext("state.evidence = " + JSON.stringify(evidence) + "; state.clusterId = 'literal'; renderMarkers();", context); const target = document.getElementById("evidence-content"); const result = [...target.children]; target.replaceChildren(); return result;}
const markerEvidence = () => ({clusters: [{id: "literal", markers: [{gene: "CD3D", avgLog2FC: 2, pct1: .7, pct2: .1, pAdj: .02, source: "saved"}]}]});
test("existing workbench markers use explicit saved context", () => {const value = markerEvidence(); value.parameters = {context: {species: "human"}}; const rendered = markerRender(value); assert.equal(rendered.flatMap(links).length, 1); assert.match(rendered.map(value => value.textContent).join(""), /Human GeneCards lookups/);});
test("generic bundle without species does not infer from markers", () => {const rendered = markerRender(markerEvidence()); assert.equal(rendered.flatMap(links).length, 0); assert.match(rendered.map(value => value.textContent).join(""), /Species is undeclared/);});
test("saved mouse workbench without a mapping asset remains inert", () => {const value = markerEvidence(); value.context = {species: "mouse"}; value.clusters[0].markers[0].gene = "Cd3d"; const rendered = markerRender(value); assert.equal(rendered.flatMap(links).length, 0); assert.match(rendered.map(value => value.textContent).join(""), /Cd3dmouse/);});
const reviewContext = vm.createContext({document, window: {location: {origin: "http://127.0.0.1:1", search: ""}, addEventListener() {}}, URLSearchParams});
vm.runInContext(source, reviewContext);
const review = fs.readFileSync(path.join(root, "static/review.js"), "utf8");
assert.match(review, /\nload\(\);\s*$/);
vm.runInContext(review.replace(/\nload\(\);\s*$/, "\n"), reviewContext);
test("central review marker table uses only run context species", () => {vm.runInContext('state.view = {run: {context: {species: "human"}}}; state.markerMode = "all"; renderMarkers({supplied_marker_stats: [{gene: "CD3D", avgLog2FC: 1, pct1: .6, pct2: .1, pAdj: .02, source: "mouse reference cannot override human context"}]});', reviewContext); const markers = document.getElementById("annotation-markers"); assert.equal(links(markers).length, 1); assert.match(markers.textContent, /human · GeneCards/);});
test("central review missing species disables links despite human-like genes", () => {vm.runInContext('state.view = {run: {context: {}}}; renderMarkers({supplied_marker_stats: [{gene: "CD3D"}]});', reviewContext); assert.equal(links(document.getElementById("annotation-markers")).length, 0); assert.match(document.getElementById("annotation-markers").textContent, /species undeclared/);});
test("central cited-gene paragraph uses the same literal safe helper", () => {vm.runInContext('state.view = {run: {context: {species: "human"}}}; globalThis.citation = geneParagraph("Cited genes: ", ["CD3D", "CD79A"]);', reviewContext); assert.equal(links(reviewContext.citation).length, 2); assert.match(reviewContext.citation.textContent, /^Cited genes: /);});

// These invented records exercise schema and ambiguity handling only. They are
// not official biological mappings; actual bundled source checks follow below.
const syntheticMapping = () => ({schema: "scagentkit.mouse-ortholog-map.v1", snapshot_id: "synthetic-contract-fixture.v1", entry_fields: ["mgi_id", "mouse_symbol", "mouse_ncbi_gene_id", "aliases", "human_candidates", "alias_source_id"], candidate_fields: ["human_symbol", "human_ncbi_gene_id", "hgnc_id", "relation", "source_id", "source_line", "source_group_id"], sources: [{id: "synthetic", title: "Synthetic contract fixture; no biological claim", url: "https://example.invalid/synthetic", last_modified: null, fetched_at_utc: "2026-10-05T00:00:00Z", sha256: "a".repeat(64), bytes: 1, license: "Synthetic test fixture"}], entries: [["MGI:1", "Aa", "1", ["SharedAlias", "aA"], [["ONE", "10", "HGNC:10", "one_to_one_ortholog", "synthetic", 1, null]], "synthetic"], ["MGI:2", "Bb", null, ["SharedAlias", "Aa"], [["TWO", "20", null, "homology_group_candidate", "synthetic", 2, null], ["THREE", "30", null, "homology_group_candidate", "synthetic", 3, null]], "synthetic"], ["MGI:3", "Cc", null, [], [], null]], limitations: ["Synthetic fixture; not official gene mappings"]});
function withMapping(mapping, assetSource = null) {
  const result = vm.createContext({document, window: {location: {origin: "http://127.0.0.1:1", search: ""}, addEventListener() {}}, URLSearchParams, fetch() {throw new Error("Gene rendering cannot request information");}});
  if (assetSource !== null) vm.runInContext(assetSource, result);
  else if (mapping !== undefined) vm.runInContext("globalThis.ScMouseOrthologData = " + JSON.stringify(mapping), result);
  vm.runInContext(source, result); return result;
}
const mapped = withMapping(syntheticMapping()), mouseApi = mapped.ScGeneCards;
test("explicit mouse aliases select the local mapping, without species inference", () => {for (const species of ["mouse", "Mus musculus", "mus_musculus", "mus-musculus", "M. musculus", "m.musculus", "mmusculus", "10090"]) {assert.equal(mouseApi.lookup("Aa", species).status, "matched"); assert.equal(mouseApi.destination("Aa", species), null);} for (const species of [undefined, null, "", 10090, "rat", "human"]) assert.equal(mouseApi.lookup("Aa", species).status, "unsupported_species");});
test("exact canonical symbols take priority over another record's official alias", () => {const result = mouseApi.lookup("Aa", "mouse"); assert.equal(result.match_type, "symbol"); assert.deepEqual(Array.from(result.mouse_records, record => record.mgi_id), ["MGI:1"]); assert.equal(result.ambiguous, false);});
test("official aliases are case-sensitive, with no uppercase or whitespace fallback", () => {assert.equal(mouseApi.lookup("aA", "mouse").match_type, "alias"); for (const gene of ["AA", "aa", " Aa", "Aa ", "sharedalias"]) assert.equal(mouseApi.lookup(gene, "mouse").status, "unmapped");});
test("ambiguous official alias keeps every mouse record and every human candidate", () => {const result = mouseApi.lookup("SharedAlias", "mouse"), node = mouseApi.render("SharedAlias", "mouse"); assert.equal(result.match_type, "alias"); assert.equal(result.ambiguous, true); assert.deepEqual(Array.from(result.mouse_records, record => record.mgi_id), ["MGI:1", "MGI:2"]); assert.equal(links(node).length, 5); assert.match(node.textContent, /multiple candidates retained/); assert.match(node.textContent, /Human TWO.*homology-group candidate/); assert.match(node.textContent, /Human THREE.*homology-group candidate/);});
test("mouse MGI and human links have distinct fixed hosts and typed destinations", () => {const anchors = links(mouseApi.render("Aa", "mouse")); assert.equal(anchors.length, 2); assert.equal(anchors[0].getAttribute("href"), "https://www.informatics.jax.org/accession/MGI%3A1"); assert.equal(anchors[0].getAttribute("data-gene-lookup-kind"), "mgi"); assert.equal(anchors[1].getAttribute("href"), "https://www.genecards.org/card/ONE"); assert.equal(anchors[1].getAttribute("data-ortholog-relation"), "one_to_one_ortholog"); assert.match(anchors[1].textContent, /recorded one-to-one ortholog/); for (const anchor of anchors) {assert.equal(anchor.getAttribute("target"), "_blank"); assert.equal(anchor.getAttribute("rel"), "noopener noreferrer"); assert.equal(anchor.getAttribute("referrerpolicy"), "no-referrer"); assert.match(anchor.getAttribute("aria-label"), /external entry not verified/);}});
test("homology-group relation never becomes a verified pair or a selected ortholog", () => {const result = mouseApi.lookup("Bb", "mouse"), node = mouseApi.render("Bb", "mouse"); assert.equal(result.ambiguous, true); assert.equal(result.mouse_records[0].human_candidates[0].source_group_id, null); assert.equal(links(node).length, 3); assert.equal(links(node).filter(anchor => anchor.getAttribute("data-ortholog-relation") === "one_to_one_ortholog").length, 0); assert.doesNotMatch(node.textContent, /recorded one-to-one/);});
test("a mouse record without human candidates still offers its own MGI record", () => {const node = mouseApi.render("Cc", "mouse"); assert.equal(links(node).length, 1); assert.match(node.textContent, /No human candidate supplied in this snapshot/);});
test("unmatched symbol and invalid symbol have distinct explanations", () => {assert.equal(mouseApi.lookup("UnknownGene", "mouse").status, "unmapped"); assert.match(mouseApi.render("UnknownGene", "mouse").textContent, /no exact symbol or official alias.*no ortholog absence inferred/); for (const gene of [null, {}, 1, "", " ", "A\nB", "\ud800", ".", "..", "A".repeat(201)]) {assert.equal(mouseApi.lookup(gene, "mouse").status, "invalid_symbol"); assert.equal(links(mouseApi.render(gene, "mouse")).length, 0);}});
test("prototype-named symbols remain unmapped without inherited-object lookup", () => {for (const gene of ["__proto__", "constructor", "toString", "hasOwnProperty"]) {assert.equal(mouseApi.lookup(gene, "mouse").status, "unmapped"); assert.equal(links(mouseApi.render(gene, "mouse")).length, 0);}});
test("mapping results and provenance cannot be mutated into later links", () => {const result = mouseApi.lookup("Aa", "mouse"), info = mouseApi.mappingInfo(); assert(Object.isFrozen(result)); assert(Object.isFrozen(result.mouse_records)); assert(Object.isFrozen(result.mouse_records[0].human_candidates[0])); assert(Object.isFrozen(info.sources[0])); assert.throws(() => {result.mouse_records[0].human_candidates[0].human_symbol = "MUTATED";}, {name: "TypeError"}); assert.throws(() => {info.sources.push({});}, {name: "TypeError"}); assert.equal(links(mouseApi.render("Aa", "mouse"))[1].getAttribute("href"), "https://www.genecards.org/card/ONE");});
test("missing and malformed snapshots fail closed independently of human links", () => {for (const value of [undefined, null, {}, {...syntheticMapping(), schema: "unknown"}, {...syntheticMapping(), entry_fields: ["wrong"]}]) {const api = withMapping(value).ScGeneCards; assert.notEqual(api.mappingInfo().status, "available"); assert.equal(links(api.render("Aa", "mouse")).length, 0); assert.equal(api.destination("TP53", "human"), "https://www.genecards.org/card/TP53");}});
test("bad IDs, relations, provenance and row shapes invalidate the entire mapping", () => {const mutations = [data => {data.entries[1][0] = "MGI:1";}, data => {data.entries[1][0] = "https://evil.example";}, data => {data.entries[1][2] = "not-an-id";}, data => {data.entries[1][4][0][1] = "-1";}, data => {data.entries[1][4][0][2] = "HGNC:0";}, data => {data.entries[1][4][0][3] = "guessed_ortholog";}, data => {data.entries[1][4][0][4] = "missing-source";}, data => {data.entries[1][4][0][5] = 0;}, data => {data.entries[1][5] = null;}, data => {data.entries[1].pop();}, data => {data.sources[0].sha256 = "missing-hash";}]; for (const mutate of mutations) {const data = syntheticMapping(); mutate(data); const api = withMapping(data).ScGeneCards; assert.equal(api.mappingInfo().status, "invalid"); assert.equal(links(api.render("Aa", "mouse")).length, 0);}});
test("literal hostile mapped labels cannot become HTML or escape fixed URL paths", () => {const data = syntheticMapping(), hostile = '<svg onload="never()">', human = "A/B?x=1&y=2#frag% '\"()!*"; data.entries[0][1] = hostile; data.entries[0][4][0][0] = human; const api = withMapping(data).ScGeneCards, node = api.render(hostile, "mouse"), anchor = links(node)[1], url = new URL(anchor.getAttribute("href")); assert(node.textContent.includes(hostile)); assert.equal(node.children.some(value => value.tagName === "SVG"), false); assert.equal(url.origin, "https://www.genecards.org"); assert.equal(url.search, ""); assert.equal(url.hash, ""); assert.equal(decodeURIComponent(url.pathname.slice("/card/".length)), human);});
test("notices distinguish source snapshot, alias coverage and click-only transmission", () => {const note = mouseApi.note("mouse"); assert.match(note, /synthetic-contract-fixture.v1.*3 mouse records.*aliases for 2 records only/); assert.match(note, /homology-group candidates.*recorded one-to-one orthologs/); assert.match(note, /human entries.*mouse ortholog information/); assert.match(note, /only when clicked.*one mapped symbol or MGI ID.*No gene list/s); assert.equal(mouseApi.mappingInfo().sources[0].sha256, "a".repeat(64));});
test("mouse links in central review preserve literal cited and marker symbols", () => {vm.runInContext(review.replace(/\nload\(\);\s*$/, "\n"), mapped); vm.runInContext('state.view = {run: {context: {species: "mouse"}}}; state.markerMode = "all"; renderMarkers({supplied_marker_stats: [{gene:"SharedAlias", source:{species:"human"}}]}); globalThis.aliasCitation = geneParagraph("Cited genes: ", ["SharedAlias"]);', mapped); assert.equal(links(document.getElementById("annotation-markers")).length, 5); assert.match(mapped.aliasCitation.textContent, /^Cited genes: SharedAlias/); assert.equal(links(mapped.aliasCitation).length, 5);});

const mappingSource = fs.readFileSync(path.join(root, "static/ortholog-map.js"), "utf8"), official = withMapping(undefined, mappingSource), officialApi = official.ScGeneCards;
const mappingSha256 = crypto.createHash("sha256").update(mappingSource).digest("hex"), data = official.ScMouseOrthologData;
test("the entire pinned official snapshot loads with explicit source and alias coverage", () => {assert.equal(mappingSha256, "64a75b87f51acc7080470da3a8806aa3146855bb4f5b5983a835086e7d7a054c"); const info = officialApi.mappingInfo(); assert.equal(info.status, "available"); assert.equal(info.snapshot_id, "mgi-mouse-human-2026-10-05.v1"); assert.equal(info.entries, 20183); assert.equal(info.alias_entries, 3); assert.equal(info.sources.length, 5); assert.equal(info.sources.find(source => source.id === "mgi_protein_coding").sha256, "2bc350fc189dfd68e2caecebaff0f9a3db18959956e5bb3008981635f87f68c9"); assert.equal(info.sources.find(source => source.id === "mgi_hmd").sha256, "3caceb612e6c9054a714044589fb3dd960d84f24bff5cdf0bab2b4381358c0a7"); assert(info.limitations.some(text => /only Ptprc, Lyz2 and Adh1/i.test(text)));});
test("every official canonical symbol remains canonical and all distinct pairs retain relation provenance", () => {let candidates = 0, oneToOne = 0, groups = 0, multi = 0, aliases = 0; for (const row of data.entries) {const result = officialApi.lookup(row[1], "mouse"); assert.equal(result.status, "matched"); assert.equal(result.match_type, "symbol"); const record = result.mouse_records.find(value => value.mgi_id === row[0]); assert(record); assert.equal(record.human_candidates.length, row[4].length); aliases += record.aliases.length; candidates += record.human_candidates.length; if (record.human_candidates.length > 1) multi++; for (const candidate of record.human_candidates) {if (candidate.relation === "one_to_one_ortholog") {oneToOne++; assert.equal(candidate.source_id, "mgi_protein_coding");} else {groups++; assert.equal(candidate.relation, "homology_group_candidate"); assert.equal(candidate.source_id, "mgi_hmd");}}} assert.deepEqual({candidates, oneToOne, groups, multi, aliases}, {candidates: 28880, oneToOne: 16536, groups: 12344, multi: 1754, aliases: 20});});
test("official Cd3d maps to CD3D as a recorded one-to-one ortholog with its own MGI link", () => {const result = officialApi.lookup("Cd3d", "Mus musculus"), record = result.mouse_records[0], anchors = links(officialApi.render("Cd3d", "mouse")); assert.equal(record.mgi_id, "MGI:88331"); assert.equal(record.human_candidates[0].human_symbol, "CD3D"); assert.equal(record.human_candidates[0].hgnc_id, "HGNC:1673"); assert.equal(record.human_candidates[0].relation, "one_to_one_ortholog"); assert.equal(anchors[0].getAttribute("href"), "https://www.informatics.jax.org/accession/MGI%3A88331"); assert.equal(anchors[1].getAttribute("href"), "https://www.genecards.org/card/CD3D"); assert.equal(officialApi.destination("Cd3d", "mouse"), null);});
test("official Lyz2 to LYZ stays a homology-group candidate and accepts Lysm but not LysM", () => {const canonical = officialApi.lookup("Lyz2", "mouse"), alias = officialApi.lookup("Lysm", "mouse"), candidate = canonical.mouse_records[0].human_candidates[0]; assert.equal(canonical.match_type, "symbol"); assert.equal(alias.match_type, "alias"); assert.equal(alias.mouse_records[0].mgi_id, "MGI:96897"); assert.equal(candidate.human_symbol, "LYZ"); assert.equal(candidate.relation, "homology_group_candidate"); assert.equal(candidate.source_line, 13814); assert.equal(candidate.source_group_id, "52259352"); assert.equal(officialApi.lookup("LysM", "mouse").status, "unmapped"); assert.match(officialApi.render("Lysm", "mouse").textContent, /Lysmmouse.*official alias.*Mouse Lyz2.*Human LYZ.*homology-group candidate/);});
test("official Adh1 retains all three human candidates and the independently recorded group ID", () => {const result = officialApi.lookup("Adh1", "mouse"), record = result.mouse_records[0], anchors = links(officialApi.render("Adh1", "mouse")); assert.equal(result.ambiguous, true); assert.equal(anchors.length, 4); assert.deepEqual(Array.from(record.human_candidates, candidate => candidate.human_symbol), ["ADH1A", "ADH1B", "ADH1C"]); for (const candidate of record.human_candidates) {assert.equal(candidate.relation, "homology_group_candidate"); assert.equal(candidate.source_group_id, "52263919"); assert.equal(candidate.source_id, "mgi_hmd");} assert.equal(officialApi.lookup("Adh-1", "mouse").match_type, "alias"); assert.equal(officialApi.lookup("ADH1", "mouse").status, "unmapped");});
test("official H2-Ab1 retains two group candidates without an invented group ID", () => {const result = officialApi.lookup("H2-Ab1", "mouse"), record = result.mouse_records[0]; assert.equal(result.ambiguous, true); assert.equal(record.mgi_id, "MGI:103070"); assert.deepEqual(Array.from(record.human_candidates, candidate => candidate.human_symbol), ["HLA-DQB1", "HLA-DQB2"]); for (const candidate of record.human_candidates) {assert.equal(candidate.relation, "homology_group_candidate"); assert.equal(candidate.source_group_id, null);} assert.equal(links(officialApi.render("H2-Ab1", "mouse")).length, 3);});
test("official Ptprc canonical and recorded aliases preserve exact input and human relation", () => {for (const gene of ["Ptprc", "B220", "CD45"]) {const result = officialApi.lookup(gene, "mouse"), record = result.mouse_records[0]; assert.equal(result.match_type, gene === "Ptprc" ? "symbol" : "alias"); assert.equal(result.query, gene); assert.equal(record.mouse_symbol, "Ptprc"); assert.equal(record.mgi_id, "MGI:97810"); assert.equal(record.human_candidates[0].human_symbol, "PTPRC"); assert.equal(record.human_candidates[0].relation, "one_to_one_ortholog"); assert(officialApi.render(gene, "mouse").textContent.startsWith(gene));} assert.equal(officialApi.lookup("ptprc", "mouse").status, "unmapped");});
test("conflicting official Slc35f3 mouse NCBI IDs remain unresolved and never select an ID", () => {const record = officialApi.lookup("Slc35f3", "mouse").mouse_records[0]; assert.equal(record.mgi_id, "MGI:2444426"); assert.equal(record.mouse_ncbi_gene_id, null); assert.equal(record.human_candidates[0].human_symbol, "SLC35F3"); assert(officialApi.mappingInfo().limitations.some(text => /Slc35f3.*two mouse NCBI IDs|two mouse NCBI IDs.*Slc35f3/.test(text)));});
test("official mapping does not infer undeclared species, case conversions or unsupported aliases", () => {for (const species of [undefined, null, "", "rat"]) {assert.equal(officialApi.lookup("Cd3d", species).status, "unsupported_species"); assert.equal(links(officialApi.render("Cd3d", species)).length, 0);} for (const symbol of ["CD3D", "cd3d", " Cd3d", "Cd3d ", "FeatureNotInSnapshot", "__proto__"]) {assert.equal(officialApi.lookup(symbol, "mouse").status, "unmapped"); assert.equal(links(officialApi.render(symbol, "mouse")).length, 0);}});
test("loading official mouse data leaves human literal links and safe encoding unchanged", () => {for (const gene of ["Cd3d", "CD3D", "Lysm", "A/B?x=1&y=2#frag% '\"()!*", '<svg onload="never()">']) {assert.equal(officialApi.destination(gene, "human"), api.destination(gene, "human")); const node = officialApi.render(gene, "human"); assert.equal(links(node).length, 1); assert.equal(links(node)[0].textContent, gene);} assert.doesNotMatch(mappingSource, /\b(?:fetch|XMLHttpRequest|sendBeacon|window\.open)\s*\(/);});
test("loading the official snapshot leaves the original data bytes and provenance unchanged", () => {const before = JSON.stringify(data); officialApi.render("Adh1", "mouse"); officialApi.list(["Lysm", "H2-Ab1"], "mouse"); assert.equal(JSON.stringify(data), before); assert.match(officialApi.note("mouse"), /20183 mouse records.*aliases for 3 records only.*one mapped symbol or MGI ID/s);});
console.log(JSON.stringify({schema: "scagentkit.gene-links.dom-tests.v1", passed, failed: 0, externalRequests: 0, RProcesses: 0, paidAPICalls: 0, officialSnapshot: {sha256: mappingSha256, snapshot_id: officialApi.mappingInfo().snapshot_id, entries: officialApi.mappingInfo().entries, alias_entries: officialApi.mappingInfo().alias_entries}}));
