#!/usr/bin/env node
// Executes the actual unified workbench and pure display helpers with an inert
// DOM. All HTTP replies are declared fixtures; no network, R or provider runs.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {fileURLToPath} from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), sha = value => createHash("sha256").update(value).digest("hex"), clone = value => JSON.parse(JSON.stringify(value));
const html = fs.readFileSync(path.join(root, "static/workbench.html"), "utf8"), source = fs.readFileSync(path.join(root, "static/workbench.js"), "utf8");
const modules = ["ortholog-map.js", "gene-links.js", "evidence-display.js"].map(name => [name, fs.readFileSync(path.join(root, "static", name), "utf8")]);
class Element {
  constructor(tag) {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.style = {}; this._text = ""; this.listeners = {}; this.hidden = false; this.disabled = false; this.checked = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  set innerHTML(_) {throw new Error("Saved facts must never become HTML");}
  append(...children) {this.children.push(...children);}
  replaceChildren(...children) {this._text = ""; this.children = children;}
  setAttribute(name, value) {this.attributes[name] = String(value);}
  getAttribute(name) {return this.attributes[name] ?? null;}
  removeAttribute(name) {delete this.attributes[name];}
  addEventListener(name, callback) {(this.listeners[name] ||= []).push(callback);}
}
const descend = value => [value, ...(value.children || []).flatMap(descend)];
const h64 = char => char.repeat(64);
function events(count = 4, id = "parent") {let previous = h64("0"); return Array.from({length: count}, (_, index) => {const event = {sequence: index + 1, action: ["created", "processed_stage_reused", "approved", "finalized"][index % 4], created_at: "2026-10-05T12:00:00Z", details: {reviewer: "Public mock analyst", reason: "Explicit saved fixture reason"}, previous_hash: previous, hash: sha(id + "-event-" + index)}; previous = event.hash; return event;});}
function scopes() {return {schema: "scagentkit.run-scopes.workbench.v1", workspace_enabled: true, parent: {project_id: "parent", input_hash: h64("a"), revision: 4, ready: true, frozen: true, status: "complete"}, children: [{project_id: "child-A", input_hash: h64("b"), revision: 4, status: "complete", stage: "complete", applications: [{application_id: "apply-A", active: true, column: "sc_subtype", output_path: "integration/derived-parent.rds"}]}, {project_id: "child & B", revision: 4, status: "awaiting_review", stage: "strategy_propose", applications: []}]};}
function view(id = "parent", options = {}) {
  const inputHash = h64(id === "parent" ? "a" : "b"), historyEvents = events(4, id), head = historyEvents.at(-1).hash, child = id !== "parent";
  const markers = [{clusterId: "01", gene: "CD3D", avgLog2FC: 2.1234567891234, pct1: .7, pct2: .1, pctDiff: .6, pAdj: .002, source: "saved public fixture"}, {clusterId: "1", gene: "CD79A", avgLog2FC: 1.7, pct1: .8, pct2: .2, pAdj: .003, source: "saved public fixture"}];
  const evidence = {projectId: "bundle-" + id, bundleDigest: h64("e"), sourceFingerprint: h64("c"), dataset: {retainedCells: 3, clusterCount: 2}, embeddingName: "UMAP", clusters: [{id: "01", cellCount: 2, cellIds: ["cell:A", "cell:B"], markers: [markers[0]], sourceAnnotations: [{value: "old T", count: 2}]}, {id: "1", cellCount: 1, cellIds: ["cell:C"], markers: [markers[1]]}], umap: [{cellId: "cell:A", clusterId: "01", x: 1.2, y: 3}, {cellId: "cell:B", clusterId: "01", x: 2.4, y: -1.7}, {cellId: "cell:C", clusterId: "1", x: -.8, y: 1.1}]};
  const proposal = {schema: "scagentkit.strategy.v1", rationale: "Saved bounded child strategy", risks: ["Biology remains unresolved"], qc: {filters: [], rationale: "Retain exact selection"}, analysis: {normalization_method: "LogNormalize", nfeatures: 100, npcs: 12}, pcs: {method: "fixed", ndim: 10}, batch: {method: "none", reason: "Condition is not a batch"}, clustering: {resolution: .4}, umap: {run: true}};
  const strategyReview = child ? {details: {canonical_proposal: proposal, source: {kind: "mock"}, qc_impact: {expected_retained_cells: 3}, applicability: {executable: true}}, lifecycle: {status: "executed"}} : null;
  const annotationReview = {details: {annotations: evidence.clusters.map(cluster => ({clusterId: cluster.id, cell_count: cluster.cellCount, proposal: {label: "Unknown", confidence: "low", rationale: "This public mock fixture does not establish cell identities", markers: cluster.markers.map(row => row.gene)}, supplied_marker_stats: cluster.markers, local_reference: {status: "not_supplied"}})), source: {kind: "mock"}}, lifecycle: {executed: true}};
  const run = {schema: "scagentkit.run.v1", project_id: id, input_hash: inputHash, config_hash: h64("b"), implementation_hash: h64("c"), revision: 4, history_head: head, status: options.pending ? "awaiting_review" : "complete", stage: options.pending ? "strategy_propose" : "complete", context: {species: options.species || "human", tissue: "Public fixture", notes: "Study-specific notes", columns: {condition: "Ca_Ctrl"}}, nodes: {qc_evidence: "EXECUTED", analysis: "EXECUTED", annotation_apply: "EXECUTED"}, output: {seurat: "outputs/seurat.rds", bundle: "/fixed/bundle"}, annotation_review: annotationReview, strategy_review: strategyReview};
  return {schema: "scagentkit.workbench.v1", readonly: true, project: {project_id: id, input_hash: inputHash, revision: 4, history_head: head, scope: child ? "child" : "parent", frozen: !child}, run,
    source: {start_stage: child ? "qc" : "processed", processed_reason: child ? null : "Verified processed public object; keep original PCA and UMAP", source: {type: "Seurat", path: "/public/fixture.rds", rds_sha256: h64("d")}}, provider: {name: options.provider || "mock", model: options.provider === "deepseek" ? "deepseek-flash" : "simulated-v1", external: options.provider === "deepseek"},
    history: {schema: "scagentkit.run-history.v1", events: historyEvents, head, total_events: 4, provided_events: 4, truncated: false, authority: "state.rds"},
    qc: child ? {status: "saved", summary: {cells: 3, features: 500, assay: "RNA", counts_layer: "counts", groups: [{group_id: "g1", selector: {sample: "s1", capture: "01"}, cells: 3, metrics: {nFeature: {median: 250, p05: 180, p95: 280}}}]}} : {status: "processed_reused", reason: "Verified processed public object; keep original PCA and UMAP", summary: null, preview: null},
    strategy: {status: strategyReview ? "saved" : "not_recorded", review: strategyReview}, analysis: {status: child ? "executed" : "processed_reused", foundation_executed: child, parameters: {normalization_method: "LogNormalize"}}, annotation: {status: "saved", review: annotationReview},
    evidence: options.noEvidence ? null : evidence, evidence_complete: !options.noEvidence, evidence_kind: options.noEvidence ? "unavailable" : "final_output_bundle",
    detail_projection: "Scientific aggregate facts; private per-cell detail fields excluded.",
    binding: {project_id: id, bundle_cell_scope_hash: h64("d"), state_sha256: h64("d"), input_hash: inputHash, revision: 4, history_head: head, evidence_project_id: evidence.projectId, bundle_digest: h64("e"), source_fingerprint: h64("c"), workspace_fingerprint: h64("f"), stage_checkpoint_records: null, stage_records_hash: null, stage_scope_hash: null}, outputs: {artifacts: [{path: "outputs/seurat.rds", sha256: h64("a")}], scientific_result: "Biology unvalidated"}, children: scopes().children,
    navigation: {review_url: "https://foreign.example/review", subclusters_url: "https://foreign.example/subclusters", can_review: !child, can_revise: child, can_undo: child, frozen: !child}};
}
function savedStage(id = "parent") {
  const value = view(id), run = value.run, binding = value.binding;
  run.status = "awaiting_review"; run.stage = "annotation_propose"; run.output = null; value.project.frozen = false;
  value.evidence_kind = "saved_analysis_checkpoint"; value.evidence.projectId = id; binding.evidence_project_id = id;
  binding.stage_checkpoint_records = Object.fromEntries(["analysis", "markers", "annotation_evidence"].map((name, i) => [name, {path: "checkpoints/" + name + "-" + h64(String(i + 1)) + ".rds", sha256: h64(String(i + 4))}]));
  binding.stage_records_hash = h64("a"); binding.stage_scope_hash = h64("b");
  value.evidence.parameters = {savedStageSnapshot: {stateSHA: binding.state_sha256, inputHash: run.input_hash, configHash: run.config_hash, implementationHash: run.implementation_hash, revision: run.revision, historyHead: run.history_head, scopeHash: binding.stage_scope_hash, bundleScopeHash: binding.bundle_cell_scope_hash, records: clone(binding.stage_checkpoint_records)}};
  for (const cluster of value.evidence.clusters) delete cluster.sourceAnnotations;
  value.outputs = {artifacts: []}; return value;
}
function harness(search = "", hash = "") {
  const nodes = new Map(); for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(nodes.has(match[2]), false, "Duplicate production HTML ID"); const node = new Element(match[1]); node.hidden = /\bhidden\b/.test(match[0]); node.checked = /\bchecked\b/.test(match[0]); nodes.set(match[2], node);}
  for (const section of ["overview", "qc", "strategy", "analysis", "annotation", "children", "outputs", "history"]) {const link = new Element("a"); link.setAttribute("data-section", section); link.setAttribute("href", "#" + section); nodes.get("wb-navigation").append(link);}
  for (const [name, section] of [["overview", "overview"], ["figures", "analysis"], ["results", "outputs"]]) {const link = new Element("a"); link.setAttribute("data-view", name); link.setAttribute("href", "#" + section); nodes.get("wb-primary-navigation").append(link);}
  const h = {requests: [], handler: null, nodes}, document = {getElementById(id) {assert(nodes.has(id), "Missing production HTML ID " + id); return nodes.get(id);}, createElement: tag => new Element(tag), createElementNS: (_, tag) => new Element(tag), createTextNode: text => {const node = new Element("#text"); node.textContent = text; return node;}};
  const listeners = {}, window = {location: {search, hash}, addEventListener(name, fn) {listeners[name] = fn;}};
  const context = vm.createContext({document, window, URLSearchParams, async fetch(url, options = {}) {h.requests.push({url, options}); assert(h.handler, "No network allowed"); return h.handler(url, options);}});
  for (const [name, code] of modules) vm.runInContext(code, context, {filename: name});
  assert.match(source, /\nwbLoad\(\);\s*$/); vm.runInContext(source.replace(/\nwbLoad\(\);\s*$/, "\n"), context);
  h.state = vm.runInContext("wbState", context); h.call = (name, ...args) => vm.runInContext(name, context)(...args); h.el = id => nodes.get(id); h.window = window; h.listeners = listeners;
  h.wire = (id = "parent", value = view(id)) => {h.handler = async url => ({ok: true, json: async () => clone(url === "/api/run-review/scopes" ? scopes() : value)});};
  return h;
}
const results = [];
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.stack});}}
await check("first entry resolves parent then reads exact scoped snapshot by GET only", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.deepEqual(h.requests.map(request => request.url), ["/api/run-review/scopes", "/api/run-review/workbench?project_id=parent"]); assert.equal(h.requests[1].options.headers["X-ScAgentKit-Run-Project"], "parent"); assert(h.requests.every(request => request.options.method === "GET"));});
await check("candidate workflow navigation follows the verified child and performs no mutation", async () => {const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A"); await h.call("wbLoad"); assert.equal(h.el("wb-header-review").getAttribute("href"), "/review?child_id=child-A&project_id=child-A"); assert.equal(h.el("wb-header-scope").getAttribute("href"), "/subclusters?child_id=child-A&project_id=child-A"); assert.equal(h.el("wb-header-review").hidden, false); assert.equal(h.requests.every(request => request.options.method === "GET"), true);});
await check("candidate navigation disappears after an unverified saved response", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); const invalid = view(); invalid.binding.input_hash = h64("0"); h.wire("parent", invalid); await h.call("wbLoad"); assert.equal(h.el("wb-header-review").hidden, true); assert.equal(h.el("wb-header-scope").hidden, true);});
await check("registered child and encoded literal ID keep per-tab scope", async () => {const h = harness("?child_id=child+%26+B&project_id=child+%26+B"); h.wire("child & B"); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.equal(h.state.projectId, "child & B"); assert.equal(h.el("wb-review").getAttribute("href"), "/review?child_id=child+%26+B&project_id=child+%26+B");});
await check("two tabs render independent parent and child snapshots", async () => {const a = harness("?project_id=parent"), b = harness("?child_id=child-A&project_id=child-A"); a.wire(); b.wire("child-A"); await Promise.all([a.call("wbLoad"), b.call("wbLoad")]); assert.equal(a.state.projectId, "parent"); assert.equal(b.state.projectId, "child-A"); assert.notEqual(a.el("wb-title").textContent, b.el("wb-title").textContent);});
for (const query of ["?project_id=", "?child_id=", "?project_id=parent&project_id=parent", "?child_id=child-A&child_id=child-A", "?project_id=parent&child_id=child-A", "?project_dir=/private", "?path=/private", "?child_id=%00"]) await check("invalid scope rejects before any read: " + query, async () => {const h = harness(query); h.wire(); await h.call("wbLoad"); assert.equal(h.state.failed, true); assert.equal(h.requests.length, 0); assert.equal(h.state.view, null);});
await check("unknown child and parent masquerading as child have no parent fallback", async () => {for (const query of ["?child_id=foreign&project_id=foreign", "?child_id=parent&project_id=parent"]) {const h = harness(query); h.wire(); await h.call("wbLoad"); assert.equal(h.requests.length, 1); assert.equal(h.state.failed, true);}});
for (const [name, mutate] of [["foreign binding project", value => value.binding.project_id = "foreign"], ["missing bundle cell hash", value => delete value.binding.bundle_cell_scope_hash], ["invalid bundle cell hash", value => value.binding.bundle_cell_scope_hash = "bad"], ["foreign run", value => value.run.project_id = "foreign"], ["foreign project", value => value.project.project_id = "foreign"], ["changed input", value => value.binding.input_hash = h64("0")], ["changed revision", value => value.binding.revision = 5], ["unverified state hash", value => value.binding.state_sha256 = "bad"], ["mutation authority", value => value.readonly = false], ["foreign role", value => value.project.scope = "child"], ["history head mismatch", value => value.history.head = h64("0")], ["history link mismatch", value => value.history.events[1].previous_hash = h64("0")], ["history count mismatch", value => value.history.total_events = 20], ["bundle owner mismatch", value => value.evidence.projectId = "foreign"], ["bundle digest mismatch", value => value.evidence.bundleDigest = h64("0")], ["source fingerprint mismatch", value => value.evidence.sourceFingerprint = h64("0")], ["partial output snapshot", value => value.evidence_complete = false], ["duplicate cell", value => value.evidence.clusters[1].cellIds[0] = "cell:A"], ["foreign marker", value => value.evidence.clusters[0].markers[0].clusterId = "1"], ["foreign embedding point", value => value.evidence.umap[0].cellId = "foreign"], ["nonfinite coordinate", value => value.evidence.umap[0].x = "Infinity"], ["unregistered child", value => value.children.push({project_id: "foreign"})]]) await check("mismatched saved facts fail closed: " + name, async () => {const h = harness(), value = view(); mutate(value); h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, true); assert.equal(h.state.view, null); assert.equal(h.el("wb-review").hidden, true); assert.equal(h.el("wb-metrics").children.length, 0);});
await check("bundle display name can differ from coordinator ID only via explicit binding", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.equal(h.state.view.evidence.projectId, "bundle-parent"); assert.equal(h.state.view.project.project_id, "parent");});
await check("changing an existing page URL cannot reuse project authority", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); h.window.location.search = "?child_id=child-A&project_id=child-A"; await h.call("wbLoad"); assert.equal(h.requests.length, 2); assert.equal(h.state.failed, true); assert.equal(h.state.view, null);});
await check("completed child next step permits writeback inspection without suggesting another child", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A"); await h.call("wbLoad");
  assert.equal(h.state.failed, false); assert.equal(h.state.child, true);
  assert.match(h.el("wb-next").textContent, /inspect label writeback to the parent/);
  assert.doesNotMatch(h.el("wb-next").textContent, /select cells|create.*child|nested|independent analysis/i);
  assert.equal(h.el("wb-child-action").getAttribute("href"), "/subclusters?child_id=child-A&project_id=child-A");
  assert.equal(h.el("wb-child-action").textContent, "Review writeback");
  assert.equal(h.requests.length, 2); assert(h.requests.every(request => request.options.method === "GET"));
});
await check("completed parent without workspace capability suggests inspection rather than child creation", async () => {
  const h = harness(), registered = scopes(), value = view(); registered.workspace_enabled = false;
  h.handler = async url => ({ok: true, json: async () => clone(url === "/api/run-review/scopes" ? registered : value)}); await h.call("wbLoad");
  assert.equal(h.state.failed, false); assert.equal(h.state.child, false);
  assert.match(h.el("wb-next").textContent, /Explore a cluster and its markers.*inspect the saved labels in Review/);
  assert.doesNotMatch(h.el("wb-next").textContent, /select cells|create.*child|independent analysis|writeback/i);
  assert.equal(h.el("wb-child-action").hidden, true); assert.equal(h.el("wb-header-scope").hidden, true);
  assert.equal(h.requests.length, 2); assert(h.requests.every(request => request.options.method === "GET"));
});
await check("completed ready parent with workspace capability offers exact parent cell selection", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad");
  assert.equal(h.state.failed, false); assert.equal(h.state.child, false);
  assert.equal(h.state.scopes.workspace_enabled, true); assert.equal(h.state.scopes.parent.ready, true);
  assert.match(h.el("wb-next").textContent, /select cells for an independent analysis/);
  assert.equal(h.el("wb-child-action").hidden, false);
  assert.equal(h.el("wb-child-action").getAttribute("href"), "/subclusters?project_id=parent");
  assert.equal(h.el("wb-child-action").textContent, "Select cells");
  assert.equal(h.requests.length, 2); assert(h.requests.every(request => request.options.method === "GET"));
});
await check("all eight sections are local navigation including completed history", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); const count = h.requests.length; for (const section of ["overview", "qc", "strategy", "analysis", "annotation", "children", "outputs", "history"]) {h.call("wbSelectSection", section); assert.equal(h.el("wb-section-" + section).hidden, false);} assert.equal(h.requests.length, count); assert.match(h.el("wb-history-summary").textContent, /4 supplied event headers of 4.*allowlisted.*no edit, approve, retry or resume/s); assert.equal(descend(h.el("wb-history-content")).some(node => ["BUTTON", "INPUT", "FORM"].includes(node.tagName)), false);});
const flowNode = (h, name) => h.el("wb-flow").children.find(node => node.getAttribute("data-flow-node") === name);
await check("chart-first overview reuses one analysis DOM and keeps three entries local", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(h.el("wb-section-overview").hidden, false); assert.equal(h.el("wb-section-analysis").hidden, false); assert.equal([...html.matchAll(/\sid="wb-umap"/g)].length, 1); assert(html.indexOf('id="wb-section-analysis"') < html.indexOf('id="wb-section-overview"')); const count = h.requests.length; h.call("wbSelectSection", "qc"); assert.equal(h.el("wb-section-analysis").hidden, true); h.call("wbSelectSection", "overview"); assert.equal(h.el("wb-section-analysis").hidden, false); assert.equal(h.requests.length, count);});
await check("selected evidence is exact literal scope and preserves all marker statistics", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.match(h.el("wb-selection").textContent, /Cluster 01.*2 cells.*old T.*Unknown.*low/s); assert.match(h.el("wb-marker-preview").textContent, /1 \/ 1 supplied markers.*CD3D.*avg log2FC 2\.12/s); assert.match(h.el("wb-markers").textContent, /2\.1234567891234/); const count = h.requests.length; h.call("wbSelectCluster", "1"); assert.match(h.el("wb-selection").textContent, /Cluster 1.*1 cells/); assert.doesNotMatch(h.el("wb-marker-preview").textContent, /CD3D/); assert.match(h.el("wb-markers").textContent, /CD79A/); assert.equal(h.requests.length, count); assert.equal(descend(h.el("wb-marker-preview")).some(node => node.tagName === "A"), false);});
await check("review risks and QC failure combination stay visible outside technical details", async () => {const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); value.provider.name = "manual"; value.strategy.review.details.canonical_proposal.qc.risks = "A measured risk must remain near the decision"; value.qc.preview.details.canonical_parameters.proposal.remove_if = "all"; h.wire("child-A", value); await h.call("wbLoad"); assert.equal(h.el("wb-risk").hidden, false); assert.match(h.el("wb-risk").textContent, /Manual configuration.*no provider.*measured risk.*provisional/s); assert.match(h.el("wb-parameter-summary").textContent, /ALL 2 rules fail.*projected 40 → 30, 10 unique removals/); assert.equal(h.el("wb-parameter-review").getAttribute("href"), "/review?child_id=child-A&project_id=child-A");});
await check("failed refresh clears new selection, risk and parameter context as well as legacy facts", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); const changed = view(); changed.binding.revision++; h.wire("parent", changed); await h.call("wbLoad"); for (const id of ["wb-selection", "wb-marker-preview", "wb-risk", "wb-risk-details", "wb-parameter-summary"]) assert.equal(h.el(id).textContent, ""); assert.equal(h.el("wb-parameter-review").hidden, true); assert.match(h.el("wb-dataset-title").textContent, /unavailable/);});
await check("three primary views retain all eight secondary anchors and collapsed technical records", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad"); const count = h.requests.length;
  assert.equal(h.el("wb-primary-navigation").children.length, 3);
  assert.match(html, /<details class="wb-secondary-navigation"><summary>All saved evidence/);
  assert.match(html, /<details class="wb-card"><summary>Input diagnostics and raw stage records/);
  assert.match(html, /<details class="wb-card"><summary>Recorded analysis parameters and diagnostics/);
  for (const [viewName, section] of [["overview", "qc"], ["figures", "annotation"], ["results", "history"]]) {h.call("wbSelectSection", section); assert.equal(h.el("wb-primary-navigation").children.find(node => node.getAttribute("data-view") === viewName).getAttribute("aria-current"), "page");}
  for (const link of h.el("wb-primary-navigation").children) {link.listeners.click[0]({preventDefault() {}}); assert.equal(h.el("wb-section-" + link.getAttribute("href").slice(1)).hidden, false);}
  assert.equal(h.requests.length, count);
});
await check("saved workflow has seven scope-bound local links with no scientific actions", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad"); const count = h.requests.length;
  assert.deepEqual(h.el("wb-flow").children.map(node => node.getAttribute("data-flow-node")), ["input", "qc", "decision", "foundation", "markers", "annotation", "output"]);
  for (const item of h.el("wb-flow").children) {const link = item.children[0]; assert.match(link.getAttribute("href"), /^#(?:overview|qc|strategy|analysis|annotation|outputs)$/); assert(link.getAttribute("aria-label")); link.listeners.click[0]({preventDefault() {}}); assert.equal(h.el("wb-section-" + link.getAttribute("href").slice(1)).hidden, false);}
  assert.equal(h.requests.length, count); assert.equal(descend(h.el("wb-flow")).some(node => ["BUTTON", "INPUT", "FORM"].includes(node.tagName)), false);
});
function groupedQC() {
  const value = view("child-A", {noEvidence: true}); value.run.status = "awaiting_review"; value.run.stage = "strategy_propose"; value.run.output = null; value.run.completed = ["qc_evidence"]; value.run.nodes = {qc_evidence: "EXECUTED", strategy_propose: "PROPOSED"}; value.run.diagnostics = {cell_count: 40, feature_count: 500};
  const proposal = {schema: "scagentkit.qc.rules.v1", rationale: "Different measured capture cohorts", risks: [], remove_if: "any", rules: [{op: "range", metric: "nFeature", min: 200, group: {sample: "S1", capture: "01"}}, {op: "range", metric: "nFeature", min: 400, group: {sample: "S2", capture: "02"}}]};
  const details = {canonical_parameters: {proposal}, retention: {before: 40, retained: 30, removed: 10, groups: [{group_id: "g1", selector: {sample: "S1", capture: "01"}, before: 20, retained: 15, removed: 5}, {group_id: "g2", selector: {sample: "S2", capture: "02"}, before: 20, retained: 15, removed: 5}]}, filter_impacts: [{independently_removed: 8, exclusively_removed: 3}, {independently_removed: 7, exclusively_removed: 2}], overlap: {counts: [[8, 5], [5, 7]], interpretation: "Measured overlap"}};
  value.analysis.foundation_executed = false; value.analysis.status = "not_executed";
  value.qc.summary.cells = 40; value.qc.preview = {hash: h64("a"), details}; value.strategy.review.details.canonical_proposal.qc = proposal; value.strategy.review.details.canonical_proposal.doublet = {method: "remove_predicted", reason: "Explicit reviewed prediction intersection"}; value.strategy.review.details.qc_impact = details;
  value.strategy.review.hash = h64("b"); value.strategy.review.details.applicability.doublet = {before: 30, retained: 28, removed: 2}; value.strategy.review.lifecycle = {status: "awaiting_review"}; value.annotation = {status: "not_recorded", review: null}; value.outputs = {artifacts: []}; return value;
}
await check("different QC scopes keep exact thresholds and overlap totals are never added", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); h.wire("child-A", value); await h.call("wbLoad"); assert.equal(h.state.failed, false);
  assert.match(flowNode(h, "qc").textContent, /Suggested.*nFeature ≥ 200.*sample=S1.*capture=01.*nFeature ≥ 400.*sample=S2.*capture=02.*Projected: 40 → 30 cells; 10 unique removals.*Doublet policy: remove_predicted/s);
  assert.doesNotMatch(flowNode(h, "qc").textContent, /15 unique removals|12 unique removals/);
  assert.match(h.el("wb-flow-details").textContent, /ANY failed rule \(OR failures\).*counts are not added.*S1.*200.*S2.*400.*quality-QC preview.*removed 10.*not an execution receipt.*Projected retained.*Separate doublet policy: remove_predicted.*intersection/s);
  assert.equal(h.el("wb-flow-details").children[0].getAttribute("open"), null);
  value.qc.preview.details.canonical_parameters.proposal.remove_if = "all"; value.strategy.review.details.canonical_proposal.qc.remove_if = "all"; h.wire("child-A", value); await h.call("wbLoad"); assert.match(h.el("wb-flow-details").textContent, /ALL failed rules \(AND failures\)/);
  assert(h.requests.every(request => request.options.method === "GET"));
});
await check("approved strategy remains unexecuted until saved apply checkpoint completes", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = {kind: "strategy", review_hash: value.strategy.review.hash, decision_id: "decision-4", can_decide: false, undone: false}; h.wire("child-A", value); await h.call("wbLoad");
  assert.equal(flowNode(h, "decision").getAttribute("data-flow-status"), "Approved · awaiting execution"); assert.equal(flowNode(h, "qc").getAttribute("data-flow-status"), "Approved · awaiting execution"); assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Not run"); assert.equal(flowNode(h, "output").getAttribute("data-flow-status"), "Not run");
  value.run.completed.push("strategy_apply", "analysis"); value.run.nodes.strategy_apply = "EXECUTED"; value.analysis.foundation_executed = true; value.run.stage = "markers"; h.wire("child-A", value); await h.call("wbLoad"); assert.equal(flowNode(h, "decision").getAttribute("data-flow-status"), "Executed"); assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Executed"); assert.match(flowNode(h, "qc").textContent, /Projected: 40 → 30/);
});
await check("executed foundation with an absent PC projection does not imply analysis is unrun or infer dimensions", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); value.strategy.review.details.canonical_proposal.pcs = {method: "computed_variance", threshold: .87}; value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = {kind: "strategy", review_hash: value.strategy.review.hash, decision_id: "decision-4", can_decide: false, undone: false}; h.wire("child-A", value); await h.call("wbLoad");
  assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Not run"); assert.match(flowNode(h, "foundation").textContent, /Saved PC policy: 0\.87 \/ computed_variance; selected count unavailable until recorded execution/);
  value.analysis.foundation_executed = true; value.run.completed.push("analysis"); value.run.stage = "markers"; h.wire("child-A", value); await h.call("wbLoad");
  assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Executed"); assert.match(flowNode(h, "foundation").textContent, /Saved PC policy: 0\.87 \/ computed_variance; Executed PC count is not exposed by the current saved projection/); assert.doesNotMatch(flowNode(h, "foundation").textContent, /until recorded execution|Executed PCs 22/); assert(h.requests.every(request => request.options.method === "GET"));
});
await check("annotation approval and failed or deferred work preserve their true current state", async () => {
  const h = harness(), value = savedStage(); value.annotation.review.hash = h64("c"); value.annotation.review.lifecycle = {executed: false, current_proposal: false}; value.run.nodes.annotation_apply = "PLANNED"; value.run.status = "ready"; value.run.stage = "annotation_apply"; value.run.review_node = {kind: "annotation", review_hash: value.annotation.review.hash, decision_id: "decision-4", can_decide: false, undone: false}; h.wire("parent", value); await h.call("wbLoad");
  assert.equal(flowNode(h, "annotation").getAttribute("data-flow-status"), "Approved · awaiting execution"); assert.match(flowNode(h, "annotation").textContent, /not finalized/); assert.equal(flowNode(h, "output").getAttribute("data-flow-status"), "Not run");
  value.run.status = "failed"; value.run.nodes.annotation_apply = "FAILED"; h.wire("parent", value); await h.call("wbLoad"); assert.equal(flowNode(h, "annotation").getAttribute("data-flow-status"), "Failed");
  value.run.status = "awaiting_configuration"; value.run.nodes.annotation_apply = "NEEDS_CONFIGURATION"; value.run.review_node = null; h.wire("parent", value); await h.call("wbLoad"); assert.equal(flowNode(h, "annotation").getAttribute("data-flow-status"), "Deferred · configuration needed");
});
await check("unrun and missing scalar counts never become zero or invented thresholds", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); value.run.status = "ready"; value.run.stage = "qc_evidence"; value.run.nodes = {}; value.run.completed = []; value.run.diagnostics = {cell_count: null, feature_count: ""}; value.qc = {status: "not_recorded", summary: null, preview: null}; value.strategy = {status: "not_recorded", review: null}; value.analysis = {foundation_executed: false}; h.wire("child-A", value); await h.call("wbLoad");
  assert.match(flowNode(h, "input").textContent, /cells Unavailable.*features Unavailable/); assert.equal(flowNode(h, "qc").getAttribute("data-flow-status"), "Not run"); assert.match(flowNode(h, "qc").textContent, /Thresholds unavailable; no default applied/); assert.match(flowNode(h, "foundation").textContent, /Parameters unavailable.*PC policy unavailable.*Resolution unavailable.*Result counts unavailable/s);
  for (const scalar of [null, undefined, "", "0", NaN, Infinity, -1]) assert.equal(h.call("wbCount", scalar), "Unavailable"); assert.equal(h.call("wbCount", 0), "0");
});
await check("processed reuse does not invent threshold execution or normalization settings", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(flowNode(h, "qc").getAttribute("data-flow-status"), "Reused"); assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Reused"); assert.match(flowNode(h, "qc").textContent, /keep original PCA and UMAP/); assert.doesNotMatch(flowNode(h, "qc").textContent, /Projected|nFeature|percent_mt/); assert.doesNotMatch(flowNode(h, "foundation").textContent, /LogNormalize|HVGs|Saved resolution/); assert.equal(h.el("wb-flow-details").children.length, 2); assert.match(h.el("wb-flow-details").textContent, /Quality QC.*Unavailable.*Reused; no execution/s);
});
await check("stale or missing approval fingerprints cannot claim the current proposal is approved", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); value.run.status = "ready"; value.run.stage = "strategy_apply"; value.run.review_node = {kind: "strategy", review_hash: h64("0"), decision_id: "old-decision", can_decide: false, undone: false}; h.wire("child-A", value); await h.call("wbLoad"); assert.equal(flowNode(h, "decision").getAttribute("data-flow-status"), "Suggested · awaiting review"); assert.doesNotMatch(h.el("wb-next").textContent, /decision is saved/);
  delete value.strategy.review.hash; value.run.review_node.review_hash = h64("b"); h.wire("child-A", value); await h.call("wbLoad"); assert.doesNotMatch(flowNode(h, "decision").textContent, /Approved/);
});
await check("an undone annotation takes priority over historical executed stage markers", async () => {
  const h = harness(), value = savedStage(); value.annotation.review.lifecycle = {executed: false, undone: true}; value.run.nodes.annotation_apply = "EXECUTED"; value.run.completed = []; value.run.status = "awaiting_configuration"; h.wire("parent", value); await h.call("wbLoad"); assert.equal(flowNode(h, "annotation").getAttribute("data-flow-status"), "Undone · needs fresh review"); assert.match(flowNode(h, "annotation").textContent, /Previous decision undone/); assert.doesNotMatch(flowNode(h, "annotation").textContent, /Executed/);
});
await check("executed parameters and proposal values have separate source labels", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = view("child-A"); value.strategy.summary = {execution: {neighbors: {pcs: {ndim: 7, denominator: "sum of variances of 12 computed PCs only"}}, cluster: {resolution: .4}}}; h.wire("child-A", value); await h.call("wbLoad"); assert.match(flowNode(h, "foundation").textContent, /Saved foundation plan.*Executed PCs 7.*12 computed PCs.*Executed resolution 0\.4/s); assert.match(h.el("wb-flow-details").textContent, /Saved typed strategy proposal.*Actual saved strategy execution/s); assert.match(flowNode(h, "decision").textContent, /fixed/);
});
await check("dynamic MAD thresholds retain exact group values and unavailable measurements", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = groupedQC(); const panel = {grouping: {method: "column", column: "sample_id", declared_role: "sample", source: "Public fixture declaration"}, groups: [{group_id: "mad1", value: "sample-A", metrics: {percent_mt: {available: true, transform: "identity", exact: {lower_raw: null, upper_raw: 7.213456789123}}}}, {group_id: "mad2", value: "sample-B", metrics: {percent_mt: {available: true, transform: "identity", exact: {upper_raw: 12.987654321234}}, nFeature: {available: false, exact: {lower_raw: null, lower_transformed: null}}}}]};
  value.qc.preview.details.mad_panel = panel; value.strategy.review.details.mad_panel = panel; value.qc.preview.details.canonical_parameters.proposal.rules.push({op: "mad_preset", preset_id: "high_mt3", panel_hash: h64("a")}); h.wire("child-A", value); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-flow-details").textContent, /Every saved MAD group.*MAD thresholds differ.*Exact raw upper.*sample-A.*7\.213456789123.*sample-B.*12\.987654321234.*nFeature.*Unavailable/s); assert.doesNotMatch(flowNode(h, "qc").textContent, /percent_mt ≤ 7|percent_mt ≤ 12/); assert.match(flowNode(h, "qc").textContent, /\+1 more scoped rules/);
});
const savedCount = (source, cells, hash = h64("f")) => ({status: "saved", source, artifact_sha256: hash, cells});
function withStageCounts(value) {
  const counts = {schema: "scagentkit.stage-counts.v1", input: savedCount("input_checkpoint", 40), qc: savedCount("executed_quality_qc_checkpoint", 30), selection: savedCount("executed_doublet_selection_checkpoint", 28), analysis: savedCount("executed_analysis_checkpoint", 28), output: {status: "unavailable", source: null, artifact_sha256: null, cells: null}, prefilter: {status: "saved", source: "verified_prefilter_record", artifact_sha256: h64("e"), method: "min_counts", original_cells: 40, eligible_cells: 38, excluded_cells: 2}};
  value.run.computed_diagnostics = {stage_counts: counts}; value.analysis.computed_diagnostics = {stage_counts: counts}; return value;
}
await check("marker preview rounds display only and never converts missing statistics to zero", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(h.call("wbPreviewNumber", 2.1234567891234), "2.12"); assert.equal(h.call("wbPreviewNumber", 1.7), "1.70"); assert.equal(h.call("wbPreviewNumber", 0), "0.00");
  for (const missing of [null, undefined, "", "0", NaN, Infinity]) assert.equal(h.call("wbPreviewNumber", missing), "Unavailable");
  assert.match(h.el("wb-marker-preview").textContent, /avg log2FC 2\.12/); assert.doesNotMatch(h.el("wb-marker-preview").textContent, /2\.1234567891234/); assert.match(h.el("wb-markers").textContent, /2\.1234567891234/); assert.equal(h.state.view.evidence.clusters[0].markers[0].avgLog2FC, 2.1234567891234);
});
await check("completed summary uses actual counts and executed dimensions while keeping full risks accessible", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = withStageCounts(groupedQC()); value.run.status = "complete"; value.run.stage = "complete"; value.provider.name = "manual";
  value.strategy.summary = {execution: {neighbors: {pcs: {ndim: 7, available_pcs: 12}}, cluster: {resolution: .4}}}; value.strategy.review.details.canonical_proposal.risks = "QC retention, embeddings and clusters do not prove biological correctness."; value.strategy.review.details.canonical_proposal.qc.risks = "These neutral ranges are a control starting point, not suggested QC thresholds.";
  value.annotation = view("child-A").annotation; value.annotation.review.details.annotations.push({...value.annotation.review.details.annotations[0], clusterId: "extra"}); h.wire("child-A", value); await h.call("wbLoad");
  assert.equal(h.el("wb-parameter-summary").textContent, "QC 40→30 · ANY 2 rules · PCs 7/12 · res 0.4"); assert.match(h.el("wb-flow-details").textContent, /10 unique removals.*actual QC checkpoint 30/s);
  assert.equal(h.el("wb-risk").textContent, "Manual / no provider · all 3 Unknown / low, uncalibrated confidence · biological identities unverified / provisional · QC can remove valid populations · QC rules are a control example, not recommended thresholds."); assert.match(h.el("wb-risk-details").textContent, /do not prove biological correctness.*neutral ranges are a control starting point.*provisional/s);
  value.annotation.review.details.annotations[0].proposal.confidence = "high"; h.wire("child-A", value); await h.call("wbLoad"); assert.match(h.el("wb-risk").textContent, /all 3 Unknown ·/); assert.doesNotMatch(h.el("wb-risk").textContent, /Unknown \/ low/);
  value.analysis.computed_diagnostics.stage_counts.qc.cells = null; h.wire("child-A", value); await h.call("wbLoad"); assert.match(h.el("wb-parameter-summary").textContent, /^QC projected 40→30/); assert(h.requests.every(request => request.options.method === "GET"));
});
await check("actual checkpoint counts stay separate from projected QC and doublet hits", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = withStageCounts(groupedQC()); value.run.status = "running"; value.run.stage = "strategy_apply"; value.run.nodes.strategy_apply = "RUNNING"; h.wire("child-A", value); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(flowNode(h, "qc").textContent, /Projected: 40 → 30 cells; 10 unique removals.*Actual checkpoint cells: input 40; quality QC 30; separate doublet selection 28/s); assert.equal(flowNode(h, "qc").getAttribute("data-flow-status"), "Executed"); assert.match(flowNode(h, "foundation").textContent, /Actual analysis checkpoint: 28 cells/); assert.match(h.el("wb-flow-details").textContent, /Actual saved cell counts.*Quality QC30Saved checkpoint.*Separate doublet selection28Saved checkpoint.*Final outputUnavailableNot recorded.*minimal prefilter: min_counts; original 40; eligible for scoring 38; excluded 2/s); assert.equal(flowNode(h, "output").getAttribute("data-flow-status"), "Not run");
});
await check("a completed quality checkpoint does not invent a missing doublet selection", async () => {
  const h = harness("?child_id=child-A&project_id=child-A"), value = withStageCounts(groupedQC()); value.run.computed_diagnostics.stage_counts.selection = {status: "unavailable", cells: null}; value.run.computed_diagnostics.stage_counts.analysis = {status: "unavailable", cells: null}; h.wire("child-A", value); await h.call("wbLoad"); assert.equal(flowNode(h, "qc").getAttribute("data-flow-status"), "QC executed · selection not recorded"); assert.match(flowNode(h, "qc").textContent, /quality QC 30; separate doublet selection Unavailable/); assert.equal(flowNode(h, "foundation").getAttribute("data-flow-status"), "Not run");
});
await check("invalid stage counts, sources and fingerprints cannot populate actual numbers", async () => {
  const h = harness("?child_id=child-A&project_id=child-A");
  for (const corrupt of [row => row.cells = null, row => row.cells = "", row => row.cells = "0", row => row.cells = -1, row => row.cells = 1.2, row => row.status = "planned", row => row.source = "proposal_retention", row => row.artifact_sha256 = "bad"]) {const value = withStageCounts(groupedQC()); corrupt(value.run.computed_diagnostics.stage_counts.qc); h.wire("child-A", value); await h.call("wbLoad"); assert.match(flowNode(h, "qc").textContent, /quality QC Unavailable/);}
  const value = withStageCounts(groupedQC()); value.run.computed_diagnostics.stage_counts.schema = "foreign"; h.wire("child-A", value); await h.call("wbLoad"); assert.match(flowNode(h, "qc").textContent, /Actual stage counts unavailable; preview only/);
});
await check("pending analysis cell counts require the displayed checkpoint fingerprint", async () => {
  const h = harness(), value = withStageCounts(savedStage()); value.run.computed_diagnostics.stage_counts.analysis.cells = 3; h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.call("wbStageCountRecord", "analysis"), null); value.run.computed_diagnostics.stage_counts.analysis.artifact_sha256 = value.binding.stage_checkpoint_records.analysis.sha256; h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.call("wbStageCountRecord", "analysis").cells, 3);
});
await check("presentation has local fonts, labelled status, readable contrast and reduced motion", () => {
  const css = fs.readFileSync(path.join(root, "static/workbench.css"), "utf8"); assert.doesNotMatch(css, /@import|https?:\/\/|url\(/); assert.match(css, /prefers-reduced-motion:reduce/); assert.match(css, /focus-visible/); assert.match(html, /id="wb-status"[^>]*role="status"[^>]*aria-live="polite"/);
  const luminance = hex => {const channels = hex.match(/[a-f0-9]{2}/gi).map(value => parseInt(value, 16) / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4); return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;}; const ratio = (a, b) => (Math.max(luminance(a), luminance(b)) + .05) / (Math.min(luminance(a), luminance(b)) + .05);
  const token = name => css.match(new RegExp("--" + name + ":#([a-f0-9]{6})")).at(1); for (const name of ["ink", "muted", "blue"]) assert(ratio(token(name), "ffffff") >= 4.5, name); assert(ratio("ffffff", token("blue")) >= 4.5);
});
await check("stale refresh clears the entire workflow and rejoin only restores verified GET data", async () => {
  const h = harness(); h.wire(); await h.call("wbLoad"); const changed = view(); changed.binding.revision += 1; h.wire("parent", changed); await h.call("wbLoad"); assert.equal(h.state.failed, true); assert.equal(h.el("wb-flow").children.length, 0); assert.equal(h.el("wb-flow-details").children.length, 0); h.wire(); h.listeners.pageshow({persisted: true}); for (let tick = 0; tick < 20 && h.state.busy; tick++) await Promise.resolve(); assert.equal(h.state.failed, false); assert.equal(h.el("wb-flow").children.length, 7); assert(h.requests.every(request => request.options.method === "GET"));
});
function withAudit(value, empty = false) {
  const auditEvents = empty ? [] : events(2, "integration");
  if (!empty) {auditEvents[0].action = "applied"; auditEvents[1].action = "undone";}
  const audit = {schema: "scagentkit.subcluster.integration-history.v1", revision: auditEvents.length, head: empty ? null : auditEvents.at(-1).hash, events: auditEvents, total_events: auditEvents.length, provided_events: auditEvents.length, truncated: false, authority: empty ? "not_created" : "reintegration/state.rds"};
  value.integration_history = audit; Object.assign(value.binding, {integration_state_sha256: empty ? null : h64("a"), integration_revision: audit.revision, integration_history_head: audit.head}); return value;
}
await check("child application audit is separate, complete and read-only", async () => {const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A", withAudit(view("child-A"))); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.equal(h.state.view.run.revision, 4); assert.match(h.el("wb-history-summary").textContent, /4 supplied event headers of 4/); assert.match(h.el("wb-history-content").textContent, /Saved derived application audit.*2 supplied event headers of 2.*independent.*applied.*undone/s); assert.equal(descend(h.el("wb-history-content")).some(node => ["BUTTON", "INPUT", "FORM"].includes(node.tagName)), false);});
await check("uncreated child application journal is explicit rather than inferred", async () => {const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A", withAudit(view("child-A"), true)); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-history-content").textContent, /0 supplied event headers of 0.*not_created.*No derived application journal/s);});
for (const [name, mutate] of [["foreign parent audit", value => value.project.scope = "parent"], ["changed application head", value => value.binding.integration_history_head = h64("0")], ["changed application revision", value => value.binding.integration_revision = 100], ["missing application state hash", value => value.binding.integration_state_sha256 = null], ["changed application links", value => value.integration_history.events[1].previous_hash = h64("0")], ["changed application count", value => value.integration_history.total_events = 50], ["false uncreated journal", value => value.integration_history.authority = "not_created"]]) await check("mismatched application audit fails closed: " + name, async () => {const h = harness("?child_id=child-A&project_id=child-A"), value = withAudit(view("child-A")); mutate(value); h.wire("child-A", value); await h.call("wbLoad"); assert.equal(h.state.failed, true); assert.equal(h.state.view, null);});
await check("processed entry shows original reuse reason without invented QC or execution", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.match(h.el("wb-qc-status").textContent, /skipped/); assert.match(h.el("wb-qc-content").textContent, /keep original PCA and UMAP/); assert.equal(descend(h.el("wb-qc-content")).some(node => node.tagName === "TABLE"), false); assert.match(h.el("wb-analysis-status").textContent, /foundation computation was not executed/); assert.match(h.el("wb-stages").textContent, /Reused \/ skipped/);});
await check("child keeps actual recorded QC quantiles and typed strategy facts", async () => {const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A"); await h.call("wbLoad"); assert.match(h.el("wb-qc-content").textContent, /sample.*01.*250.*180.*280/s); assert.match(h.el("wb-strategy-content").textContent, /Condition is not a batch/); assert.equal(h.el("wb-review").textContent, "Review result");});
await check("pending current review remains clearly separate from revision tools", async () => {const h = harness("?child_id=child-A&project_id=child-A"); h.wire("child-A", view("child-A", {pending: true})); await h.call("wbLoad"); assert.equal(h.el("wb-review").textContent, "Review current step");});
await check("missing output displays unavailable rather than sample coordinates", async () => {const h = harness(); h.wire("parent", view("parent", {noEvidence: true})); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-umap").textContent, /Embedding unavailable/); assert.equal(descend(h.el("wb-umap")).filter(node => node.tagName === "CIRCLE").length, 0);});
await check("pending annotation displays verified checkpoint plots and markers without final labels or artifacts", async () => {const h = harness(), value = savedStage(); h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, false, h.el("wb-notice").textContent); assert.match(h.el("wb-metrics").textContent, /Analysis cells3Exact checkpoint cell universe; annotation pending/); assert.doesNotMatch(h.el("wb-metrics").textContent, /Exact exported cell universe/); assert.match(h.el("wb-analysis-status").textContent, /Annotation is not finalized; labels remain provisional/); assert.match(h.el("wb-analysis-content").textContent, /verified saved analysis checkpoints.*not finalized.*not final output labels/s); assert.match(h.el("wb-analysis-content").textContent, /One point represents one literal cell ID/); assert.match(h.el("wb-embedding-summary").textContent, /3 plotted cells.*annotation not finalized/s); assert.equal(descend(h.el("wb-umap")).filter(node => node.tagName === "CIRCLE").length, 3); assert.match(h.el("wb-markers").textContent, /CD3D.*2\.1234567891234/s); assert.match(h.el("wb-outputs-content").textContent, /No completed artifacts/); assert.doesNotMatch(h.el("wb-umap").textContent, /old T/); assert(h.requests.every(request => request.options.method === "GET"));});
await check("approved checkpoint awaits execution without claiming approval is missing", async () => {const h = harness(), value = savedStage(); value.run.status = "ready"; value.run.stage = "annotation_apply"; h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-analysis-status").textContent, /Annotation is not finalized/); assert.doesNotMatch(h.el("wb-analysis-status").textContent, /pending approval/);});
await check("saved checkpoint review failure stays recoverable with real evidence", async () => {const h = harness(), value = savedStage(); value.run.status = "failed"; h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-analysis-status").textContent, /Annotation is not finalized; labels remain provisional/); assert.match(h.el("wb-analysis-content").textContent, /verified saved analysis checkpoints.*not finalized.*not final output labels/s); assert.equal(h.el("wb-review").textContent, "Review current step");});
for (const [name, mutate] of [["undeclared source", value => delete value.evidence_kind], ["final output masquerade", value => value.evidence_kind = "final_output_bundle"], ["complete run", value => value.run.status = "complete"], ["foreign stage", value => value.run.stage = "strategy_propose"], ["simultaneous output bundle", value => value.run.output = {bundle: "/fixed/bundle"}], ["foreign evidence owner", value => value.binding.evidence_project_id = "foreign"], ["missing checkpoint", value => delete value.binding.stage_checkpoint_records.markers], ["extra checkpoint", value => value.binding.stage_checkpoint_records.raw = {path: "checkpoints/raw.rds", sha256: h64("a")}], ["foreign checkpoint path", value => value.binding.stage_checkpoint_records.analysis.path = "checkpoints/../private.rds"], ["invalid checkpoint hash", value => value.binding.stage_checkpoint_records.markers.sha256 = "bad"], ["unverified records hash", value => value.binding.stage_records_hash = null], ["stale state", value => value.evidence.parameters.savedStageSnapshot.stateSHA = h64("0")], ["stale input", value => value.evidence.parameters.savedStageSnapshot.inputHash = h64("0")], ["stale config", value => value.evidence.parameters.savedStageSnapshot.configHash = h64("0")], ["stale implementation", value => value.evidence.parameters.savedStageSnapshot.implementationHash = h64("0")], ["stale revision", value => value.evidence.parameters.savedStageSnapshot.revision = 3], ["stale history", value => value.evidence.parameters.savedStageSnapshot.historyHead = h64("0")], ["foreign cell scope", value => value.evidence.parameters.savedStageSnapshot.scopeHash = h64("0")], ["foreign membership", value => value.evidence.parameters.savedStageSnapshot.bundleScopeHash = h64("0")], ["changed checkpoint receipt", value => value.evidence.parameters.savedStageSnapshot.records.markers.sha256 = h64("0")], ["unapproved source label", value => value.evidence.clusters[0].sourceAnnotations = [{value: "invented T", count: 2}]], ["unapproved display label", value => value.evidence.clusters[0].sourceLabels = "invented T"]]) await check("pending checkpoint mismatch fails closed: " + name, async () => {const h = harness(), value = savedStage(); mutate(value); h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, true); assert.equal(h.state.view, null); assert.equal(h.el("wb-review").hidden, true); assert.equal(h.el("wb-metrics").children.length, 0);});
await check("literal 01 and 1 clusters remain distinct and local point selection never reads or writes", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); const count = h.requests.length; assert.equal(descend(h.el("wb-umap")).filter(node => node.tagName === "CIRCLE").length, 3); h.call("wbSelectCluster", "1"); assert.equal(h.state.clusterId, "1"); assert.match(h.el("wb-markers").textContent, /CD79A/); assert.doesNotMatch(h.el("wb-markers").textContent, /CD3D/); h.call("wbSelectCluster", "01"); assert.match(h.el("wb-markers").textContent, /2\.1234567891234/); assert.equal(h.requests.length, count);});
await check("real provider configuration has no fixed simulated badge", async () => {const h = harness(); h.wire("parent", view("parent", {provider: "deepseek"})); await h.call("wbLoad"); assert.match(h.el("wb-model").textContent, /deepseek.*deepseek-flash/); assert.doesNotMatch(h.el("wb-model").textContent, /mock|simulated/i);});
await check("mock configuration is conspicuous while manual remains manual", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.match(h.el("wb-model").textContent, /mock.*simulated/); h.wire("parent", view("parent", {provider: "manual"})); await h.call("wbLoad"); assert.match(h.el("wb-model").textContent, /Manual/); assert.doesNotMatch(h.el("wb-model").textContent, /mock|simulated/i);});
await check("GeneCards uses run species without reference-species inference", async () => {for (const [species, links] of [["human", 1], ["mouse", 0]]) {const h = harness(); h.wire("parent", view("parent", {species})); await h.call("wbLoad"); assert.equal(descend(h.el("wb-markers")).filter(node => node.tagName === "A").length, links);}});
await check("mapped mouse markers and citations retain originals and all official candidates", async () => {
  const h = harness(), value = view("parent", {species: "mouse"});
  for (const gene of ["Lyz2", "Adh1"]) {
    value.evidence.clusters[0].markers[0].gene = gene;
    value.annotation.review.details.annotations[0].proposal.markers = [gene];
    value.annotation.review.details.annotations[0].supplied_marker_stats[0].gene = gene;
    h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, false);
    const anchors = descend(h.el("wb-markers")).filter(node => node.tagName === "A"), expected = gene === "Lyz2" ? ["LYZ"] : ["ADH1A", "ADH1B", "ADH1C"];
    assert.equal(anchors.length, expected.length + 1);
    assert.equal(anchors[0].getAttribute("href"), "https://www.informatics.jax.org/accession/" + encodeURIComponent(gene === "Lyz2" ? "MGI:96897" : "MGI:87921"));
    assert.deepEqual(anchors.slice(1).map(node => node.getAttribute("data-gene-symbol")), expected);
    assert(h.el("wb-markers").textContent.includes(gene));
    assert(h.el("wb-annotation-content").textContent.includes(gene));
    assert.equal(value.evidence.clusters[0].markers[0].gene, gene);
    for (const node of anchors) {assert.equal(node.getAttribute("target"), "_blank"); assert.equal(node.getAttribute("rel"), "noopener noreferrer"); assert.equal(node.getAttribute("referrerpolicy"), "no-referrer");}
  }
  assert(h.requests.every(request => request.options.method === "GET"));
});
await check("saved HTML-like context, genes, reasons and output paths remain inert", async () => {const h = harness(), value = view(); value.run.context.notes = "<img src=x onerror=never()>"; value.evidence.clusters[0].markers[0].gene = "<svg onload=never()>"; value.history.events[0].details.reason = "<script>never()</script>"; value.outputs.artifacts[0].path = "javascript:never()"; h.wire("parent", value); await h.call("wbLoad"); assert.equal(h.state.failed, false); assert.match(h.el("wb-background").textContent, /<img/); assert.match(h.el("wb-history-content").textContent, /<script>/); assert.equal(descend(h.el("wb-outputs-content")).some(node => node.getAttribute?.("href") === "javascript:never()"), false);});
await check("untrusted navigation URLs cannot leave the known scoped tools", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); assert.equal(h.el("wb-review").getAttribute("href"), "/review?project_id=parent"); assert.equal(h.el("wb-child-action").getAttribute("href"), "/subclusters?project_id=parent"); assert.equal(descend(h.el("wb-children-content")).some(node => node.getAttribute?.("href")?.startsWith("https://foreign")), false);});
await check("refresh updates workspace-derived receipts even at unchanged parent revision", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); const changed = view(); changed.children[0].applications[0].output_path = "integration/derived-new-parent.rds"; changed.binding.workspace_fingerprint = h64("0"); h.wire("parent", changed); await h.call("wbLoad"); assert.equal(h.state.view.run.revision, 4); assert.match(h.el("wb-outputs-content").textContent, /derived-new-parent.rds/); assert.equal(h.requests.length, 4); assert(h.requests.every(request => request.options.method === "GET" && request.options.cache === "no-store"));});
await check("duplicate refresh does not duplicate in-flight reads", async () => {const h = harness(); let release; h.handler = async url => {if (url === "/api/run-review/scopes") await new Promise(resolve => {release = resolve;}); return {ok: true, json: async () => url === "/api/run-review/scopes" ? scopes() : view()};}; const first = h.call("wbLoad"); await h.call("wbLoad"); assert.equal(h.requests.length, 1); release(); await first; assert.equal(h.requests.length, 2);});
await check("page rejoin only refreshes readonly evidence, with no job or provider endpoint", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); h.listeners.pageshow({persisted: true}); for (let tick = 0; tick < 20 && h.state.busy; tick++) await Promise.resolve(); assert.equal(h.state.busy, false); assert.equal(h.requests.length, 4); assert(h.requests.every(request => !/(decision|continue|suggestion|operation)/.test(request.url)));});
await check("failed refresh clears previous context, counts and scientific content", async () => {const h = harness(); h.wire(); await h.call("wbLoad"); h.handler = async () => {throw new Error("Saved snapshot changed");}; await h.call("wbLoad"); assert.equal(h.state.view, null); assert.equal(h.el("wb-context").textContent, ""); assert.equal(h.el("wb-marker-summary").textContent, ""); assert.equal(h.el("wb-history-summary").textContent, ""); assert.match(h.el("wb-title").textContent, /unavailable/); assert.equal(h.el("wb-review").hidden, true);});
await check("render never embeds generic workbench or supplies science forms", () => {assert.doesNotMatch(html, /<iframe|\/index\.html|\/api\/project|<form|type="password"/); assert.doesNotMatch(source, /method:\s*["']POST|\/api\/(?:project|session|export)|sendBeacon\s*\(/); for (const [, code] of modules) assert.doesNotMatch(code, /\bfetch\s*\(/);});
await check("pending input diagnostics are displayed without inventing output cells", async () => {const h = harness(), value = view("parent", {noEvidence: true}); value.run.diagnostics = {cell_count: 2700, feature_count: 32738, sparse_counts: true}; h.wire("parent", value); await h.call("wbLoad"); assert.match(h.el("wb-metrics").textContent, /Input cells2,700.*no output inferred/s); assert.match(h.el("wb-diagnostics").textContent, /32738/); assert.match(h.el("wb-metrics").textContent, /Clusters—/);});
if (process.argv[3]) await check("recorded actual backend HTTP response is compatible with production frontend", async () => {const value = JSON.parse(fs.readFileSync(path.resolve(process.argv[3]), "utf8")), id = value.project.project_id, h = harness("?project_id=" + encodeURIComponent(id)), registered = {schema: "scagentkit.run-scopes.workbench.v1", workspace_enabled: false, parent: {project_id: id, input_hash: value.project.input_hash, revision: value.project.revision, ready: false, frozen: value.project.frozen, status: value.run.status}, children: []}; h.handler = async url => ({ok: true, json: async () => clone(url === "/api/run-review/scopes" ? registered : value)}); await h.call("wbLoad"); assert.equal(h.state.failed, false, h.el("wb-notice").textContent); assert.equal(h.state.view.project.project_id, id); assert(h.requests.every(request => request.options.method === "GET"));});
const files = ["workbench.html", "workbench.js", "workbench.css", "ortholog-map.js", "gene-links.js", "evidence-display.js"], report = {schema: "scagentkit.unified-workbench.dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualR: false, actualNetwork: false, paidAPICalls: 0, sourceHashes: Object.fromEntries(files.map(file => [file, sha(fs.readFileSync(path.join(root, "static", file)))])), driverSHA256: sha(fs.readFileSync(fileURLToPath(import.meta.url))), checks: results.length, passed: results.filter(result => result.passed).length, failed: results.filter(result => !result.passed).length, results};
if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n");
console.log(JSON.stringify(report, null, 2)); if (report.failed) process.exitCode = 1;
