// Production-source offline DOM checks. No browser, R, provider or network.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import assert from "node:assert/strict";
import {webcrypto, createHash} from "node:crypto";
import {fileURLToPath} from "node:url";
const __filename = fileURLToPath(import.meta.url), __dirname = path.dirname(__filename);
const repo = path.resolve(__dirname, "../.."), sourcePath = path.join(repo, "workbench/static/subcluster.js"), htmlPath = path.join(repo, "workbench/static/subcluster.html");
const results = [], copy = value => JSON.parse(JSON.stringify(value)), sha = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
class Element {
  constructor(tag = "div") {this.tagName = tag.toUpperCase(); this.children = []; this.attributes = {}; this.dataset = {}; this.value = ""; this._text = ""; this.hidden = false; this.disabled = false; this.inert = false; this.listeners = {}; this.contentWindow = {}; this.className = ""; this.open = false; this.checked = false; this.classList = {toggle() {}};}
  get textContent() {return this._text + this.children.map(child => child instanceof Element ? child.textContent : String(child)).join("");}
  set textContent(value) {this._text = String(value ?? ""); this.children = [];}
  get innerHTML() {throw new Error("Evidence rendering must use textContent");}
  set innerHTML(_) {throw new Error("Evidence rendering must use textContent");}
  insertAdjacentHTML() {throw new Error("Evidence rendering must not insert HTML strings");}
  append(...items) {this.children.push(...items);}
  appendChild(item) {this.append(item); return item;}
  replaceChildren(...items) {this._text = ""; this.children = [...items];}
  setAttribute(key, value) {this.attributes[key] = String(value); if (key === "open") this.open = true; if (key.startsWith("data-")) this.dataset[key.slice(5).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = String(value);}
  getAttribute(key) {return this.attributes[key] ?? null;}
  addEventListener(key, callback) {(this.listeners[key] ||= []).push(callback);}
  reportValidity() {return true;}
  focus() {}
}
const descendants = node => node.children.flatMap(child => child instanceof Element ? [child, ...descendants(child)] : []);
function ui(search = "", kind = "subcluster") {
  const localSource = path.join(repo, "workbench/static/" + kind + ".js"), localHTML = path.join(repo, "workbench/static/" + (kind === "qc" ? "qc" : kind) + ".html");
  const source = fs.readFileSync(localSource, "utf8"), html = fs.readFileSync(localHTML, "utf8"), elements = new Map(), storage = new Map(), timers = new Map(); let timer = 0;
  assert.match(source, /\nload\(\);\s*$/);
  for (const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)) {assert.equal(elements.has(match[2]), false, "Duplicate production HTML ID"); elements.set(match[2], new Element(match[1]));}
  const harness = {requests: [], fetchImpl: null}, document = {body: {dataset: {}}, getElementById(id) {assert(elements.has(id), `Missing production HTML ID ${id}`); return elements.get(id);}, createElement(tag) {return new Element(tag);}};
  const window = {location: {origin: "http://127.0.0.1:19999", search, assign(url) {harness.navigation = url;}}, addEventListener() {}, confirm() {return false;}};
  const context = vm.createContext({document, window, URLSearchParams, AbortController, Uint8Array, crypto: webcrypto,
    sessionStorage: {getItem(key) {return storage.get(key) ?? null;}, setItem(key, value) {storage.set(key, value);}, removeItem(key) {storage.delete(key);}},
    setTimeout(callback, delay) {timers.set(++timer, {callback, delay}); return timer;}, clearTimeout(id) {timers.delete(id);},
    async fetch(url, options) {harness.requests.push({url, options}); assert(harness.fetchImpl, "Offline tests forbid network"); return harness.fetchImpl(url, options);}});
  vm.runInContext(source.replace(/\nload\(\);\s*$/, "\n"), context, {filename: sourcePath});
  harness.state = vm.runInContext("state", context); harness.call = (name, ...args) => vm.runInContext(name, context)(...args); harness.el = id => document.getElementById(id);

  return harness;
}
const parentHash = "a".repeat(64), inputHash = "b".repeat(64), annotationHash = "c".repeat(64), applyHash = "d".repeat(64);
function answer(selected = false) {
  const value = {schema: "scagentkit.subcluster.workbench.v1", csrf_token: "scope-token", local_continue: true,
    parent: {schema: "scagentkit.subcluster.parent.v1", parent_project_id: "parent", input_hash: inputHash, parent_scope_hash: parentHash, parent_output_hash: "e".repeat(64), expected_parent_revision: 10, total_cells: 91, cluster_column: "seurat_clusters", context: {species: "human", tissue: "synthetic"}, clusters: [{clusterId: "01", cell_count: 40}, {clusterId: "1", cell_count: 50}, {clusterId: "NA", cell_count: 1}]},
    children: selected ? [{project_id: "literal-child", status: "complete", stage: "finalize", revision: 20}] : [], child: null};
  if (selected) value.child = {schema: "scagentkit.subcluster.child.v1", run: {schema: "scagentkit.run.v1", project_id: "literal-child", input_hash: inputHash, revision: 20, status: "complete", stage: "finalize"}, origin: {parent_project_id: "parent", parent_scope_hash: parentHash, selected_clusters: ["01"], selected_cells: 40}, parent_current: true, integration_revision: 2, applications: [], apply_snapshot: {project_id: "literal-child", input_hash: inputHash, expected_revision: 20, parent_scope_hash: parentHash, expected_parent_revision: 10, annotation_hash: annotationHash, apply_hash: applyHash, column: "sc_subtype", outside: "NA", selected_cells: 40, retained_cells: 40}};
  return value;
}
function contextAnswer(enabled = true) {
  const value = answer(true), current = value.child.run;
  current.status = enabled ? "awaiting_review" : "complete"; current.stage = enabled ? "annotation_apply" : "finalize";
  value.child.apply_snapshot = enabled ? null : value.child.apply_snapshot;
  current.child_context = {schema: "scagentkit.child-context.v1", generation: 0, previous_hash: null, hash: "f".repeat(64),
    effective: {enabled: true, lineage_hint: "T cells", identity_status: "labeled", tissue: "blood", notes: "Original soft hypothesis"},
    parent_snapshot: {identity_status: "labeled", annotations: [{parentClusterId: "01", labels: ["T cells"], cellCount: 40}]}};
  value.child.context_edit = {schema: "scagentkit.child-context-edit.v1", enabled, reason: enabled ? "Stopped child annotation context can be corrected." : "Completed child is read-only; undo the annotation first.",
    allowed_fields: ["enabled", "lineage_hint", "identity_status", "tissue", "notes"], context_hash: current.child_context.hash, generation: 0,
    binding: enabled ? {project_id: current.project_id, input_hash: current.input_hash, expected_revision: current.revision, expected_context_hash: current.child_context.hash, parent_scope_hash: value.parent.parent_scope_hash, expected_parent_revision: value.parent.expected_parent_revision} : null};
  return value;
}
function setupContext(enabled = true) {const h = ui("?child_id=literal-child&project_id=literal-child"); h.state.view = h.call("verify", contextAnswer(enabled)); h.call("render"); return h;}
function correctedContext(payload) {
  const value = contextAnswer(), current = value.child.run;
  current.revision++; current.status = "awaiting_configuration"; current.stage = "annotation_propose";
  current.child_context = {...current.child_context, generation: 1, previous_hash: current.child_context.hash, hash: "9".repeat(64), effective: payload.context};
  value.child.context_edit.context_hash = current.child_context.hash; value.child.context_edit.generation = 1;
  value.child.context_edit.binding.expected_revision = current.revision; value.child.context_edit.binding.expected_context_hash = current.child_context.hash;
  value.child.context_receipt = {schema: "scagentkit.child-context-receipt.v1", action: "context", outcome: "committed", request_id: payload.request_id,
    request_hash: "7".repeat(64), payload_sha256: "6".repeat(64), journal_event_hash: "5".repeat(64), project_id: payload.project_id,
    input_hash: payload.input_hash, expected_revision: payload.expected_revision, parent_scope_hash: payload.parent_scope_hash,
    expected_parent_revision: payload.expected_parent_revision, previous_context_hash: payload.expected_context_hash,
    context_hash: current.child_context.hash, generation: 1, committed_revision: current.revision,
    context: copy(payload.context), reviewer: payload.reviewer, reason: payload.reason, is_current: true};
  return value;
}
function creationAnswer(clusters) {const value = answer(true); value.child.origin.selected_clusters = clusters; return value;}
function setup(selected = false) {const h = ui(selected ? "?child_id=literal-child" : ""); h.state.view = h.call("verify", answer(selected)); h.el("sub-column").value = "sc_subtype"; h.el("sub-annotation-column").value = "sc_subtype"; h.el("sub-choice-qc").value = "retain_selected"; h.el("sub-choice-batch").value = "none"; h.el("sub-choice-reference").value = "none"; h.call("render"); return h;}
function fields(h, action) {h.el("sub-" + action + "-reviewer").value = "analyst"; h.el("sub-" + action + "-reason").value = "Review actual selected scope";}
async function check(name, action) {try {await action(); results.push({name, passed: true});} catch (error) {results.push({name, passed: false, error: error.message});}}
async function main() {
  await check("unified child navigation keeps exact scope and never starts a task", () => {const h = setup(true); assert.equal(h.el("sub-home").getAttribute("href"), "/workbench?child_id=literal-child&project_id=literal-child"); assert.equal(h.el("sub-header-review").getAttribute("href"), "/review?child_id=literal-child&project_id=literal-child"); assert.equal(h.el("sub-header-current").getAttribute("href"), "#sub-child-panel"); assert.match(h.el("sub-current-scope").textContent, /Independent child.*literal-child.*Parent parent/); assert.equal(h.requests.length, 0);});
  await check("saved child context is a read-only matching draft until an explicit edit", () => {const h = setupContext(); assert.equal(h.el("sub-context-panel").hidden, false); assert.equal(h.el("sub-context-save").disabled, true); assert.match(h.el("sub-context-summary").textContent, /hypothesis.*not.*validated/); assert.equal(h.requests.length, 0);});
  await check("native canonical key order leaves identical context clean and strict value edits dirty", () => {const h = ui("?child_id=literal-child&project_id=literal-child"), value = contextAnswer(), effective = value.child.run.child_context.effective; value.child.run.child_context.effective = Object.fromEntries(Object.keys(effective).sort().map(key => [key, effective[key]])); h.state.view = h.call("verify", value); h.call("render"); assert.equal(h.call("contextDirty"), false); assert.equal(h.el("sub-context-save").disabled, true); assert.match(h.el("sub-context-status").textContent, /matches the saved annotation context/); for (const [id, changed] of [["sub-context-enabled", false], ["sub-context-lineage", "B cells"], ["sub-context-identity", "mixed"], ["sub-context-tissue", "lung"], ["sub-context-notes", "Updated hypothesis"]]) {h.state.contextDraftHash = null; h.call("renderContext"); if (id === "sub-context-enabled") h.el(id).checked = changed; else h.el(id).value = changed; h.call("buttons"); assert.equal(h.call("contextDirty"), true); assert.equal(h.el("sub-context-save").disabled, false); assert.match(h.el("sub-context-status").textContent, /Unsaved annotation context/);} h.state.contextDraftHash = null; h.call("renderContext"); h.call("buttons"); assert.equal(h.call("contextDirty"), false); assert.equal(h.el("sub-context-save").disabled, true); assert.equal(h.requests.length, 0);});
  await check("typed context correction sends exact bindings and explicit null without model or compute", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-enabled").checked = false; h.el("sub-context-lineage").value = ""; h.el("sub-context-tissue").value = "new tissue"; h.el("sub-context-notes").value = "Engineering check\nnot biological truth"; h.call("buttons"); assert.equal(h.el("sub-context-save").disabled, false); h.fetchImpl = async (_url, options) => ({ok: true, json: async () => correctedContext(JSON.parse(options.body))}); await h.call("saveContext"); assert.equal(h.requests.length, 1); const payload = JSON.parse(h.requests[0].options.body); assert.equal(payload.action, "context"); assert.equal(payload.child_id, "literal-child"); assert.equal(payload.project_id, "literal-child"); assert.equal(payload.input_hash, inputHash); assert.equal(payload.expected_revision, 20); assert.equal(payload.expected_context_hash, "f".repeat(64)); assert.equal(payload.parent_scope_hash, parentHash); assert.equal(payload.expected_parent_revision, 10); assert.deepEqual(payload.context, {enabled: false, lineage_hint: null, identity_status: "labeled", tissue: "new tissue", notes: "Engineering check\nnot biological truth"}); assert.equal(h.el("sub-context-save").disabled, true); assert.equal(h.state.view.child.run.child_context.generation, 1); assert.match(h.el("sub-message").textContent, /proposals, approvals and transfer consents are inactive.*reused.*no model request/); assert.equal(h.navigation, undefined);});
  await check("same-scope old context snapshot cannot clear a submitted correction", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Changed hypothesis"; h.call("buttons"); h.fetchImpl = async () => ({ok: true, json: async () => contextAnswer()}); await h.call("saveContext"); assert.equal(h.state.stale, true); assert(h.state.pending); assert.equal(h.state.view.child.run.child_context.generation, 0); assert.match(h.el("sub-message").textContent, /receipt.*exact correction.*request is retained/); assert.doesNotMatch(h.el("sub-message").textContent, /correction saved/); await h.call("saveContext"); assert.equal(h.requests.length, 1);});
  await check("wrong context receipt request, edits or durable result remains pending", async () => {for (const mutate of [v => v.child.context_receipt.request_id = "foreign-request", v => v.child.context_receipt.context.notes = "foreign-edit", v => v.child.context_receipt.previous_context_hash = "1".repeat(64), v => v.child.context_receipt.expected_revision++, v => v.child.context_receipt.context_hash = "1".repeat(64), v => v.child.context_receipt.generation++, v => v.child.context_receipt.committed_revision = 20, v => v.child.context_receipt.journal_event_hash = "bad", v => v.child.run.child_context.previous_hash = "1".repeat(64), v => v.child.context_receipt.payload_sha256 = "bad", v => v.child.context_receipt.reviewer = "foreign-reviewer", v => v.child.context_receipt.is_current = false]) {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Changed hypothesis"; h.call("buttons"); h.fetchImpl = async (_url, options) => {const v = correctedContext(JSON.parse(options.body)); mutate(v); return {ok: true, json: async () => v};}; await h.call("saveContext"); assert.equal(h.state.stale, true); assert(h.state.pending); assert.equal(h.state.view.child.run.child_context.generation, 0); assert.equal(h.requests.length, 1);}});
  await check("exact context replay accepts a historical durable receipt without replacing newer context", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Original correction"; h.call("buttons"); h.fetchImpl = async () => {throw new Error("Lost committed response");}; await h.call("saveContext"); const payload = copy(h.state.pending), latest = correctedContext(payload); latest.child.run.revision = 23; latest.child.run.child_context = {...latest.child.run.child_context, generation: 2, previous_hash: latest.child.run.child_context.hash, hash: "8".repeat(64), effective: {...latest.child.run.child_context.effective, notes: "Later correction"}}; latest.child.context_edit.generation = 2; latest.child.context_edit.context_hash = latest.child.run.child_context.hash; latest.child.context_edit.binding.expected_context_hash = latest.child.run.child_context.hash; latest.child.context_edit.binding.expected_revision = 23; latest.child.context_receipt.is_current = false; h.fetchImpl = async () => ({ok: true, json: async () => latest}); await h.call("operate", h.state.pending); assert.deepEqual(JSON.parse(h.requests[1].options.body), payload); assert.equal(h.state.pending, null); assert.equal(h.state.stale, false); assert.equal(h.el("sub-context-notes").value, "Later correction"); assert.match(h.el("sub-message").textContent, /already saved at generation 1.*newer generation 2.*does not replace newer context or decisions/); assert.equal(h.navigation, undefined);});
  await check("same-context exact replay acknowledges later workflow decisions without declaring them inactive", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Saved correction"; h.call("buttons"); h.fetchImpl = async () => {throw new Error("Lost committed response");}; await h.call("saveContext"); const payload = copy(h.state.pending), latest = correctedContext(payload); latest.child.run.revision = 30; latest.child.run.status = "complete"; latest.child.run.stage = "finalize"; latest.child.context_edit.enabled = false; latest.child.context_edit.binding = null; latest.child.context_edit.reason = "Completed child context is read-only."; h.fetchImpl = async () => ({ok: true, json: async () => latest}); await h.call("operate", h.state.pending); assert.deepEqual(JSON.parse(h.requests[1].options.body), payload); assert.equal(h.state.pending, null); assert.equal(h.state.stale, false); assert.equal(h.state.view.child.run.status, "complete"); assert.equal(h.state.view.child.run.child_context.generation, 1); assert.equal(h.el("sub-context-save").disabled, true); assert.match(h.el("sub-message").textContent, /already saved at generation 1.*still current.*workflow has advanced to revision 30.*does not replace newer context or decisions/); assert.doesNotMatch(h.el("sub-message").textContent, /approvals.*inactive|new annotation proposal/); assert.equal(h.navigation, undefined);});
  await check("completed or unsupported child context cannot submit edits", async () => {const h = setupContext(false); h.el("sub-context-lineage").value = "other"; h.call("buttons"); await h.call("saveContext"); assert.equal(h.el("sub-context-save").disabled, true); assert.equal(h.el("sub-context-lineage").disabled, true); assert.match(h.el("sub-context-status").textContent, /read-only/); assert.equal(h.requests.length, 0);});
  await check("foreign or stale context capability is rejected before editing", () => {const h = setupContext(); for (const mutate of [v => v.child.context_edit.binding.expected_context_hash = "1".repeat(64), v => v.child.context_edit.binding.expected_revision++, v => v.child.context_edit.binding.parent_scope_hash = "1".repeat(64), v => v.child.context_edit.binding.project_id = "foreign", v => v.child.run.child_context.hash = "bad", v => v.child.run.child_context.generation = -1, v => v.child.run.stage = "strategy_propose", v => v.child.run.status = "running", v => v.child.parent_current = false]) {const value = contextAnswer(); mutate(value); assert.throws(() => h.call("verify", value));} assert.equal(h.requests.length, 0);});
  await check("UTF-8 context limits, invalid identities and controls block saves", () => {const h = setupContext(); for (const [id, text] of [["sub-context-lineage", "界".repeat(67)], ["sub-context-tissue", "a".repeat(201)], ["sub-context-notes", "a".repeat(2001)], ["sub-context-notes", "bad\u0000note"], ["sub-context-lineage", "bad\tlineage"], ["sub-context-identity", "truth"]]) {h.call("renderContext"); h.el(id).value = text; h.call("buttons"); assert.equal(h.el("sub-context-save").disabled, true); assert(h.call("contextDraftError")); h.state.contextDraftHash = null;} assert.equal(h.requests.length, 0);});
  await check("context save doubleclick sends one exact local operation", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Changed hypothesis"; h.call("buttons"); let done; h.fetchImpl = () => new Promise(resolve => {done = resolve;}); const first = h.call("saveContext"); await h.call("saveContext"); assert.equal(h.requests.length, 1); const payload = JSON.parse(h.requests[0].options.body); done({ok: true, json: async () => correctedContext(payload)}); await first; assert.equal(h.state.pending, null);});
  await check("lost context response preserves exact payload and retries without a new request ID", async () => {const h = setupContext(); fields(h, "context"); h.el("sub-context-notes").value = "Changed hypothesis"; h.call("buttons"); h.fetchImpl = async () => {throw new Error("Response disconnected");}; await h.call("saveContext"); const payload = JSON.parse(h.requests[0].options.body); assert.equal(h.state.stale, true); assert.deepEqual(copy(h.state.pending), payload); assert.equal(h.el("sub-context-save").disabled, true); h.fetchImpl = async () => ({ok: true, json: async () => correctedContext(payload)}); await h.call("operate", h.state.pending); assert.deepEqual(JSON.parse(h.requests[1].options.body), payload); assert.equal(h.state.pending, null);});
  await check("context and parent hypothesis text render inert and drafts survive an unchanged refresh", () => {const h = setupContext(); h.el("sub-context-notes").value = "<script>never()</script>"; h.call("render"); assert.equal(h.el("sub-context-notes").value, "<script>never()</script>"); h.state.view.child.run.child_context.parent_snapshot.annotations[0].labels = ["<script>never()</script>"]; h.call("renderContext"); assert.match(h.el("sub-context-parent").textContent, /<script>never/); assert.equal(h.requests.length, 0);});

  await check("parent labels remain literal distinct choices and counts", () => {const h = setup(); assert.equal(h.state.controls.length, 3); assert.deepEqual(copy(h.state.controls.map(node => node.getAttribute("data-cluster-id"))), ["01", "1", "NA"]); assert.match(h.el("sub-clusters").textContent, /01 · 40 cells.*1 · 50 cells.*NA · 1 cells/s); assert.equal(h.el("sub-create").disabled, true); assert.equal(h.requests.length, 0);});
  await check("single rare scope stays blocked without clipped parameters", () => {const h = setup(); h.state.selection.add("NA"); h.call("buttons"); assert.equal(h.call("selectedCount"), 1); assert.equal(h.el("sub-create").disabled, true); assert.match(h.el("sub-selection").textContent, /at least 21 cells.*not.*clipped/);});
  await check("single cluster and explicit multi-cluster union accepted", () => {const h = setup(); h.state.selection.add("01"); h.call("buttons"); assert.equal(h.call("selectedCount"), 40); assert.equal(h.el("sub-create").disabled, false); h.state.selection.add("1"); h.call("buttons"); assert.equal(h.call("selectedCount"), 90); assert.equal(h.requests.length, 0);});
  await check("cancel before creation makes zero mutation requests", async () => {const h = setup(); h.state.selection.add("01"); h.call("cancelSelection"); assert.equal(h.state.selection.size, 0); assert.equal(h.requests.length, 0); assert.match(h.el("sub-message").textContent, /No child.*changed/);});
  await check("cancel writeback restores draft only and sends no request", () => {const h = setup(true); h.el("sub-column").value = "other"; h.state.previewEdited = true; h.call("cancelApply"); assert.equal(h.el("sub-column").value, "sc_subtype"); assert.equal(h.requests.length, 0);});
  await check("unsafe optional strategy disables create without executing text", () => {const h = setup(); h.state.selection.add("01"); for (const value of [{schema: "scagentkit.strategy.v1", provider: {}}, {schema: "scagentkit.strategy.v1", analysis: {code: "never()"}}, {schema: "wrong"}, []]) {h.el("sub-strategy").value = JSON.stringify(value); h.call("buttons"); assert.equal(h.el("sub-create").disabled, true);} assert.equal(h.requests.length, 0);});
  await check("create sends literal labels frozen parent binding and explicit defaults once", async () => {const h = setup(); fields(h, "create"); h.state.selection.add("01"); h.state.selection.add("1"); h.call("buttons"); h.fetchImpl = async (_url, options) => ({ok: true, json: async () => creationAnswer(JSON.parse(options.body).clusters)}); await h.call("createChild"); assert.equal(h.requests.length, 1); const payload = JSON.parse(h.requests[0].options.body); assert.deepEqual(payload.clusters, ["01", "1"]); assert.equal(payload.parent_scope_hash, parentHash); assert.equal(payload.expected_parent_revision, 10); assert.deepEqual(payload.choices, {qc: "retain_selected", doublet: "keep", batch: "none", cycle: "none", reference: "none"}); assert.equal(Object.hasOwn(payload, "project_dir"), false); assert.equal(h.navigation, "/review?child_id=literal-child&project_id=literal-child"); assert.equal(h.state.pending, null);});
  await check("doubleclick while creation response is pending queues only one operation", async () => {const h = setup(); fields(h, "create"); h.state.selection.add("01"); h.call("buttons"); let resolve; h.fetchImpl = () => new Promise(done => {resolve = done;}); const first = h.call("createChild"); await h.call("createChild"); assert.equal(h.requests.length, 1); resolve({ok: true, json: async () => creationAnswer(["01"])}); await first;});
  await check("disconnected operation preserves exact request ID and fields for retry", async () => {const h = setup(); fields(h, "create"); h.state.selection.add("01"); h.call("buttons"); h.fetchImpl = async () => {throw new Error("Disconnected response");}; await h.call("createChild"); const first = JSON.parse(h.requests[0].options.body); assert.equal(h.state.stale, true); assert.deepEqual(copy(h.state.pending), first); assert.equal(h.el("sub-create").disabled, true); h.fetchImpl = async (_url, options) => ({ok: true, json: async () => creationAnswer(JSON.parse(options.body).clusters)}); await h.call("operate", h.state.pending); assert.deepEqual(JSON.parse(h.requests[1].options.body), first); assert.equal(h.state.pending, null);});
  await check("child navigation is URL scoped and does not expose a filesystem path", () => {const h = setup(true); assert.equal(h.el("sub-review-link").getAttribute("href"), "/review?child_id=literal-child&project_id=literal-child"); assert.equal(h.el("sub-create-panel").hidden, true); assert.equal(h.el("sub-apply").disabled, false); assert.equal(h.el("sub-undo-form").hidden, true);});
  await check("foreign, duplicated or path-bearing registry is rejected", () => {const h = setup(); for (const mutate of [v => v.children = [{project_id: "x", project_dir: "/private"}], v => v.children = [{project_id: "x"}, {project_id: "x"}], v => v.parent.clusters[1].clusterId = "01", v => v.parent.total_cells = 1]) {const value = answer(); mutate(value); assert.throws(() => h.call("verify", value));}});
  await check("parent and annotation stale snapshots reject browser submission", () => {const h = setup(true); for (const mutate of [v => v.child.apply_snapshot.expected_revision++, v => v.child.apply_snapshot.parent_scope_hash = "f".repeat(64), v => v.child.apply_snapshot.annotation_hash = "invalid", v => v.child.run.project_id = "foreign"]) {const value = answer(true); mutate(value); assert.throws(() => h.call("verify", value));}});
  await check("parent-current false blocks apply even with unchanged-looking draft", () => {const h = setup(true); h.state.view.child.parent_current = false; h.call("render"); assert.equal(h.el("sub-apply").disabled, true); assert.match(h.el("sub-parent-current").textContent, /binding changed.*blocked/);});
  await check("edited target requires refreshed R preview and includes no outside policy guessing", () => {const h = setup(true); h.el("sub-column").value = "new_subtype"; h.state.previewEdited = true; h.call("buttons"); assert.equal(h.el("sub-apply").disabled, true); assert.equal(h.call("inspectURL"), "/api/subcluster/inspect?child_id=literal-child&column=new_subtype"); const value = answer(true); value.child.apply_snapshot.column = "new_subtype"; h.state.view = h.call("verify", value); h.state.previewEdited = false; h.call("render"); assert.equal(h.el("sub-apply").disabled, false);});
  await check("apply sends only authoritative snapshot fields plus reviewer and request", async () => {const h = setup(true); fields(h, "apply"); h.fetchImpl = async (_url, options) => {const value = answer(true), payload = JSON.parse(options.body); value.child.active_application_id = "exact-application"; value.child.applications = [{application_id: "exact-application", active: true, status: "applied", request_id: payload.request_id, child_project_id: payload.child_id, parent_project_id: "parent", child_input_hash: payload.input_hash, child_revision: payload.expected_revision, parent_input_hash: value.parent.input_hash, parent_scope_hash: payload.parent_scope_hash, parent_revision: payload.expected_parent_revision, parent_output_sha256: value.parent.parent_output_hash, apply_hash: payload.apply_hash, annotation_hash: payload.annotation_hash, column: payload.column, outside: payload.outside, output_sha256: "f".repeat(64)}]; return {ok: true, json: async () => value};}; await h.call("apply"); assert.equal(h.navigation, "/review?project_id=parent#run-derived-details"); const payload = JSON.parse(h.requests[0].options.body); assert.equal(payload.child_id, "literal-child"); assert.equal(payload.apply_hash, applyHash); assert.equal(payload.annotation_hash, annotationHash); assert.equal(payload.outside, "NA"); assert.equal(Object.hasOwn(payload, "selected_cells"), false); assert.equal(Object.hasOwn(payload, "cells"), false);});
  await check("navigation rejects changed parent binding after create without clearing exact pending request", async () => {const h = setup(); fields(h, "create"); h.state.selection.add("01"); h.call("buttons"); h.fetchImpl = async () => {const value = answer(true); value.parent.parent_scope_hash = "f".repeat(64); value.child.origin.parent_scope_hash = value.parent.parent_scope_hash; return {ok: true, json: async () => value};}; await h.call("createChild"); assert.equal(h.state.stale, true); assert(h.state.pending); assert.equal(h.navigation, undefined); assert.equal(h.requests.length, 1);});
  await check("create cannot automatically navigate to another literal selection", async () => {const h = setup(); fields(h, "create"); h.state.selection.add("01"); h.call("buttons"); h.fetchImpl = async () => ({ok: true, json: async () => creationAnswer(["1"])}); await h.call("createChild"); assert.equal(h.state.stale, true); assert(h.state.pending); assert.equal(h.navigation, undefined); assert.equal(h.requests.length, 1);});
  await check("apply response without exact active saved receipt cannot navigate or submit again", async () => {const h = setup(true); fields(h, "apply"); h.fetchImpl = async () => ({ok: true, json: async () => answer(true)}); await h.call("apply"); assert.equal(h.state.stale, true); assert(h.state.pending); assert.equal(h.navigation, undefined); await h.call("apply"); assert.equal(h.requests.length, 1);});
  await check("manual Unknown is offered only at the recorded annotation configuration boundary", async () => {const h = setup(true); h.state.view.child.run.status = "awaiting_configuration"; h.state.view.child.run.stage = "annotation_propose"; h.state.view.child.apply_snapshot = null; h.call("render"); assert.equal(h.el("sub-unknown-panel").hidden, false); assert.equal(h.el("sub-unknown").disabled, false); fields(h, "unknown"); h.fetchImpl = async () => {const value = answer(true); value.child.run.status = "awaiting_review"; value.child.run.stage = "annotation_propose"; value.child.apply_snapshot = null; return {ok: true, json: async () => value};}; await h.call("unknown"); const payload = JSON.parse(h.requests[0].options.body); assert.equal(payload.action, "unknown"); assert.equal(payload.project_id, "literal-child"); assert.equal(Object.hasOwn(payload, "annotations"), false); assert.equal(h.el("sub-unknown-panel").hidden, true);});
  await check("undo needs an explicitly active application and integration revision", async () => {const h = setup(true); h.state.view.child.active_application_id = "own-active"; h.state.view.child.applications = [{application_id: "own-active", active: true, column: "sc_subtype", output_path: "local-receipt-only"}]; h.call("render"); assert.equal(h.el("sub-undo-form").hidden, false); fields(h, "undo"); h.fetchImpl = async () => ({ok: true, json: async () => answer(true)}); await h.call("undo"); const payload = JSON.parse(h.requests[0].options.body); assert.equal(payload.application_id, "own-active"); assert.equal(payload.integration_revision, 2); assert.equal(Object.hasOwn(payload, "parent_project"), false);});
  await check("no implicit latest application or numeric cluster to parent mapping", () => {const h = setup(true); h.state.view.child.applications = [{application_id: "first"}, {application_id: "last"}]; h.call("render"); assert.equal(h.call("activeApplication"), null); assert.equal(h.el("sub-undo").disabled, true); assert.equal(h.requests.length, 0);});
  await check("normal review API forwards only exact child ID including escaped literal characters", () => {const h = ui("?child_id=child%20%2F%20literal", "review"); assert.equal(h.call("scopedRunURL", "/api/run-review/inspect"), "/api/run-review/inspect?child_id=child+%2F+literal"); assert.equal(h.call("scopedRunURL", "/review-qc?localContinue=1"), "/review-qc?localContinue=1&child_id=child+%2F+literal"); assert.equal(ui("", "review").call("scopedRunURL", "/api/run-review/inspect"), "/api/run-review/inspect");});
  await check("QC iframe API forwards same literal child without a path or global selector", () => {const h = ui("?child_id=child-A&localContinue=1", "qc"); assert.equal(h.call("scopedQCURL", "/api/run-review/inspect"), "/api/run-review/inspect?child_id=child-A"); assert.equal(h.call("scopedQCURL", "/api/run-review/decision"), "/api/run-review/decision?child_id=child-A");});
  await check("explicit child review permissions are typed and make no automatic selection", async () => {const h = setup(); h.state.selection.add("01"); h.el("sub-choice-qc").value = "review"; h.el("sub-choice-batch").value = "review"; h.el("sub-choice-reference").value = "inherit"; fields(h, "create"); h.call("buttons"); assert.equal(h.el("sub-create").disabled, false); assert.equal(h.requests.length, 0); h.fetchImpl = async (_url, options) => ({ok: true, json: async () => creationAnswer(JSON.parse(options.body).clusters)}); await h.call("createChild"); assert.deepEqual(JSON.parse(h.requests[0].options.body).choices, {qc: "review", doublet: "keep", batch: "review", cycle: "none", reference: "inherit"});});
  await check("unsupported browser policy disables creation and cancel restores disclosed defaults", () => {const h = setup(); h.state.selection.add("01"); h.el("sub-choice-batch").value = "automatic_harmony"; h.call("buttons"); assert.equal(h.el("sub-create").disabled, true); h.call("cancelSelection"); assert.deepEqual(copy(h.call("creationChoices")), {qc: "retain_selected", doublet: "keep", batch: "none", cycle: "none", reference: "none"}); assert.equal(h.requests.length, 0);});
  await check("pending operation drafts remain child scoped across navigation", () => {const parent = setup(), child = setup(true); assert.notEqual(parent.call("storageKey"), child.call("storageKey")); assert.match(child.call("storageKey"), /literal-child$/);});
  await check("clearing a rejected request after fresh inspect changes draft only", () => {const h = setup(true); h.state.pending = {action: "apply", request_id: "exact"}; h.state.stale = true; h.call("buttons"); assert.equal(h.el("sub-clear-pending").disabled, true); h.call("clearPending"); assert(h.state.pending); h.state.stale = false; h.call("buttons"); h.call("clearPending"); assert.equal(h.state.pending, null); assert.equal(h.requests.length, 0); assert.match(h.el("sub-message").textContent, /already committed.*remains/);});
  const report = {schema: "scagentkit.subcluster.offline-dom-tests.v1", actualProductionSource: true, actualBrowser: false, actualRBridge: false, networkRequests: 0, providerRequests: 0, sourceSha256: sha(sourcePath), htmlSha256: sha(htmlPath), driverSha256: sha(__filename), tests: results.length, passed: results.filter(row => row.passed).length, failed: results.filter(row => !row.passed).length, results};
  if (process.argv[2]) fs.writeFileSync(path.resolve(process.argv[2]), JSON.stringify(report, null, 2) + "\n"); process.stdout.write(JSON.stringify(report, null, 2) + "\n"); if (report.failed) process.exitCode = 1;
}
main().catch(error => {process.stderr.write(error.stack + "\n"); process.exitCode = 1;});
