#!/usr/bin/env node
// Executes production scripts against inert DOM + simulated same-origin HTTP.
// No browser, scientific R, keys, providers or network.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {webcrypto, createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const copy = value => JSON.parse(JSON.stringify(value)), sha = value => createHash('sha256').update(value).digest('hex');
const results = [], parentHash = 'a'.repeat(64), childHash = 'b'.repeat(64);
class Element {
  constructor(tag) {this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.dataset={};this.value='';this._text='';this.hidden=false;this.disabled=false;this.checked=false;this.listeners={};this.contentWindow={};this.classList={toggle(){}};}
  get textContent(){return this._text+this.children.map(c=>c instanceof Element?c.textContent:String(c)).join('');}
  set textContent(v){this._text=String(v??'');this.children=[];}
  set innerHTML(v){throw Error('Untrusted project text must stay inert');}
  append(...items){this.children.push(...items);}
  replaceChildren(...items){this._text='';this.children=items;}
  setAttribute(k,v){this.attributes[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v);}
  getAttribute(k){return this.attributes[k]??null;}
  addEventListener(k,fn){(this.listeners[k] ||= []).push(fn);}
  reportValidity(){return true;} focus(){}
}
function harness(kind='review',search='',storage=new Map()) {
  const source=fs.readFileSync(path.join(repo,'workbench/static/'+kind+'.js'),'utf8'), html=fs.readFileSync(path.join(repo,'workbench/static/'+kind+'.html'),'utf8');
  const elements=new Map(),timers=new Map();let timer=0;for(const m of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"/g)){assert(!elements.has(m[2]));elements.set(m[2],new Element(m[1]));}
  const h={requests:[],fetchImpl:null,timers,storage},document={getElementById(id){assert(elements.has(id),'Missing HTML ID '+id);return elements.get(id);},createElement(tag){return new Element(tag);}};
  const window={location:{origin:'http://127.0.0.1:19999',search,assign(url){h.navigation=url;}},addEventListener(){},confirm(){return false;}};
  const context=vm.createContext({document,window,URLSearchParams,AbortController,Uint8Array,crypto:webcrypto,sessionStorage:{getItem(k){return storage.get(k)??null;},setItem(k,v){storage.set(k,v);},removeItem(k){storage.delete(k);}},setTimeout(fn,ms){timers.set(++timer,{fn,ms});return timer;},clearTimeout(id){timers.delete(id);},async fetch(url,options={}){h.requests.push({url,options});assert(h.fetchImpl,'Network forbidden');return h.fetchImpl(url,options);}});
  assert.match(source,/\nload\(\);\s*$/);vm.runInContext(source.replace(/\nload\(\);\s*$/,'\n'),context);
  h.state=vm.runInContext('state',context);h.call=(name,...args)=>vm.runInContext(name,context)(...args);h.el=id=>document.getElementById(id);h.window=window;return h;
}
function scopes(ready=true){return {schema:'scagentkit.run-scopes.workbench.v1',workspace_enabled:true,parent:{project_id:'parent',input_hash:parentHash,revision:10,status:ready?'complete':'awaiting_review',stage:ready?'complete':'strategy_propose',ready,frozen:ready,output:{seurat:'outputs/original-parent.rds'}},children:ready?[{project_id:'child-A',input_hash:childHash,revision:20,status:'complete',stage:'complete',applications:[{application_id:'apply-A',active:true,column:'sc_subtype',output_path:'integration/derived-A.rds'}]},{project_id:'child-B',input_hash:childHash,revision:3,status:'awaiting_review',stage:'strategy_propose',applications:[]}]:[]};}
function scientific(id='parent'){return {schema:'scagentkit.run-review.workbench.v1',csrf_token:'science-'+id,suggestion_enabled:false,run:{schema:'scagentkit.run.v1',project_id:id,input_hash:id==='parent'?parentHash:childHash,revision:id==='parent'?10:20,status:'complete',stage:'complete',context:{species:'human',tissue:'synthetic'},review_node:null,output:{seurat:id==='parent'?'outputs/original-parent.rds':'outputs/child.rds'}}};}
function workspace(id=null){const child=id?{schema:'scagentkit.subcluster.child.v1',run:scientific(id).run,origin:{parent_project_id:'parent',parent_scope_hash:'c'.repeat(64)},parent_current:true,integration_revision:1,applications:[{application_id:'apply-A',active:true,column:'sc_subtype',output_path:'integration/derived-A.rds'}],active_application_id:'apply-A',apply_snapshot:null}:null;return {schema:'scagentkit.subcluster.workbench.v1',csrf_token:'workspace-token',ready:true,parent:{schema:'scagentkit.subcluster.parent.v1',parent_project_id:'parent',input_hash:parentHash,parent_scope_hash:'c'.repeat(64),parent_output_hash:'d'.repeat(64),expected_parent_revision:10,total_cells:40,clusters:[{clusterId:'01',cell_count:40}],context:{species:'human'},cluster_column:'seurat_clusters'},children:scopes().children,child};}
function waiting(){return {schema:'scagentkit.subcluster.workbench.v1',csrf_token:'workspace-token',ready:false,parent_run:{...scientific().run,status:'awaiting_review',stage:'strategy_propose'},parent:{schema:'scagentkit.subcluster.parent-waiting.v1',parent_project_id:'parent',expected_parent_revision:10},children:[],child:null};}
const response=(value,ok=true)=>({ok,json:async()=>copy(value)});
function wire(h,id='parent',ready=true){h.fetchImpl=async url=>url==='/api/run-review/scopes'?response(scopes(ready)):url.startsWith('/api/subcluster')?response(ready?workspace(id==='parent'?null:id):waiting()):response(scientific(id));}
async function check(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message});}}
await check('fresh parent bootstraps registered scopes before project inspect and sends exact header',async()=>{const h=harness();wire(h);await h.call('load');assert.equal(h.state.stale,false);assert.deepEqual(h.requests.map(r=>r.url),['/api/run-review/scopes','/api/run-review/inspect']);assert.equal(h.requests[1].options.headers['X-ScAgentKit-Run-Project'],'parent');assert.equal(h.requests.every(r=>r.options.method!=='POST'),true);});
await check('child bootstrap and refresh preserve per-tab URL and exact registered header',async()=>{const h=harness('review','?child_id=child-A&project_id=child-A');wire(h,'child-A');await h.call('load');await h.call('load');assert.equal(h.state.view.run.project_id,'child-A');assert.equal(h.requests.filter(r=>r.url.includes('/inspect')).every(r=>r.url==='/api/run-review/inspect?child_id=child-A&project_id=child-A'&&r.options.headers['X-ScAgentKit-Run-Project']==='child-A'),true);assert.equal(h.requests.length,4);});
await check('two tabs have independent selected project state and links',async()=>{const a=harness('review','?project_id=parent'),b=harness('review','?child_id=child-B&project_id=child-B');wire(a);wire(b,'child-B');await Promise.all([a.call('load'),b.call('load')]);assert.equal(a.state.scopeProject,'parent');assert.equal(b.state.scopeProject,'child-B');assert.equal(a.requests[1].options.headers['X-ScAgentKit-Run-Project'],'parent');assert.equal(b.requests[1].options.headers['X-ScAgentKit-Run-Project'],'child-B');assert.equal(a.el('run-scope-links').children.length,3);assert.equal(b.el('run-scope-links').children[2].getAttribute('aria-current'),'page');});
for(const query of ['?child_id=','?project_id=','?child_id=child-A&child_id=child-B','?project_id=parent&project_id=child-A','?child_id=child-A&project_id=parent','?project_dir=/private/data','?path=/private/data','?child_id=%00'])await check('invalid scope URL cannot inspect or mutate: '+query,async()=>{const h=harness('review',query);wire(h);await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.requests.length,0);assert.equal(h.state.view,null);});
await check('unknown child has no parent fallback and stops at registry read',async()=>{const h=harness('review','?child_id=foreign&project_id=foreign');wire(h);await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.requests.length,1);assert.equal(h.state.view,null);});
await check('parent ID must not masquerade as child',async()=>{const h=harness('review','?child_id=parent&project_id=parent');wire(h);await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.requests.length,1);});
await check('foreign project response is rejected even when shape is valid',async()=>{const h=harness('review','?child_id=child-A&project_id=child-A');h.fetchImpl=async url=>response(url.endsWith('/scopes')?scopes():scientific());await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.state.view,null);});
await check('duplicate and path-bearing registry entries are rejected before inspect',async()=>{for(const change of [v=>v.children.push(v.children[0]),v=>v.children[0].project_dir='/private']){const h=harness(),value=scopes();change(value);h.fetchImpl=async()=>response(value);await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.requests.length,1);}});
await check('project URL change in an existing page cannot switch mutation authority',async()=>{const h=harness();wire(h);await h.call('load');h.window.location.search='?child_id=child-A&project_id=child-A';assert.throws(()=>h.call('projectHeaders'),/changed/);await assert.rejects(()=>h.call('request',{project_id:'parent'}));assert.equal(h.requests.length,2);assert.equal(h.state.stale,true);});
await check('parent page distinguishes original output from derived child application',async()=>{const h=harness();wire(h);await h.call('load');assert.match(h.el('run-output').textContent,/original-parent.rds/);assert.match(h.el('run-derived-outputs').textContent,/Derived parent.*active.*child-A.*sc_subtype.*original parent.*derived-A.rds/s);assert.equal(h.el('run-derived-outputs').children[0].children.find(n=>n.tagName==='A').getAttribute('href'),'/subclusters?child_id=child-A&project_id=child-A');assert.equal(h.el('run-workspace-link').getAttribute('href'),'/subclusters?project_id=parent');});
await check('all scope links are mechanical navigation and do not submit any task',async()=>{const h=harness();wire(h);await h.call('load');for(const link of h.el('run-scope-links').children){assert.match(link.getAttribute('href'),/^\/review\?/);assert.equal(Object.keys(link.listeners).length,0);}assert.equal(h.requests.filter(r=>r.options.method==='POST').length,0);});
await check('scope data and application strings render as inert text',async()=>{const h=harness(),value=scopes();value.children[0].applications[0].column='<script>never()</script>';h.fetchImpl=async url=>response(url.endsWith('/scopes')?value:scientific());await h.call('load');assert.match(h.el('run-derived-outputs').textContent,/<script>never\(\)<\/script>/);assert.equal(h.state.stale,false);});
await check('workspace before completion is read-only waiting and links to parent review',async()=>{const h=harness('subcluster','?project_id=parent');wire(h,'parent',false);await h.call('load');assert.equal(h.state.stale,false);assert.equal(h.el('sub-waiting').hidden,false);assert.equal(h.el('sub-create').disabled,true);assert.equal(h.el('sub-create-panel').hidden,true);assert.equal(h.el('sub-parent-review').getAttribute('href'),'/review?project_id=parent');assert.equal(h.requests[1].options.headers['X-ScAgentKit-Run-Project'],'parent');});
await check('same workspace becomes available after parent completion without global selection',async()=>{const h=harness('subcluster','?project_id=parent');wire(h,'parent',false);await h.call('load');wire(h);await h.call('load');assert.equal(h.el('sub-waiting').hidden,true);assert.equal(h.el('sub-create-panel').hidden,false);assert.equal(h.state.scopeProject,'parent');assert.equal(h.requests.length,4);assert.equal(h.requests.every(r=>r.options.method!=='POST'),true);});
await check('child workspace returns parent review and shows derived receipt without application mutation',async()=>{const h=harness('subcluster','?child_id=child-A&project_id=child-A');wire(h,'child-A');await h.call('load');assert.equal(h.state.stale,false);assert.equal(h.el('sub-parent-review').getAttribute('href'),'/review?project_id=parent');assert.equal(h.el('sub-review-link').getAttribute('href'),'/review?child_id=child-A&project_id=child-A');assert.match(h.el('sub-derived-receipts').textContent,/Derived parent.*active.*sc_subtype.*Original parent.*derived-A.rds/s);assert.equal(h.requests[1].options.headers['X-ScAgentKit-Run-Project'],'child-A');});
await check('workspace wrong selected project rejects before inspecting scientific state',async()=>{const h=harness('subcluster','?child_id=child-A&project_id=child-B');wire(h,'child-A');await h.call('load');assert.equal(h.requests.length,0);assert.equal(h.state.stale,true);});
await check('workspace child mismatch rejects response and keeps no fallback parent',async()=>{const h=harness('subcluster','?child_id=child-A&project_id=child-A');h.fetchImpl=async url=>response(url.endsWith('/scopes')?scopes():workspace('child-B'));await h.call('load');assert.equal(h.state.stale,true);assert.equal(h.state.view,null);});
await check('per-child model request draft keys remain isolated even sharing tab storage',()=>{const a=harness(),b=harness(),base={suggestion:{project_id:'parent',input_hash:parentHash,revision:7,suggestion_hash:'c'.repeat(64)}};for(const [h,id] of [[a,'parent'],[b,'child-A']]){h.state.suggestion=copy(base);h.state.suggestion.suggestion.project_id=id;h.el('suggestion-reviewer').value='Analyst';h.el('suggestion-reason').value='Exact transfer review';}const aa=a.call('suggestionPayload','request'),bb=b.call('suggestionPayload','request');assert.notEqual(aa.request_id,bb.request_id);assert.equal(aa.project_id,'parent');assert.equal(bb.project_id,'child-A');});
await check('scope discovery leaves active saved task ID intact and never posts retry',async()=>{const h=harness('review','?child_id=child-A&project_id=child-A');wire(h,'child-A');await h.call('load');h.state.continuation={enabled:true,job:{job_id:'persisted-child-job',status:'running'}};await h.call('loadScopes');assert.equal(h.state.continuation.job.job_id,'persisted-child-job');assert.equal(h.requests.filter(r=>r.options.method==='POST').length,0);});
await check('frozen parent cannot gain scientific authority from stale displayed node',async()=>{const h=harness();wire(h);await h.call('load');h.state.view.effective_readonly=true;assert.equal(h.call('ready'),false);h.state.view.run.output=null;h.call('render');assert.match(h.el('run-output').textContent,/completed source is verified.*unavailable.*inspect.*R/i);assert.match(h.el('run-scope-current').textContent,/completed parent is read-only/);});
await check('active derived receipt opens automatically without submitting an operation',async()=>{const h=harness();wire(h);await h.call('load');assert.equal(h.el('run-derived-details').open,true);assert.match(h.el('run-derived-outputs').textContent,/derived-A.rds/);assert.equal(h.requests.every(r=>r.options.method!=='POST'),true);});
await check('historical receipts alone do not automatically open an active result',async()=>{const h=harness(),value=scopes();value.children[0].applications[0].active=false;h.el('run-derived-details').open=false;h.fetchImpl=async url=>response(url.endsWith('/scopes')?value:scientific());await h.call('load');assert.equal(h.el('run-derived-details').open,false);assert.match(h.el('run-derived-outputs').textContent,/historical/);});
await check('completed child central review has an exact child-scoped writeback link',async()=>{const h=harness('review','?child_id=child-A&project_id=child-A');wire(h,'child-A');await h.call('load');assert.equal(h.el('run-child-tools').hidden,false);assert.equal(h.el('run-child-scope-link').getAttribute('href'),'/subclusters?child_id=child-A&project_id=child-A');assert.match(h.el('run-child-scope-link').textContent,/Review exact child labels and save a new parent object/);assert.equal(h.requests.every(r=>r.options.method!=='POST'),true);});
const files=['review.js','review.html','review.css','subcluster.js','subcluster.html','subcluster.css'];
const report={schema:'scagentkit.single-service.offline-dom-tests.v1',actualProductionSource:true,actualBrowser:false,actualRBridge:false,networkRequests:0,providerRequests:0,keyReads:0,sourceHashes:Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(repo,'workbench/static',f)))])),driverSha256:sha(fs.readFileSync(fileURLToPath(import.meta.url))),tests:results.length,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,results};
if(process.argv[2])fs.writeFileSync(path.resolve(process.argv[2]),JSON.stringify(report,null,2)+'\n');process.stdout.write(JSON.stringify(report,null,2)+'\n');if(report.failed)process.exitCode=1;
