test_that("PC candidates use exactly the first 50 of 51 or 100 computed PCs", {
  for (total in c(51L, 100L)) {
    record <- scAgentKit:::.sc_run_pc_candidates(rep(1, total))
    expect_identical(record$schema, "scagentkit.pc.candidates.v1")
    expect_identical(record$total_computed_pcs, total)
    expect_identical(record$reference_pcs, 50L)
    expect_identical(record$target_reference_pcs, 50L)
    expect_false(record$shortfall)
    expect_identical(record$shortfall_count, 0L)
    expect_identical(record$denominator_value, 50)
    expect_identical(length(record$deviation), total)
    expect_identical(record$variance, rep(1, 50L))
    expect_identical(length(record$fraction_per_pc), 50L)
    expect_identical(length(record$cumulative_fraction), 50L)
    expect_equal(record$fraction_per_pc, rep(.02, 50L))
    expect_identical(record$candidates$p80$ndim, 40L)
    expect_identical(record$candidates$p85$ndim, 43L)
    expect_true(record$candidates$p80$supported)
    expect_true(record$candidates$p85$supported)
    expect_match(record$denominator, "first reference_pcs actually computed PCs")
    expect_match(record$denominator, "not total expressed-gene variance")
    expect_silent(scAgentKit:::.sc_run_pc_verify(record))
    # The existing all-computed-PC denominator would instead cross later.
    legacy_fraction <- cumsum(rep(1 / total, total))
    expect_gt(which(legacy_fraction >= .8)[1L], record$candidates$p80$ndim)
    expect_gt(which(legacy_fraction >= .85)[1L], record$candidates$p85$ndim)
  }
  first <- scAgentKit:::.sc_run_pc_candidates(rep(1, 100L))
  # Extra computed components are still saved and validated, but their size
  # cannot enter the reference denominator or any diagnostic fraction.
  altered <- scAgentKit:::.sc_run_pc_candidates(c(rep(1, 50L), rep(12, 50L)))
  expect_identical(altered$denominator_value, first$denominator_value)
  expect_identical(altered$variance, first$variance)
  expect_identical(altered$fraction_per_pc, first$fraction_per_pc)
  expect_identical(altered$cumulative_fraction, first$cumulative_fraction)
  expect_identical(altered$candidates, first$candidates)
  expect_false(identical(altered$deviation_hash, first$deviation_hash))
  expect_false(identical(altered$hash, first$hash))
})

test_that("a reference shorter than 50 PCs discloses its actual denominator and shortfall", {
  record <- scAgentKit:::.sc_run_pc_candidates(rep(1, 20L))
  expect_identical(record$total_computed_pcs, 20L)
  expect_identical(record$reference_pcs, 20L)
  expect_true(record$shortfall)
  expect_identical(record$shortfall_count, 30L)
  expect_identical(record$denominator_value, 20)
  expect_identical(length(record$fraction_per_pc), 20L)
  expect_identical(record$candidates$p80$ndim, 16L)
  expect_identical(record$candidates$p85$ndim, 17L)
  expect_match(record$interpretation, "without inventing missing components")
  two <- scAgentKit:::.sc_run_pc_candidates(c(1, 1))
  expect_identical(two$reference_pcs, 2L)
  expect_identical(two$shortfall_count, 48L)
  expect_identical(two$candidates$p80$ndim, 2L)
  expect_identical(two$candidates$p85$ndim, 2L)
  expect_true(two$candidates$p80$supported)
  expect_silent(scAgentKit:::.sc_run_pc_verify(two))
})

test_that("exact threshold equality is included and displayed rounding never chooses PCs", {
  equal <- scAgentKit:::.sc_run_pc_candidates(c(2, 1))
  expect_identical(equal$cumulative_fraction[1L], .8)
  expect_identical(equal$candidates$p80$ndim, 1L)
  expect_false(equal$candidates$p80$supported)
  expect_identical(equal$candidates$p85$ndim, 2L)
  expect_true(equal$candidates$p85$supported)
  # This first fraction displays as 0.8, but remains strictly less than 0.8.
  below <- scAgentKit:::.sc_run_pc_candidates(c(1, .5 + .Machine$double.eps))
  expect_lt(below$cumulative_fraction[1L], .8)
  expect_identical(signif(below$cumulative_fraction[1L], 12L), .8)
  expect_identical(below$candidates$p80$ndim, 2L)
  expect_true(below$candidates$p80$supported)
  above <- scAgentKit:::.sc_run_pc_candidates(c(1, .5 - .Machine$double.eps))
  expect_gt(above$cumulative_fraction[1L], .8)
  expect_identical(above$candidates$p80$ndim, 1L)
  expect_false(above$candidates$p80$supported)
  expect_match(above$candidates$p80$reason, "never clipped to two")
  expect_match(above$threshold_comparison, "exact saved numeric values")
  # Both candidates can honestly select one; neither silently grows to two.
  dominated <- scAgentKit:::.sc_run_pc_candidates(c(3, 1))
  expect_identical(dominated$candidates$p80$ndim, 1L)
  expect_identical(dominated$candidates$p85$ndim, 1L)
  expect_false(dominated$candidates$p80$supported)
  expect_false(dominated$candidates$p85$supported)
})

test_that("invalid, zero, overflowing and underflowing PC evidence fails closed", {
  helper <- scAgentKit:::.sc_run_pc_candidates
  for (invalid in list(NULL, numeric(), 1, c(0, 1), c(-1, 1), c(NA_real_, 1),
                       c(NaN, 1), c(Inf, 1), c("1", "2"), list(1, 2), matrix(1, 2, 2)))
    expect_error(helper(invalid), "finite, strictly positive.*at least two")
  expect_error(helper(c(1, .Machine$double.xmax)), "overflowing.*variances")
  expect_error(helper(c(1, 1e-200)), "underflowing variances")
  expect_error(helper(rep(sqrt(.Machine$double.xmax) / 2, 50L)), "variance sum.*overflowing")
  expect_error(helper(c(1e-150, 1e150)), "fractions.*underflowing")
  # Invalid suffix components cannot be hidden behind the first-50 policy.
  expect_error(helper(c(rep(1, 50L), 0)), "strictly positive")
  expect_error(helper(c(rep(1, 50L), Inf)), "strictly positive")
  expect_error(helper(c(rep(1, 50L), .Machine$double.xmax)), "overflowing")
})

test_that("PC diagnostic identity survives serialization and rejects tampered policies or evidence", {
  helper <- scAgentKit:::.sc_run_pc_candidates
  verify <- scAgentKit:::.sc_run_pc_verify
  record <- helper(stats::setNames(1:50, paste0("component", 1:50)))
  expect_identical(record, helper(as.numeric(1:50)))
  expect_type(record$deviation, "double")
  expect_null(names(record$deviation))
  expect_identical(record$hash, scAgentKit:::.sc_run_pc_hash(record))
  expect_identical(unserialize(serialize(record, NULL, version = 2L)), record)
  expect_silent(verify(unserialize(serialize(record, NULL, version = 2L))))
  path <- tempfile(fileext = ".rds")
  on.exit(unlink(path), add = TRUE)
  saveRDS(record, path, version = 2L)
  expect_identical(readRDS(path), record)
  expect_silent(verify(readRDS(path)))
  bad <- record; bad$candidates$p80$ndim <- 2L
  expect_error(verify(bad), "missing or changed")
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent.*threshold crossings")
  bad <- record; bad$denominator_value <- sum(record$variance) * 2
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent.*denominator")
  bad <- record; bad$deviation[1L] <- 999
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent.*standard deviations")
  bad <- helper(rep(1, 100L)); bad$deviation[100L] <- 2
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent.*standard deviations")
  bad <- record; bad$target_reference_pcs <- 100L
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent")
  bad <- record; bad$execute <- "arbitrary unsupported policy"
  bad$hash <- scAgentKit:::.sc_run_pc_hash(bad)
  expect_error(verify(bad), "inconsistent")
})

test_that("PC diagnostic table keeps exact unrounded evidence and explicit candidate support", {
  record <- scAgentKit:::.sc_run_pc_candidates(c(2, 1))
  before <- serialize(record, NULL, version = 2L)
  table <- scAgentKit:::.sc_run_pc_table(record)
  expect_identical(serialize(record, NULL, version = 2L), before)
  expect_identical(table$pc, 1:2)
  expect_identical(table$variance, c(4, 1))
  expect_identical(table$fraction_per_pc, record$fraction_per_pc)
  expect_identical(table$cumulative_fraction, record$cumulative_fraction)
  expect_identical(table$p80_boundary, c(TRUE, FALSE))
  expect_identical(table$p85_boundary, c(FALSE, TRUE))
  expect_identical(table$p80_supported, c(FALSE, FALSE))
  expect_identical(table$p85_supported, c(TRUE, TRUE))
  record <- scAgentKit:::.sc_run_pc_candidates(rep(1, 100L))
  expect_identical(nrow(scAgentKit:::.sc_run_pc_table(record)), 50L)
  expect_identical(tail(scAgentKit:::.sc_run_pc_table(record)$pc, 1), 50L)
})

test_that("PC diagnostic PNG is local and malformed records cannot create an artifact", {
  skip_if_not(capabilities("png"))
  path <- tempfile(fileext = ".png")
  on.exit(unlink(path), add = TRUE)
  record <- scAgentKit:::.sc_run_pc_candidates(rep(1, 20L))
  before <- serialize(record, NULL, version = 2L)
  expect_identical(scAgentKit:::.sc_run_pc_plot(record, path), path)
  expect_identical(serialize(record, NULL, version = 2L), before)
  expect_true(file.exists(path))
  expect_identical(readBin(path, "raw", n = 8L), as.raw(c(137, 80, 78, 71, 13, 10, 26, 10)))
  unlink(path)
  bad <- record; bad$candidates$p85$ndim <- 100L
  expect_error(scAgentKit:::.sc_run_pc_plot(bad, path), "missing or changed")
  expect_false(file.exists(path))
})
