#' Export a self-contained reproducible R script
#'
#' Concatenates all recorded script snippets into a single R file that,
#' when executed, reproduces the analysis from scratch. A header comment
#' documents the pipeline metadata.
#'
#' @param obj An AgentSeurat object.
#' @param path Output file path (default "reproducible_script.R").
#' @param header_comment Optional extra text to include in the file header.
#'
#' @return Invisibly returns `path`.
#' @export
export_script <- function(obj,
                          path           = "reproducible_script.R",
                          header_comment = NULL) {

  stopifnot(methods::is(obj, "AgentSeurat"))

  header <- c(
    "# =============================================================",
    "# Reproducible scRNA-seq analysis script",
    sprintf("# Generated by scAgentKit at %s",
            format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    sprintf("# Pipeline stage: %s", obj@stage),
    sprintf("# Steps recorded: %d", length(obj@decisions)),
    "# =============================================================",
    "",
    "library(Seurat)",
    "library(dplyr)",
    "library(tibble)",
    "library(qs)",
    ""
  )
  if (!is.null(header_comment)) {
    header <- c(header, paste0("# ", header_comment), "")
  }

  writeLines(c(header, obj@scripts), con = path)
  invisible(path)
}

#' Export the decision log as JSON
#'
#' Writes `@@decisions` to a JSON file for audit / inspection. Requires the
#' `jsonlite` package.
#'
#' @param obj An AgentSeurat object.
#' @param path Output path, default "decisions.json".
#'
#' @return Invisibly returns `path`.
#' @export
export_decisions <- function(obj, path = "decisions.json") {
  stopifnot(methods::is(obj, "AgentSeurat"))
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("Package 'jsonlite' is required for export_decisions.")
  }
  # Convert POSIXct timestamps to character so JSON is readable
  decisions <- lapply(obj@decisions, function(d) {
    d$timestamp <- format(d$timestamp, "%Y-%m-%d %H:%M:%S")
    d
  })
  jsonlite::write_json(
    decisions, path = path,
    auto_unbox = TRUE, pretty = TRUE, null = "null"
  )
  invisible(path)
}
